"""
build_interactive.py -- Injects evaluation results into the interactive page
template, producing the single self-contained HTML artefact.

Reads:  data/runs/evaluation.json, one raw document (the horror exhibit),
        one generated parser (the code exhibit), interactive/_template.html
Writes: interactive/erp-cleanup.html   (the published artefact)

Deterministic: same inputs -> byte-identical page. Every number shown on the
page flows from evaluation.json through this script -- nothing is hand-typed.

Usage: python build_interactive.py
"""

import sys
import json
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "data" / "runs"
OUT = ROOT / "interactive" / "erp-cleanup.html"

HORROR_DOC = "2025-01_FBL1N_01"
PARSER_EXHIBIT = "parser_fbl3n.py"

TYPE_IDX = {"FBL3N": 0, "ME2M": 1, "VA05": 2, "FBL1N": 3, "MB52": 4}
PATH_CODE = {"deterministic": "d", "llm_discovery": "l", "llm_fallback": "f"}

SCORECARD_TEXT = {
    "R": ("model during discovery, plain code thereafter",
          "exactly that: 40 discovery, 178 deterministic, zero field errors"),
    "V": ("stays with the model (too rare to learn)",
          "as designed: all six fell back to the model"),
    "F": ("breaks the parser, falls back safely",
          "ten as designed; five parsed correctly instead — the parser was better than our trap"),
    "S": ("passes every check, silently wrong",
          "as designed: caught by nothing except the answer key"),
}


def main():
    ev = json.loads((RUNS / "evaluation.json").read_text(encoding="utf-8"))
    s = ev["summary"]

    docs = [{
        "id": d["doc_id"], "m": int(d["month"][5:7]), "t": TYPE_IDX[d["type"]],
        "c": d["class"], "p": PATH_CODE[d["path"]],
        "ch": round(d["cum_hybrid_usd_est"], 2), "cf": round(d["cum_cf_usd_est"], 2),
        "cost": round(d["cost_hybrid_central_usd_est"], 2), "w": d["wrong_fields"],
    } for d in ev["docs"]]

    activations = [{"i": a["after_idx"], "type": a["type"]} for a in ev["activation_events"]]

    det = s["accuracy"]["deterministic"]
    s_doc = next(d for d in ev["docs"] if d["class"] == "S")
    det_excl = (det["fields"] - s_doc["fields"] - (det["wrong"] - s_doc["wrong_fields"])) \
        / (det["fields"] - s_doc["fields"])
    counts = {}
    for d in ev["docs"]:
        counts[d["class"]] = counts.get(d["class"], 0) + 1

    summary = {
        "det_share_pct": f"{s['deterministic_share'] * 100:.1f}%",
        "det_acc_excl_pct": f"{det_excl * 100:.3f}%",
        "det_acc_incl_pct": f"{det['field_accuracy'] * 100:.3f}%",
        "llm_acc_pct": f"{s['accuracy']['llm']['field_accuracy'] * 100:.3f}%",
        "saving_pct": f"{s['cost_estimates']['saving_share_of_cf'] * 100:.0f}%",
    }

    scorecard = [{"cls": c, "n": counts[c], "designed": SCORECARD_TEXT[c][0],
                  "actual": SCORECARD_TEXT[c][1], "dev": c == "F"}
                 for c in "RVFS"]

    horror_text = (ROOT / "data" / "documents" / f"{HORROR_DOC}.txt") \
        .read_text(encoding="utf-8").split("\f")[0].rstrip()
    parser_code = (ROOT / "code" / "parsers_generated" / PARSER_EXHIBIT) \
        .read_text(encoding="utf-8")

    data = {
        "docs": docs, "activations": activations, "summary": summary,
        "scorecard": scorecard,
        "horror": {"text": horror_text,
                   "caption": f"{HORROR_DOC}.txt, page 1 of the rendered spool file — "
                              "synthetic, built from documented SAP list conventions."},
        "parser": {"code": parser_code,
                   "caption": f"{PARSER_EXHIBIT} — generated by the overseer, verbatim. "
                              "Pure standard library; induced from the first eight accepted "
                              "parses; the answer key was never read."},
    }

    template = (ROOT / "interactive" / "_template.html").read_text(encoding="utf-8")
    marker = "/*__DATA__*/null"
    if marker not in template:
        raise SystemExit("data marker not found in template")
    page = template.replace(marker, json.dumps(data, ensure_ascii=False, separators=(",", ":")))
    OUT.write_text(page, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB), "
          f"{len(docs)} docs, {len(activations)} activations.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
