"""Deterministic parser for supplier s5 (Terasleht OÜ).

Machine-generated by the overseer agent (Claude Sonnet 5, model id
claude-sonnet-5), 2026-07-03, induced from 6 accepted LLM parses and their
matching PDFs / pdfplumber text-and-word dumps:

    2025-01_s5_01, 2025-01_s5_02, 2025-02_s5_01, 2025-02_s5_02,
    2025-03_s5_01, 2025-03_s5_02

Layout summary (English-language Estonian invoice, single page in every
induction document):

    Terasleht OÜ                                  <- supplier name (line 1)
    Invoice number <NUMBER>
    <supplier street>            Issue date <DD.MM.YYYY>      (merged 2-col line)
    <postcode> <city>, <country> Supply date <DD.MM.YYYY>     (merged 2-col line)
    Reg. code: <supplier business id>
    Due date <DD.MM.YYYY>
    Reference (RF) <RF...>
    PO number <PO-...>
    BUYER
    <buyer name>
    <buyer street>
    <postcode> <city>, <country>
    Business ID: <buyer business id>
    VAT ID: <buyer VAT id>
    DESCRIPTION QTY UNIT UNIT PRICE LINE TOTAL         <- table header (verbatim)
    <line item rows, 4-8 observed, 5 whitespace-separated columns each>
    Net total <amount> €
    VAT <rate> % <amount> €
    Total due <amount> €
    Reverse charge (Article 196, Council Directive 2006/112/EC)   <- verbatim
    Payment terms: <text>
    IBAN: <iban> BIC: <bic>
    VAT ID: <supplier VAT id>                          <- footer, near bank details

Landmarks this parser keys on and verifies before trusting any value: the
literal labels "Invoice number", "Issue date", "Supply date", "Reg. code:",
"Due date", "Reference (RF)", "PO number", "BUYER", "Business ID:", "VAT ID:"
(twice - buyer block and footer), the exact table header string, the
"Net total" / "VAT ... %" / "Total due" summary rows, the verbatim reverse
charge sentence, and the "IBAN: ... BIC: ..." line. Money is UK-style
(comma thousands, dot decimals); dates are DD.MM.YYYY; VAT is always 0%
reverse-charge in the induction set; the RF creditor reference is always
present. Country names seen in the induction set: "Estonia" (supplier),
"Finland" (buyer) - mapped explicitly, anything else is unrecognised.

Not observed in the induction set, and therefore NOT handled (any such
document must raise ParserLayoutError rather than being silently guessed
at): more than one page / a repeated table header, any VAT rate other than
0%, a credit note (only "Invoice number" was ever seen, never a credit
note label), a Bankgiro line, blank lines within the body.

Public API: parse(pdf_path: str) -> dict.

Imports: stdlib (re, decimal, pathlib) + pdfplumber only.
"""

from decimal import Decimal
from pathlib import Path

import pdfplumber
import re


class ParserLayoutError(Exception):
    """Raised when a PDF does not match the layout this parser was induced from."""


_COUNTRY_CODE = {
    "Estonia": "EE",
    "Finland": "FI",
}

_CITY_BLOCK_RE = re.compile(r'^(\d{4,6})\s+(.+?),\s*(.+)$')
_DATE_RE = re.compile(r'^(\d{2})\.(\d{2})\.(\d{4})$')
_MONEY_TOKEN = r'\d[\d,]*\.\d{2}'
_LINE_ITEM_RE = re.compile(
    r'^(.+?)\s+(\d+)\s+(\S+)\s+(' + _MONEY_TOKEN + r')\s+(' + _MONEY_TOKEN + r')$'
)


def _canon_date(raw, field_name):
    m = _DATE_RE.match(raw)
    if not m:
        raise ParserLayoutError(f"{field_name}: {raw!r} is not in DD.MM.YYYY format")
    dd, mm, yyyy = m.groups()
    if not (1 <= int(mm) <= 12) or not (1 <= int(dd) <= 31):
        raise ParserLayoutError(f"{field_name}: {raw!r} has an out-of-range day/month")
    return f"{yyyy}-{mm}-{dd}"


def _canon_money(raw, field_name):
    cleaned = raw.replace(",", "")
    if not re.match(r'^\d+\.\d{2}$', cleaned):
        raise ParserLayoutError(f"{field_name}: {raw!r} is not a valid UK-style amount")
    return cleaned


def _canon_int(raw, field_name):
    if not re.match(r'^\d+$', raw):
        raise ParserLayoutError(f"{field_name}: {raw!r} is not a plain integer quantity")
    return str(int(raw))


def _parse_city_block(raw, field_name):
    m = _CITY_BLOCK_RE.match(raw)
    if not m:
        raise ParserLayoutError(
            f"{field_name}: {raw!r} does not match '<postcode> <city>, <country>'"
        )
    postcode, city, country_name = m.groups()
    if country_name not in _COUNTRY_CODE:
        raise ParserLayoutError(f"{field_name}: unrecognised country name {country_name!r}")
    return postcode, city, _COUNTRY_CODE[country_name]


def parse(pdf_path: str) -> dict:
    with pdfplumber.open(pdf_path) as pdf:
        if len(pdf.pages) != 1:
            raise ParserLayoutError(
                f"expected a single-page invoice (every induction document was "
                f"single-page); got {len(pdf.pages)} pages"
            )
        text = pdf.pages[0].extract_text()

    if not text:
        raise ParserLayoutError("page 1 has no extractable text layer")

    lines = [ln.rstrip() for ln in text.splitlines()]

    idx = 0

    def next_line(context):
        nonlocal idx
        if idx >= len(lines):
            raise ParserLayoutError(f"ran out of lines while expecting {context}")
        line = lines[idx]
        idx += 1
        return line

    def expect_literal(expected, context):
        line = next_line(context)
        if line != expected:
            raise ParserLayoutError(f"expected {context} to be {expected!r}, got {line!r}")
        return line

    def expect_match(pattern, context):
        line = next_line(context)
        m = re.match(pattern, line)
        if not m:
            raise ParserLayoutError(f"expected {context} to match {pattern!r}, got {line!r}")
        return m

    # --- header: supplier identity + name line ---
    supplier_name = next_line("supplier name line")
    if not supplier_name.strip():
        raise ParserLayoutError("supplier name line is blank")

    m = expect_match(r'^Invoice number\s+(\S+)$', "invoice number line")
    invoice_number = m.group(1)

    m = expect_match(r'^(.+?)\s+Issue date\s+(\d{2}\.\d{2}\.\d{4})$', "street / issue-date line")
    supplier_street, issue_date_raw = m.group(1), m.group(2)

    m = expect_match(r'^(.+?)\s+Supply date\s+(\d{2}\.\d{2}\.\d{4})$', "city / supply-date line")
    supplier_city_block, supply_date_raw = m.group(1), m.group(2)

    m = expect_match(r'^Reg\.\s*code:\s+(\S+)$', "Reg. code line")
    supplier_business_id = m.group(1)

    m = expect_match(r'^Due date\s+(\d{2}\.\d{2}\.\d{4})$', "due date line")
    due_date_raw = m.group(1)

    m = expect_match(r'^Reference \(RF\)\s+(RF\S+)$', "reference (RF) line")
    reference_value = m.group(1)

    m = expect_match(r'^PO number\s+(\S+)$', "PO number line")
    po_number = m.group(1)

    expect_literal("BUYER", "buyer section label")

    buyer_name = next_line("buyer name line")
    if not buyer_name.strip():
        raise ParserLayoutError("buyer name line is blank")

    buyer_street = next_line("buyer street line")

    buyer_city_block = next_line("buyer city/country line")

    m = expect_match(r'^Business ID:\s+(\S+)$', "buyer Business ID line")
    buyer_business_id = m.group(1)

    m = expect_match(r'^VAT ID:\s+(\S+)$', "buyer VAT ID line")
    buyer_vat_id = m.group(1)

    expect_literal(
        "DESCRIPTION QTY UNIT UNIT PRICE LINE TOTAL", "line-item table header"
    )

    # --- line items ---
    items = []
    while idx < len(lines) and not lines[idx].startswith("Net total"):
        line = next_line("line-item row")
        m = _LINE_ITEM_RE.match(line)
        if not m:
            raise ParserLayoutError(
                f"line-item row did not match the expected 5-column pattern: {line!r}"
            )
        desc, qty_raw, unit, unit_price_raw, line_total_raw = m.groups()
        qty = _canon_int(qty_raw, "line-item quantity")
        unit_price = _canon_money(unit_price_raw, "line-item unit price")
        line_total = _canon_money(line_total_raw, "line-item line total")
        if Decimal(qty) * Decimal(unit_price) != Decimal(line_total):
            raise ParserLayoutError(
                f"line-item arithmetic does not reconcile: {qty} x {unit_price} "
                f"!= {line_total} (row: {line!r})"
            )
        items.append(
            {
                "description": desc,
                "quantity": qty,
                "unit": unit,
                "unit_price": unit_price,
                "vat_rate": None,  # filled in once the invoice-level VAT rate is known
                "line_total": line_total,
            }
        )
    if not items:
        raise ParserLayoutError("no line items found before the 'Net total' row")

    # --- totals / VAT summary ---
    m = expect_match(r'^Net total\s+(' + _MONEY_TOKEN + r')\s*€$', "net total line")
    net_total = _canon_money(m.group(1), "net total")

    m = expect_match(
        r'^VAT\s+(\d+(?:\.\d+)?)\s*%\s+(' + _MONEY_TOKEN + r')\s*€$', "VAT summary line"
    )
    vat_rate_raw, vat_amount_raw = m.group(1), m.group(2)
    if vat_rate_raw not in ("0", "0.0"):
        raise ParserLayoutError(
            f"unexpected VAT rate {vat_rate_raw!r}; this parser was induced only "
            f"from 0% reverse-charge invoices"
        )
    vat_rate = "0.0"
    vat_amount = _canon_money(vat_amount_raw, "VAT amount")

    m = expect_match(r'^Total due\s+(' + _MONEY_TOKEN + r')\s*€$', "total due line")
    gross_total = _canon_money(m.group(1), "total due")

    reverse_charge_mention = expect_literal(
        "Reverse charge (Article 196, Council Directive 2006/112/EC)",
        "reverse charge mention line",
    )

    m = expect_match(r'^Payment terms:\s+(.+)$', "payment terms line")
    payment_terms = m.group(1)

    m = expect_match(r'^IBAN:\s+(\S+)\s+BIC:\s+(\S+)$', "IBAN/BIC line")
    iban, bic = m.group(1), m.group(2)

    m = expect_match(r'^VAT ID:\s+(\S+)$', "supplier VAT ID (footer) line")
    supplier_vat_id = m.group(1)

    if idx != len(lines):
        raise ParserLayoutError(
            f"unexpected trailing content after the supplier VAT ID line: {lines[idx:]!r}"
        )

    # --- invoice-level arithmetic reconciliation ---
    lines_sum = sum(Decimal(item["line_total"]) for item in items)
    if lines_sum != Decimal(net_total):
        raise ParserLayoutError(
            f"line-item totals sum to {lines_sum}, but the printed net total is {net_total}"
        )
    if Decimal(net_total) + Decimal(vat_amount) != Decimal(gross_total):
        raise ParserLayoutError(
            f"net ({net_total}) + VAT ({vat_amount}) != gross ({gross_total})"
        )

    for item in items:
        item["vat_rate"] = vat_rate

    supplier_postcode, supplier_city, supplier_country = _parse_city_block(
        supplier_city_block, "supplier city/country line"
    )
    buyer_postcode, buyer_city, buyer_country = _parse_city_block(
        buyer_city_block, "buyer city/country line"
    )

    issue_date = _canon_date(issue_date_raw, "issue date")
    supply_date = _canon_date(supply_date_raw, "supply date")
    due_date = _canon_date(due_date_raw, "due date")

    return {
        "schema_version": "1.0",
        "doc_id": Path(pdf_path).stem,
        "supplier": {
            "name": supplier_name,
            "street": supplier_street,
            "postcode": supplier_postcode,
            "city": supplier_city,
            "country": supplier_country,
            "vat_id": supplier_vat_id,
            "business_id": supplier_business_id,
        },
        "buyer": {
            "name": buyer_name,
            "street": buyer_street,
            "postcode": buyer_postcode,
            "city": buyer_city,
            "country": buyer_country,
            "vat_id": buyer_vat_id,
            "business_id": buyer_business_id,
        },
        "invoice": {
            "number": invoice_number,
            "type": "invoice",
            "issue_date": issue_date,
            "supply_date": supply_date,
            "due_date": due_date,
            "payment_terms": payment_terms,
            "currency": "EUR",
            "po_number": po_number,
            "reference_type": "rf",
            "reference_value": reference_value,
            "original_invoice_number": None,
            "reverse_charge_mention": reverse_charge_mention,
        },
        "bank": {
            "iban": iban,
            "bic": bic,
            "bankgiro": None,
        },
        "lines": items,
        "vat_summary": [
            {"rate": vat_rate, "base": net_total, "amount": vat_amount},
        ],
        "totals": {
            "net": net_total,
            "vat": vat_amount,
            "gross": gross_total,
        },
    }


if __name__ == "__main__":
    import json
    import sys

    def _load_pairs(argv):
        if len(argv) == 1:
            with open(argv[0], encoding="utf-8") as f:
                manifest = json.load(f)
            pairs = []
            for entry in manifest:
                if isinstance(entry, dict):
                    pairs.append((entry["pdf"], entry["json"]))
                else:
                    pairs.append((entry[0], entry[1]))
            return pairs
        if len(argv) % 2 != 0:
            raise SystemExit(
                "expected an even number of (pdf_path, accepted_parse_json_path) "
                "arguments, or a single manifest JSON path"
            )
        return list(zip(argv[0::2], argv[1::2]))

    pairs = _load_pairs(sys.argv[1:])
    all_ok = True
    for pdf_path, json_path in pairs:
        with open(json_path, encoding="utf-8") as f:
            expected = json.load(f)
        try:
            actual = parse(pdf_path)
        except ParserLayoutError as exc:
            print(f"FAIL {pdf_path}: ParserLayoutError: {exc}")
            all_ok = False
            continue
        if actual == expected:
            print(f"PASS {pdf_path}")
        else:
            all_ok = False
            print(f"FAIL {pdf_path}: parsed output does not match accepted parse")
            for key in expected:
                if actual.get(key) != expected.get(key):
                    print(f"  field {key!r} differs:")
                    print(f"    expected = {expected.get(key)!r}")
                    print(f"    actual   = {actual.get(key)!r}")

    sys.exit(0 if all_ok else 1)
