"""
Deterministic parser for supplier s6 -- Vesijarven Rahtilinja Oy (Finnish freight-service
invoices, 25.5% VAT, no PO number, "viitenumero" payment reference, 14-day terms).

Machine-generated by the overseer agent (model: Claude Sonnet 5, in Claude Code), 2026-07-03.
Induced from 6 accepted LLM parses and their source documents (single induction set, no other
files read):
  2025-01_s6_01, 2025-01_s6_02, 2025-02_s6_01, 2025-02_s6_02, 2025-03_s6_01, 2025-03_s6_02
  (data/runs/llm_parses/<doc_id>.json, data/documents/<doc_id>.pdf,
   data/runs/text_layers/<doc_id>.txt, data/runs/text_layers/<doc_id>.words.json)

Layout observed in all 6 induction documents (single page each):
  - Line 1: supplier name "Vesijarven Rahtilinja Oy".
  - Top-left column: supplier street / "Y-tunnus: <business id>" / "Viitenumero <ref>".
  - Top-right column (same rows): "Lasku <invoice number>" / "Laskun paiva <dd.mm.yyyy>" /
    supplier postcode+city / "Erapaiva <dd.mm.yyyy>".
  - "OSTAJA" block: buyer name / street / postcode+city / "Y-tunnus: <business id>"
    (identical across all 6 documents -- a single, constant buyer).
  - Line-item table, header row "NIMIKE MAARA YKSIKKO A-HINTA ALV % YHTEENSA", 1-3 rows
    observed (brief notes 1-4 possible), each: free-text description, quantity ("1" in
    all rows seen), unit ("kpl" in all rows seen), unit price, VAT rate ("25,5" in all
    rows seen), line total.
  - Totals block: "Veroton yhteensa <net> EUR", "ALV <rate> % <amount> EUR",
    "Maksettava <gross> EUR" (amounts >= 1000 print with a space thousands separator,
    e.g. "1 038,22").
  - Footer, exactly 3 lines after the totals block: "Y-tunnus <business id> --
    ALV-tunnus <vat id>", "Maksuehto: <terms> -- Viitenumero: <ref>",
    "Pankkiyhteys: <iban> BIC: <bic>".

This parser trusts nothing it did not observe. It verifies every label, column header, and
cross-check it relies on (reference number repeated top/bottom, business id repeated
top/bottom, supplier/buyer identity blocks, line-item sum vs printed net, net + VAT vs
printed gross, VAT amount vs rate x base) and raises ParserLayoutError the instant something
is missing, reordered, renamed, or does not reconcile. An exception here is a SUCCESS mode
(the router falls back to the LLM); a silently wrong record is the failure mode this parser
is built to avoid.
"""

import re
from decimal import Decimal, ROUND_HALF_UP, InvalidOperation
from datetime import datetime
from pathlib import Path

import pdfplumber


class ParserLayoutError(Exception):
    """Raised when the PDF does not match the s6 layout this parser was induced from."""


# --- constants induced from the 6 documents (identical in every one of them) ---

_SUPPLIER = {
    "name": "Vesijärven Rahtilinja Oy",
    "street": "Satamakatu 6",
    "postcode": "15140",
    "city": "Lahti",
    "country": "FI",
    "vat_id": "FI22556675",
    "business_id": "2255667-5",
}

_BUYER = {
    "name": "Pyökkipaja Oy",
    "street": "Sorvaajankatu 11",
    "postcode": "15520",
    "city": "Lahti",
    "country": "FI",
    "vat_id": None,
    "business_id": "2417551-8",
}

_BANK = {
    "iban": "FI4480001470683126",
    "bic": "DABAFIHH",
    "bankgiro": None,
}

_ALLOWED_VAT_RATES = {"25.5", "14.0", "10.0", "0.0"}
_HEADER_CELLS = ["NIMIKE", "MÄÄRÄ", "YKSIKKÖ", "A-HINTA", "ALV", "%", "YHTEENSÄ"]


# --- canonicalisation helpers ---

def _clean_money(raw, ctx):
    """'1 038,22' / '294,04' -> '1038.22' / '294.04'. Raises on anything unexpected."""
    compact = re.sub(r"\s", "", raw)
    if not re.fullmatch(r"\d+,\d{2}", compact):
        raise ParserLayoutError(f"{ctx}: unexpected money format {raw!r}")
    whole, frac = compact.split(",")
    return f"{whole}.{frac}"


def _clean_rate(raw, ctx):
    rate = raw.replace(",", ".")
    if rate not in _ALLOWED_VAT_RATES:
        raise ParserLayoutError(f"{ctx}: unexpected VAT rate {raw!r}")
    return rate


def _clean_qty(raw, ctx):
    if not re.fullmatch(r"\d+", raw):
        raise ParserLayoutError(f"{ctx}: unexpected quantity {raw!r}")
    return str(int(raw))


def _iso_date(raw, ctx):
    try:
        return datetime.strptime(raw, "%d.%m.%Y").strftime("%Y-%m-%d")
    except ValueError:
        raise ParserLayoutError(f"{ctx}: unparseable date {raw!r}")


def _to_decimal(raw, ctx):
    try:
        return Decimal(raw)
    except InvalidOperation:
        raise ParserLayoutError(f"{ctx}: not a decimal amount {raw!r}")


def parse(pdf_path: str) -> dict:
    with pdfplumber.open(pdf_path) as pdf:
        if len(pdf.pages) != 1:
            raise ParserLayoutError(
                f"expected a single-page invoice, found {len(pdf.pages)} pages"
            )
        page = pdf.pages[0]
        text = page.extract_text()
        if text is None:
            raise ParserLayoutError("no extractable text layer on page 1")
        words = page.extract_words()

    lines = [ln.strip() for ln in text.split("\n")]

    # ---------------------------------------------------------------
    # Fixed top block: indices 0-13 in every induction document.
    # ---------------------------------------------------------------
    if len(lines) < 14:
        raise ParserLayoutError(f"expected at least 14 header lines, found {len(lines)}")

    if lines[0] != _SUPPLIER["name"]:
        raise ParserLayoutError(f"line 1: expected supplier name, got {lines[0]!r}")

    m = re.fullmatch(r"Lasku\s+(\S+)", lines[1])
    if not m:
        raise ParserLayoutError(f"line 2: expected 'Lasku <number>', got {lines[1]!r}")
    invoice_number = m.group(1)

    if lines[2] != _SUPPLIER["street"]:
        raise ParserLayoutError(f"line 3: expected supplier street, got {lines[2]!r}")

    m = re.fullmatch(r"Laskun päivä\s+(\d{2}\.\d{2}\.\d{4})", lines[3])
    if not m:
        raise ParserLayoutError(f"line 4: expected 'Laskun päivä <date>', got {lines[3]!r}")
    issue_date = _iso_date(m.group(1), "issue date")

    m = re.fullmatch(r"(\d{5})\s+(.+)", lines[4])
    if not m or m.group(1) != _SUPPLIER["postcode"] or m.group(2) != _SUPPLIER["city"]:
        raise ParserLayoutError(f"line 5: expected supplier postcode/city, got {lines[4]!r}")

    m = re.fullmatch(r"Eräpäivä\s+(\d{2}\.\d{2}\.\d{4})", lines[5])
    if not m:
        raise ParserLayoutError(f"line 6: expected 'Eräpäivä <date>', got {lines[5]!r}")
    due_date = _iso_date(m.group(1), "due date")

    m = re.fullmatch(r"Y-tunnus:\s*(\S+)", lines[6])
    if not m or m.group(1) != _SUPPLIER["business_id"]:
        raise ParserLayoutError(f"line 7: expected supplier Y-tunnus, got {lines[6]!r}")

    m = re.fullmatch(r"Viitenumero\s+(\S+)", lines[7])
    if not m:
        raise ParserLayoutError(f"line 8: expected 'Viitenumero <ref>', got {lines[7]!r}")
    reference_top = m.group(1)

    if lines[8] != "OSTAJA":
        raise ParserLayoutError(f"line 9: expected 'OSTAJA', got {lines[8]!r}")

    if lines[9] != _BUYER["name"]:
        raise ParserLayoutError(f"line 10: expected buyer name, got {lines[9]!r}")

    if lines[10] != _BUYER["street"]:
        raise ParserLayoutError(f"line 11: expected buyer street, got {lines[10]!r}")

    m = re.fullmatch(r"(\d{5})\s+(.+)", lines[11])
    if not m or m.group(1) != _BUYER["postcode"] or m.group(2) != _BUYER["city"]:
        raise ParserLayoutError(f"line 12: expected buyer postcode/city, got {lines[11]!r}")

    m = re.fullmatch(r"Y-tunnus:\s*(\S+)", lines[12])
    if not m or m.group(1) != _BUYER["business_id"]:
        raise ParserLayoutError(f"line 13: expected buyer Y-tunnus, got {lines[12]!r}")

    expected_header = " ".join(_HEADER_CELLS)
    if lines[13] != expected_header:
        raise ParserLayoutError(
            f"line 14: expected table header {expected_header!r}, got {lines[13]!r}"
        )

    # ---------------------------------------------------------------
    # Locate the totals block, bounding the line-item region, and check the
    # trailing footer has exactly the 6 lines observed in every induction document.
    # ---------------------------------------------------------------
    veroton_idx = next(
        (i for i, ln in enumerate(lines) if ln.startswith("Veroton yhteensä")), None
    )
    if veroton_idx is None or veroton_idx <= 14:
        raise ParserLayoutError("could not locate 'Veroton yhteensä' line after the table")

    item_lines = lines[14:veroton_idx]
    if not item_lines or len(item_lines) > 4:
        raise ParserLayoutError(f"expected 1-4 line items, found {len(item_lines)}")

    trailer = lines[veroton_idx:]
    if len(trailer) != 6:
        raise ParserLayoutError(
            f"expected exactly 6 trailing totals/footer lines, found {len(trailer)}: {trailer!r}"
        )

    # ---------------------------------------------------------------
    # Line items: parsed from word coordinates, column boundaries taken from the
    # table's own header row on this page (robust to the small per-document
    # positional jitter observed in the induction set).
    # ---------------------------------------------------------------
    nimike_words = [w for w in words if w["text"] == "NIMIKE"]
    if len(nimike_words) != 1:
        raise ParserLayoutError(
            f"expected exactly one 'NIMIKE' table header cell, found {len(nimike_words)}"
        )
    header_top = nimike_words[0]["top"]
    header_row = sorted(
        (w for w in words if abs(w["top"] - header_top) <= 1.0), key=lambda w: w["x0"]
    )
    header_texts = [w["text"] for w in header_row]
    if header_texts != _HEADER_CELLS:
        raise ParserLayoutError(f"table header cells out of order/renamed: {header_texts!r}")

    boundaries = [
        header_row[0]["x0"],  # NIMIKE -> description
        header_row[1]["x0"],  # MÄÄRÄ -> quantity
        header_row[2]["x0"],  # YKSIKKÖ -> unit
        header_row[3]["x0"],  # A-HINTA -> unit price
        header_row[4]["x0"],  # ALV (+ "%" cell, same column) -> vat rate
        header_row[6]["x0"],  # YHTEENSÄ -> line total
    ]
    if boundaries != sorted(boundaries):
        raise ParserLayoutError(f"table columns not left-to-right as expected: {boundaries!r}")

    veroton_words = [w for w in words if w["text"] == "Veroton"]
    if len(veroton_words) != 1:
        raise ParserLayoutError(
            f"expected exactly one 'Veroton' total label, found {len(veroton_words)}"
        )
    veroton_top = veroton_words[0]["top"]
    header_bottom = header_row[0]["bottom"]

    body_words = [w for w in words if header_bottom < w["top"] < veroton_top - 1.0]
    if not body_words:
        raise ParserLayoutError("no words found in the line-item region")

    rows = []
    for w in sorted(body_words, key=lambda w: (w["top"], w["x0"])):
        if rows and abs(w["top"] - rows[-1]["top"]) <= 1.0:
            rows[-1]["words"].append(w)
        else:
            rows.append({"top": w["top"], "words": [w]})

    if len(rows) != len(item_lines):
        raise ParserLayoutError(
            f"line-item row count mismatch between text ({len(item_lines)}) and "
            f"word-coordinate ({len(rows)}) extraction"
        )

    def _col(x0):
        idx = 0
        for i, b in enumerate(boundaries):
            if x0 + 1.0 >= b:
                idx = i
        return idx

    parsed_lines = []
    for row_i, row in enumerate(sorted(rows, key=lambda r: r["top"]), start=1):
        cols = {0: [], 1: [], 2: [], 3: [], 4: [], 5: []}
        for w in sorted(row["words"], key=lambda w: w["x0"]):
            cols[_col(w["x0"])].append(w["text"])
        ctx = f"line item {row_i}"

        if not cols[0]:
            raise ParserLayoutError(f"{ctx}: empty description column")
        description = " ".join(cols[0])

        if len(cols[1]) != 1:
            raise ParserLayoutError(
                f"{ctx}: quantity column has {len(cols[1])} tokens, expected 1"
            )
        quantity = _clean_qty(cols[1][0], ctx)

        if len(cols[2]) != 1:
            raise ParserLayoutError(f"{ctx}: unit column has {len(cols[2])} tokens, expected 1")
        unit = cols[2][0]

        if len(cols[3]) != 1:
            raise ParserLayoutError(
                f"{ctx}: unit price column has {len(cols[3])} tokens, expected 1"
            )
        unit_price = _clean_money(cols[3][0], ctx)

        if len(cols[4]) != 1:
            raise ParserLayoutError(
                f"{ctx}: VAT rate column has {len(cols[4])} tokens, expected 1"
            )
        vat_rate = _clean_rate(cols[4][0], ctx)

        if len(cols[5]) != 1:
            raise ParserLayoutError(
                f"{ctx}: line total column has {len(cols[5])} tokens, expected 1"
            )
        line_total = _clean_money(cols[5][0], ctx)

        parsed_lines.append(
            {
                "description": description,
                "quantity": quantity,
                "unit": unit,
                "unit_price": unit_price,
                "vat_rate": vat_rate,
                "line_total": line_total,
            }
        )

    distinct_rates = sorted(set(pl["vat_rate"] for pl in parsed_lines))
    if len(distinct_rates) != 1:
        raise ParserLayoutError(
            f"expected exactly one VAT rate across all line items, found {distinct_rates!r}"
        )

    # ---------------------------------------------------------------
    # Totals block + footer (the 6 trailer lines located above).
    # ---------------------------------------------------------------
    m = re.fullmatch(r"Veroton yhteensä\s+(\d[\d ]*,\d{2})\s*€", trailer[0])
    if not m:
        raise ParserLayoutError(f"expected 'Veroton yhteensä <amount> €', got {trailer[0]!r}")
    net_amount = _clean_money(m.group(1), "printed net total")

    m = re.fullmatch(r"ALV\s+(\d+,\d+)\s*%\s+(\d[\d ]*,\d{2})\s*€", trailer[1])
    if not m:
        raise ParserLayoutError(f"expected 'ALV <rate> % <amount> €', got {trailer[1]!r}")
    vat_rate_printed = _clean_rate(m.group(1), "printed VAT rate")
    vat_amount = _clean_money(m.group(2), "printed VAT amount")

    if vat_rate_printed != distinct_rates[0]:
        raise ParserLayoutError(
            f"printed VAT summary rate {vat_rate_printed!r} does not match line-item "
            f"rate {distinct_rates[0]!r}"
        )

    m = re.fullmatch(r"Maksettava\s+(\d[\d ]*,\d{2})\s*€", trailer[2])
    if not m:
        raise ParserLayoutError(f"expected 'Maksettava <amount> €', got {trailer[2]!r}")
    gross_amount = _clean_money(m.group(1), "printed gross total")

    m = re.fullmatch(r"Y-tunnus\s+(\S+)\s+--\s+ALV-tunnus\s+(\S+)", trailer[3])
    if not m:
        raise ParserLayoutError(
            f"expected footer 'Y-tunnus ... -- ALV-tunnus ...', got {trailer[3]!r}"
        )
    footer_business_id, footer_vat_id = m.groups()
    if footer_business_id != _SUPPLIER["business_id"] or footer_vat_id != _SUPPLIER["vat_id"]:
        raise ParserLayoutError(
            f"footer business id/VAT id {footer_business_id!r}/{footer_vat_id!r} do not "
            "match the supplier block"
        )

    m = re.fullmatch(r"Maksuehto:\s*(.+?)\s*--\s*Viitenumero:\s*(\S+)", trailer[4])
    if not m:
        raise ParserLayoutError(
            f"expected footer 'Maksuehto: ... -- Viitenumero: ...', got {trailer[4]!r}"
        )
    payment_terms, reference_bottom = m.groups()
    if reference_bottom != reference_top:
        raise ParserLayoutError(
            f"reference number mismatch: top={reference_top!r} bottom={reference_bottom!r}"
        )

    m = re.fullmatch(r"Pankkiyhteys:\s*(\S+)\s+BIC:\s*(\S+)", trailer[5])
    if not m:
        raise ParserLayoutError(f"expected footer 'Pankkiyhteys: ... BIC: ...', got {trailer[5]!r}")
    iban, bic = m.groups()
    if iban != _BANK["iban"] or bic != _BANK["bic"]:
        raise ParserLayoutError(f"bank details {iban!r}/{bic!r} do not match expected supplier bank block")

    # ---------------------------------------------------------------
    # Arithmetic reconciliation. Any mismatch here means the document is not what
    # this parser was induced to trust -- fail loudly rather than emit a wrong record.
    # ---------------------------------------------------------------
    lines_sum = sum(_to_decimal(pl["line_total"], "line total") for pl in parsed_lines)
    net_dec = _to_decimal(net_amount, "net total")
    if lines_sum != net_dec:
        raise ParserLayoutError(
            f"line items sum to {lines_sum} but printed net total is {net_dec}"
        )

    vat_dec = _to_decimal(vat_amount, "VAT amount")
    gross_dec = _to_decimal(gross_amount, "gross total")
    if net_dec + vat_dec != gross_dec:
        raise ParserLayoutError(
            f"net ({net_dec}) + VAT ({vat_dec}) != printed gross ({gross_dec})"
        )

    expected_vat = (net_dec * Decimal(vat_rate_printed) / Decimal("100")).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )
    if expected_vat != vat_dec:
        raise ParserLayoutError(
            f"net ({net_dec}) x rate ({vat_rate_printed}%) rounds to {expected_vat}, "
            f"which does not match printed VAT amount {vat_dec}"
        )

    # ---------------------------------------------------------------
    # Assemble the record in the accepted-parse schema.
    # ---------------------------------------------------------------
    doc_id = Path(pdf_path).stem

    return {
        "schema_version": "1.0",
        "doc_id": doc_id,
        "supplier": {
            "name": _SUPPLIER["name"],
            "street": _SUPPLIER["street"],
            "postcode": _SUPPLIER["postcode"],
            "city": _SUPPLIER["city"],
            "country": _SUPPLIER["country"],
            "vat_id": _SUPPLIER["vat_id"],
            "business_id": _SUPPLIER["business_id"],
        },
        "buyer": {
            "name": _BUYER["name"],
            "street": _BUYER["street"],
            "postcode": _BUYER["postcode"],
            "city": _BUYER["city"],
            "country": _BUYER["country"],
            "vat_id": _BUYER["vat_id"],
            "business_id": _BUYER["business_id"],
        },
        "invoice": {
            "number": invoice_number,
            "type": "invoice",
            "issue_date": issue_date,
            "supply_date": None,
            "due_date": due_date,
            "payment_terms": payment_terms,
            "currency": "EUR",
            "po_number": None,
            "reference_type": "viitenumero",
            "reference_value": reference_top,
            "original_invoice_number": None,
            "reverse_charge_mention": None,
        },
        "bank": {
            "iban": _BANK["iban"],
            "bic": _BANK["bic"],
            "bankgiro": _BANK["bankgiro"],
        },
        "lines": parsed_lines,
        "vat_summary": [
            {"rate": vat_rate_printed, "base": net_amount, "amount": vat_amount}
        ],
        "totals": {
            "net": net_amount,
            "vat": vat_amount,
            "gross": gross_amount,
        },
    }


if __name__ == "__main__":
    import sys
    import json as _json

    def _deep_equal(a, b, path="root"):
        if isinstance(a, dict) and isinstance(b, dict):
            if a.keys() != b.keys():
                return False, f"{path}: key mismatch {sorted(a.keys())} vs {sorted(b.keys())}"
            for k in a:
                ok, msg = _deep_equal(a[k], b[k], f"{path}.{k}")
                if not ok:
                    return False, msg
            return True, ""
        if isinstance(a, list) and isinstance(b, list):
            if len(a) != len(b):
                return False, f"{path}: length mismatch {len(a)} vs {len(b)}"
            for i, (x, y) in enumerate(zip(a, b)):
                ok, msg = _deep_equal(x, y, f"{path}[{i}]")
                if not ok:
                    return False, msg
            return True, ""
        if a != b:
            return False, f"{path}: {a!r} != {b!r}"
        return True, ""

    args = sys.argv[1:]
    pairs = []
    if len(args) == 1 and args[0].endswith(".json"):
        with open(args[0], "r", encoding="utf-8") as fh:
            manifest = _json.load(fh)
        for entry in manifest:
            if isinstance(entry, dict):
                pairs.append((entry["pdf"], entry["json"]))
            else:
                pairs.append((entry[0], entry[1]))
    else:
        if len(args) % 2 != 0:
            print("usage: parser_s6.py (pdf_path json_path)... | manifest.json", file=sys.stderr)
            sys.exit(2)
        for i in range(0, len(args), 2):
            pairs.append((args[i], args[i + 1]))

    if not pairs:
        print("usage: parser_s6.py (pdf_path json_path)... | manifest.json", file=sys.stderr)
        sys.exit(2)

    failures = 0
    for pdf_path, json_path in pairs:
        with open(json_path, "r", encoding="utf-8") as fh:
            expected = _json.load(fh)
        try:
            actual = parse(pdf_path)
            ok, msg = _deep_equal(expected, actual)
        except ParserLayoutError as exc:
            ok, msg = False, f"ParserLayoutError: {exc}"
        status = "PASS" if ok else "FAIL"
        print(f"{status}  {pdf_path}" + ("" if ok else f"  -- {msg}"))
        if not ok:
            failures += 1

    total = len(pairs)
    print(f"{total - failures}/{total} PASS")
    sys.exit(1 if failures else 0)
