"""Deterministic parser for supplier s1 — Salpausselän Puutavara Oy.

Machine-generated by the overseer agent (model: Claude Sonnet 5, claude-sonnet-5)
on 2026-07-03, per `design/overseer_brief_v1.md` (v1.0).

Induced from 6 accepted LLM parses of this supplier's invoices (the accepted
parse JSON for each doc was treated as ground truth for the correct record;
the layout was read from the PDF text layer and word-coordinate dump of each):

    2025-01_s1_01, 2025-01_s1_02, 2025-01_s1_03,
    2025-02_s1_01, 2025-02_s1_02, 2025-02_s1_03

No other files (no answer keys, no generator/template code, no other supplier's
documents) were consulted while writing this module.

Layout landmarks this parser relies on (see report for detail):
  - Fixed Finnish labels in a fixed order: "Laskun numero", "Laskun päivä",
    "Eräpäivä", "Y-tunnus:", "Viitenumero", "Tilausnumero", "OSTAJA",
    a second "Y-tunnus:" for the buyer, the item-table header line
    "NIMIKE MÄÄRÄ YKSIKKÖ A-HINTA ALV % YHTEENSÄ", "Veroton yhteensä",
    "ALV <rate> %", "Maksettava", "Y-tunnus ... Pankkiyhteys:",
    "ALV-tunnus ... BIC:", "Maksuehto: ... Viitenumero:".
  - pdfplumber's default `page.extract_text()` merges the two label/value
    columns of the header block onto shared lines (by text row position);
    this parser reads those merged lines with regexes anchored on the labels.
  - Item rows: "<description> <qty> <unit> <unit_price> <vat_rate> <line_total>",
    unit in {kpl, m2, jm}, all monetary values in Finnish comma-decimal
    notation with an optional space thousands separator (e.g. "1 107,23").
  - Multi-page invoices (seen once, 2025-02_s1_03) repeat the item-table
    header after a "<invoice number> (jatkuu)" line at the top of the
    continuation page, before the remaining item rows and the totals block.

This parser fails loudly (raises ParserLayoutError) rather than guess whenever
a label, ordering, value shape, or arithmetic reconciliation is not exactly
what was observed in the induction set above.
"""

import re
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

import pdfplumber


class ParserLayoutError(Exception):
    """Raised when this document's layout, labels, or arithmetic deviate from
    the Salpausselän Puutavara Oy template induced from the 6 training docs.

    Raising here is a SUCCESS mode of the pipeline: the router falls back to
    the LLM path. Returning a record that silently guesses at an unexpected
    value is the failure mode this parser is designed never to produce.
    """


# ---------------------------------------------------------------------------
# Finnish number / date helpers
# ---------------------------------------------------------------------------

# Finnish money: comma decimal separator, optional space-grouped thousands,
# e.g. "556,24" or "1 818,22". Exactly two decimal digits observed throughout.
_FI_MONEY_FRAGMENT = r"\d{1,3}(?: \d{3})*,\d{2}"
_FI_MONEY_RE = re.compile(r"^" + _FI_MONEY_FRAGMENT + r"$")
_FI_DATE_RE = re.compile(r"^(\d{2})\.(\d{2})\.(\d{4})$")
_FI_VAT_RE = re.compile(r"^\d{1,2}(?:,\d+)?$")

_CANONICAL_VAT_RATES = {
    Decimal("25.5"): "25.5",
    Decimal("14.0"): "14.0",
    Decimal("10.0"): "10.0",
    Decimal("0.0"): "0.0",
}


def _fi_date_to_iso(s, where):
    m = _FI_DATE_RE.match(s)
    if not m:
        raise ParserLayoutError(f"expected a DD.MM.YYYY date in {where}, got {s!r}")
    d, mo, y = m.groups()
    return f"{y}-{mo}-{d}"


def _fi_money_to_str(s, where):
    if not _FI_MONEY_RE.match(s):
        raise ParserLayoutError(f"expected a Finnish money amount in {where}, got {s!r}")
    return s.replace(" ", "").replace(",", ".")


def _fi_vat_rate_to_canonical(s, where):
    if not _FI_VAT_RE.match(s):
        raise ParserLayoutError(f"expected a VAT rate in {where}, got {s!r}")
    try:
        value = Decimal(s.replace(",", "."))
    except Exception as exc:  # pragma: no cover - guarded by regex above
        raise ParserLayoutError(f"could not parse VAT rate in {where}: {s!r}") from exc
    if value not in _CANONICAL_VAT_RATES:
        raise ParserLayoutError(
            f"unexpected VAT rate {s!r} in {where}; only 25.5/14.0/10.0/0.0 were observed"
        )
    return _CANONICAL_VAT_RATES[value]


# ---------------------------------------------------------------------------
# Structural regexes for the fixed label layout
# ---------------------------------------------------------------------------

_HEADER_TABLE_LINE = "NIMIKE MÄÄRÄ YKSIKKÖ A-HINTA ALV % YHTEENSÄ"

_RE_INVOICE_NUMBER = re.compile(r"^Laskun numero (.+)$")
_RE_STREET_ISSUE = re.compile(r"^(.+) Laskun päivä (\d{2}\.\d{2}\.\d{4})$")
_RE_POSTCODE_CITY_DUE = re.compile(r"^(\d{5}) (.+) Eräpäivä (\d{2}\.\d{2}\.\d{4})$")
_RE_BUSINESSID_REF = re.compile(r"^Y-tunnus: (\S+) Viitenumero (\S+)$")
_RE_PO_NUMBER = re.compile(r"^Tilausnumero (\S+)$")
_RE_BUYER_POSTCODE_CITY = re.compile(r"^(\d{5}) (.+)$")
_RE_BUYER_BUSINESSID = re.compile(r"^Y-tunnus: (\S+)$")

_RE_ITEM = re.compile(
    r"^(?P<desc>.+?) (?P<qty>\d+) (?P<unit>kpl|m2|jm) "
    r"(?P<price>" + _FI_MONEY_FRAGMENT + r") "
    r"(?P<vat>\d{1,2}(?:,\d+)?) "
    r"(?P<total>" + _FI_MONEY_FRAGMENT + r")$"
)
_RE_VEROTON = re.compile(r"^Veroton yhteensä (" + _FI_MONEY_FRAGMENT + r") €$")
_RE_ALV = re.compile(r"^ALV (\d{1,2}(?:,\d+)?) % (" + _FI_MONEY_FRAGMENT + r") €$")
_RE_MAKSETTAVA = re.compile(r"^Maksettava (" + _FI_MONEY_FRAGMENT + r") €$")
_RE_BANK_LINE = re.compile(r"^Y-tunnus (\S+) Pankkiyhteys: (\S+)$")
_RE_VATID_BIC_LINE = re.compile(r"^ALV-tunnus (\S+) BIC: (\S+)$")
_RE_TERMS_REF_LINE = re.compile(r"^Maksuehto: (.+) Viitenumero: (\S+)$")
_RE_CONTINUATION = re.compile(r"^(.+) \(jatkuu\)$")


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def parse(pdf_path: str) -> dict:
    """Parse one Salpausselän Puutavara Oy invoice PDF into the accepted schema.

    Raises ParserLayoutError the moment any expected label, ordering, value
    shape, or arithmetic reconciliation is not exactly as observed in the
    6-document induction set.
    """
    with pdfplumber.open(pdf_path) as pdf:
        if len(pdf.pages) == 0:
            raise ParserLayoutError("PDF has no pages")
        pages_lines = []
        for page_index, page in enumerate(pdf.pages):
            text = page.extract_text()
            if not text:
                raise ParserLayoutError(f"page {page_index} produced no extractable text")
            pages_lines.append([ln.strip() for ln in text.splitlines()])

    page_num = 0
    cur_lines = pages_lines[0]
    idx = 0

    def next_line(where):
        nonlocal idx
        if idx >= len(cur_lines):
            raise ParserLayoutError(f"ran out of lines on page {page_num} while expecting {where}")
        line = cur_lines[idx]
        idx += 1
        return line

    # --- Supplier header block (page 0 only) ---
    supplier_name = next_line("supplier name (line 1)")
    if not supplier_name:
        raise ParserLayoutError("expected a non-blank supplier name on line 1")

    line = next_line("'Laskun numero <...>'")
    m = _RE_INVOICE_NUMBER.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Laskun numero <...>', got {line!r}")
    invoice_number = m.group(1)

    line = next_line("'<street> Laskun päivä <date>'")
    m = _RE_STREET_ISSUE.match(line)
    if not m:
        raise ParserLayoutError(f"expected '<street> Laskun päivä <date>', got {line!r}")
    supplier_street = m.group(1)
    issue_date = _fi_date_to_iso(m.group(2), "'Laskun päivä'")

    line = next_line("'<postcode> <city> Eräpäivä <date>'")
    m = _RE_POSTCODE_CITY_DUE.match(line)
    if not m:
        raise ParserLayoutError(f"expected '<postcode> <city> Eräpäivä <date>', got {line!r}")
    supplier_postcode, supplier_city = m.group(1), m.group(2)
    due_date = _fi_date_to_iso(m.group(3), "'Eräpäivä'")

    line = next_line("'Y-tunnus: <id> Viitenumero <ref>'")
    m = _RE_BUSINESSID_REF.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Y-tunnus: <id> Viitenumero <ref>', got {line!r}")
    supplier_business_id, reference_value_header = m.group(1), m.group(2)

    line = next_line("'Tilausnumero <po>'")
    m = _RE_PO_NUMBER.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Tilausnumero <po>', got {line!r}")
    po_number = m.group(1)

    line = next_line("'OSTAJA'")
    if line != "OSTAJA":
        raise ParserLayoutError(f"expected literal 'OSTAJA', got {line!r}")

    buyer_name = next_line("buyer name")
    if not buyer_name:
        raise ParserLayoutError("expected a non-blank buyer name after 'OSTAJA'")

    buyer_street = next_line("buyer street")
    if not buyer_street:
        raise ParserLayoutError("expected a non-blank buyer street")

    line = next_line("buyer '<postcode> <city>'")
    m = _RE_BUYER_POSTCODE_CITY.match(line)
    if not m:
        raise ParserLayoutError(f"expected buyer '<postcode> <city>', got {line!r}")
    buyer_postcode, buyer_city = m.group(1), m.group(2)

    line = next_line("buyer 'Y-tunnus: <id>'")
    m = _RE_BUYER_BUSINESSID.match(line)
    if not m:
        raise ParserLayoutError(f"expected buyer 'Y-tunnus: <id>', got {line!r}")
    buyer_business_id = m.group(1)

    line = next_line("item table header")
    if line != _HEADER_TABLE_LINE:
        raise ParserLayoutError(f"expected item table header {_HEADER_TABLE_LINE!r}, got {line!r}")

    # --- Item rows, possibly spanning a continuation page ---
    raw_items = []
    veroton_amount = None

    while True:
        if idx >= len(cur_lines):
            page_num += 1
            if page_num >= len(pages_lines):
                raise ParserLayoutError(
                    "ran out of pages while reading line items; no totals block was found"
                )
            cur_lines = pages_lines[page_num]
            idx = 0
            if not cur_lines:
                raise ParserLayoutError(f"page {page_num} is empty; expected a continuation header")
            cont_line = next_line("continuation marker '<invoice number> (jatkuu)'")
            m = _RE_CONTINUATION.match(cont_line)
            if not m:
                raise ParserLayoutError(
                    f"expected '<invoice number> (jatkuu)' at top of page {page_num}, got {cont_line!r}"
                )
            if m.group(1) != invoice_number:
                raise ParserLayoutError(
                    f"continuation header invoice number {m.group(1)!r} does not match "
                    f"the header invoice number {invoice_number!r}"
                )
            header_line = next_line("repeated item table header")
            if header_line != _HEADER_TABLE_LINE:
                raise ParserLayoutError(
                    f"expected repeated item table header on page {page_num}, got {header_line!r}"
                )
            continue

        line = cur_lines[idx]
        m_totals = _RE_VEROTON.match(line)
        if m_totals:
            idx += 1
            veroton_amount = m_totals.group(1)
            break

        m_item = _RE_ITEM.match(line)
        if not m_item:
            raise ParserLayoutError(
                f"line {idx} on page {page_num} matched neither an item row nor "
                f"'Veroton yhteensä ...': {line!r}"
            )
        raw_items.append(m_item.groupdict())
        idx += 1

    if not raw_items:
        raise ParserLayoutError("no item rows were found before the totals block")

    # --- VAT summary lines (one or more, all before 'Maksettava') ---
    raw_vat_lines = []
    while idx < len(cur_lines):
        m_alv = _RE_ALV.match(cur_lines[idx])
        if not m_alv:
            break
        raw_vat_lines.append(m_alv)
        idx += 1
    if not raw_vat_lines:
        raise ParserLayoutError("expected at least one 'ALV <rate> % <amount> €' line after Veroton yhteensä")

    line = next_line("'Maksettava <amount> €'")
    m = _RE_MAKSETTAVA.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Maksettava <amount> €', got {line!r}")
    gross_amount = m.group(1)

    line = next_line("'Y-tunnus <id> Pankkiyhteys: <iban>'")
    m = _RE_BANK_LINE.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Y-tunnus <id> Pankkiyhteys: <iban>', got {line!r}")
    bottom_business_id, iban = m.group(1), m.group(2)

    line = next_line("'ALV-tunnus <vat id> BIC: <bic>'")
    m = _RE_VATID_BIC_LINE.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'ALV-tunnus <vat id> BIC: <bic>', got {line!r}")
    vat_id, bic = m.group(1), m.group(2)

    line = next_line("'Maksuehto: <terms> Viitenumero: <ref>'")
    m = _RE_TERMS_REF_LINE.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Maksuehto: <terms> Viitenumero: <ref>', got {line!r}")
    payment_terms, reference_value_footer = m.group(1), m.group(2)

    if idx != len(cur_lines):
        raise ParserLayoutError(f"unexpected trailing content on page {page_num}: {cur_lines[idx:]!r}")
    if page_num != len(pages_lines) - 1:
        raise ParserLayoutError(
            f"unexpected extra pages after the totals block (document has "
            f"{len(pages_lines)} pages, totals ended on page {page_num})"
        )

    # --- Cross-checks between the two places every value is repeated ---
    if reference_value_header != reference_value_footer:
        raise ParserLayoutError(
            f"reference value mismatch: header {reference_value_header!r} vs "
            f"footer {reference_value_footer!r}"
        )
    if bottom_business_id != supplier_business_id:
        raise ParserLayoutError(
            f"supplier business id mismatch: header {supplier_business_id!r} vs "
            f"footer {bottom_business_id!r}"
        )
    if not iban.startswith("FI"):
        raise ParserLayoutError(f"expected a Finnish IBAN (starting 'FI'), got {iban!r}")
    if not vat_id.startswith("FI"):
        raise ParserLayoutError(f"expected a Finnish VAT id (starting 'FI'), got {vat_id!r}")
    expected_vat_id = "FI" + supplier_business_id.replace("-", "")
    if vat_id != expected_vat_id:
        raise ParserLayoutError(
            f"VAT id {vat_id!r} does not match supplier business id {supplier_business_id!r} "
            f"(expected {expected_vat_id!r})"
        )

    # --- Canonicalise line items and reconcile per-line arithmetic ---
    lines = []
    vat_bases = {}
    for raw in raw_items:
        desc = raw["desc"]
        qty_str = raw["qty"]
        unit = raw["unit"]
        price_str = _fi_money_to_str(raw["price"], f"unit price of line {desc!r}")
        vat_canonical = _fi_vat_rate_to_canonical(raw["vat"], f"VAT rate of line {desc!r}")
        total_str = _fi_money_to_str(raw["total"], f"line total of line {desc!r}")

        qty_dec = Decimal(qty_str)
        price_dec = Decimal(price_str)
        total_dec = Decimal(total_str)
        expected_total = (qty_dec * price_dec).quantize(Decimal("0.01"))
        if expected_total != total_dec:
            raise ParserLayoutError(
                f"line {desc!r} does not reconcile: {qty_str} x {price_str} = "
                f"{expected_total} but the printed line total is {total_dec}"
            )

        lines.append(
            {
                "description": desc,
                "quantity": str(int(qty_dec)),
                "unit": unit,
                "unit_price": price_str,
                "vat_rate": vat_canonical,
                "line_total": total_str,
            }
        )
        vat_bases[vat_canonical] = vat_bases.get(vat_canonical, Decimal("0")) + total_dec

    # --- Reconcile net (Veroton yhteensä) against the sum of line totals ---
    net_str = _fi_money_to_str(veroton_amount, "'Veroton yhteensä' total")
    net_dec = Decimal(net_str)
    sum_lines_dec = sum(vat_bases.values(), Decimal("0"))
    if sum_lines_dec != net_dec:
        raise ParserLayoutError(
            f"sum of line totals {sum_lines_dec} does not match printed "
            f"'Veroton yhteensä' {net_dec}"
        )

    # --- Reconcile the VAT summary block against the line items ---
    vat_summary = []
    seen_rates = set()
    vat_total_dec = Decimal("0")
    for m_alv in raw_vat_lines:
        rate_canonical = _fi_vat_rate_to_canonical(m_alv.group(1), "'ALV' summary rate")
        amount_str = _fi_money_to_str(m_alv.group(2), "'ALV' summary amount")
        amount_dec = Decimal(amount_str)
        if rate_canonical in seen_rates:
            raise ParserLayoutError(f"VAT rate {rate_canonical} appears more than once in the summary")
        if rate_canonical not in vat_bases:
            raise ParserLayoutError(
                f"'ALV' summary lists rate {rate_canonical} but no line item uses that rate"
            )
        base_dec = vat_bases[rate_canonical]
        expected_amount = (base_dec * Decimal(rate_canonical) / Decimal("100")).quantize(
            Decimal("0.01"), rounding=ROUND_HALF_UP
        )
        if expected_amount != amount_dec:
            raise ParserLayoutError(
                f"VAT amount for rate {rate_canonical} does not reconcile: "
                f"{base_dec} x {rate_canonical}% = {expected_amount} but printed {amount_dec}"
            )
        vat_summary.append({"rate": rate_canonical, "base": str(base_dec), "amount": amount_str})
        seen_rates.add(rate_canonical)
        vat_total_dec += amount_dec

    if seen_rates != set(vat_bases.keys()):
        raise ParserLayoutError(
            f"VAT summary rates {sorted(seen_rates)} do not match the rates present in the "
            f"line items {sorted(vat_bases.keys())}"
        )

    # --- Reconcile gross (Maksettava) against net + vat ---
    gross_str = _fi_money_to_str(gross_amount, "'Maksettava' total")
    gross_dec = Decimal(gross_str)
    if net_dec + vat_total_dec != gross_dec:
        raise ParserLayoutError(
            f"net + vat does not reconcile with the printed total: {net_dec} + "
            f"{vat_total_dec} = {net_dec + vat_total_dec} but 'Maksettava' printed {gross_dec}"
        )

    return {
        "schema_version": "1.0",
        "doc_id": Path(pdf_path).stem,
        "supplier": {
            "name": supplier_name,
            "street": supplier_street,
            "postcode": supplier_postcode,
            "city": supplier_city,
            "country": "FI",
            "vat_id": vat_id,
            "business_id": supplier_business_id,
        },
        "buyer": {
            "name": buyer_name,
            "street": buyer_street,
            "postcode": buyer_postcode,
            "city": buyer_city,
            "country": "FI",
            "vat_id": None,
            "business_id": buyer_business_id,
        },
        "invoice": {
            "number": invoice_number,
            "type": "invoice",
            "issue_date": issue_date,
            "supply_date": None,
            "due_date": due_date,
            "payment_terms": payment_terms,
            "currency": "EUR",
            "po_number": po_number,
            "reference_type": "viitenumero",
            "reference_value": reference_value_header,
            "original_invoice_number": None,
            "reverse_charge_mention": None,
        },
        "bank": {
            "iban": iban,
            "bic": bic,
            "bankgiro": None,
        },
        "lines": lines,
        "vat_summary": vat_summary,
        "totals": {
            "net": net_str,
            "vat": str(vat_total_dec),
            "gross": gross_str,
        },
    }


# ---------------------------------------------------------------------------
# Mandatory self-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import json
    import sys

    def _load_pairs(argv):
        if len(argv) == 1 and argv[0].lower().endswith(".json"):
            with open(argv[0], "r", encoding="utf-8") as f:
                manifest = json.load(f)
            pairs = []
            for entry in manifest:
                if isinstance(entry, dict):
                    pairs.append((entry["pdf"], entry["json"]))
                else:
                    pairs.append((entry[0], entry[1]))
            return pairs
        if len(argv) % 2 != 0:
            print(
                "usage: parser_s1.py (<pdf_path> <accepted_parse_json>)... | <manifest.json>",
                file=sys.stderr,
            )
            sys.exit(2)
        return [(argv[i], argv[i + 1]) for i in range(0, len(argv), 2)]

    pairs = _load_pairs(sys.argv[1:])
    if not pairs:
        print(
            "usage: parser_s1.py (<pdf_path> <accepted_parse_json>)... | <manifest.json>",
            file=sys.stderr,
        )
        sys.exit(2)

    failures = 0
    for pdf_path, parse_json_path in pairs:
        doc_id = Path(pdf_path).stem
        try:
            got = parse(pdf_path)
        except ParserLayoutError as exc:
            failures += 1
            print(f"FAIL {doc_id}: ParserLayoutError: {exc}")
            continue

        with open(parse_json_path, "r", encoding="utf-8") as f:
            expected = json.load(f)

        if got == expected:
            print(f"PASS {doc_id}")
        else:
            failures += 1
            print(f"FAIL {doc_id}: parsed record does not match the accepted parse")
            for key in sorted(set(expected) | set(got)):
                if got.get(key) != expected.get(key):
                    print(f"  field {key!r} differs:")
                    print(f"    got:      {got.get(key)!r}")
                    print(f"    expected: {expected.get(key)!r}")

    total = len(pairs)
    print(f"\n{total - failures}/{total} PASS")
    sys.exit(1 if failures else 0)
