"""
Deterministic parser for supplier s3 -- Falkenrath Beschlaege GmbH.

Machine-generated by the overseer agent (model: Claude Sonnet 5) on 2026-07-03.
Induced from 6 accepted LLM parses and their underlying PDFs / pdfplumber text
and word-coordinate dumps (no other files were consulted). Induction doc_ids:
  2025-01_s3_01, 2025-01_s3_02, 2025-02_s3_01,
  2025-02_s3_02, 2025-03_s3_01, 2025-03_s3_02

LAYOUT INDUCED (single-page German "Rechnung", read via pdfplumber
page.extract_text().splitlines() -- consistent across all 6 documents, only
the number of line-item rows varies):

  line  1      : supplier name (verbatim)
  line  2      : "Rechnung-Nr. <invoice number>"
  line  3      : "<supplier street> Rechnungsdatum <DD.MM.YYYY>"
  line  4      : "<plz> <city>, <country name> Leistungsdatum <DD.MM.YYYY>"
  line  5      : "HRB <digits>, Amtsgericht <court city>"   (court city is
                  context only -- business_id is "HRB <digits>")
  line  6      : "Faelligkeitsdatum <DD.MM.YYYY>"
  line  7      : "USt-IdNr. <supplier vat id>"               (no colon)
  line  8      : "Bestellnummer <po number>"
  line  9      : "KAEUFER"
  line 10      : buyer name (verbatim)
  line 11      : buyer street (verbatim)
  line 12      : "<plz> <city>, <country name>"
  line 13      : "Handelsregister: <buyer business id>"
  line 14      : "USt-IdNr.: <buyer vat id>"                  (with colon)
  line 15      : "BEZEICHNUNG MENGE EINHEIT EINZELPREIS UST % GESAMT"
  line 16..N   : one row per line item:
                 "<description tokens...> <qty> ST <unit price> <vat%> <line total>"
                 (unit is always literally "ST" in the induction set; this is
                 used as the anchor token to split description from quantity)
  then         : "Netto <amount> <currency symbol>"
                 "Umsatzsteuer <rate digits> % <amount> <currency symbol>"
                 "Brutto <amount> <currency symbol>"
                 "Steuerfreie innergemeinschaftliche Lieferung"
                 "Bankverbindung"
                 "IBAN: <iban> BIC: <bic>"
                 "Zahlungsbedingungen: <payment terms>"
                 "Verwendungszweck: <invoice number restated>"

Notes on schema mapping, taken from the accepted parses:
  - Only VAT rate observed for this supplier is 0% (intra-EU reverse charge /
    exempt supply -- "Steuerfreie innergemeinschaftliche Lieferung" is always
    present). Rate token "0" maps to canonical vat_rate "0.0".
  - "Verwendungszweck:" merely restates the invoice number; it is not a
    structured payment reference, so reference_type/reference_value are
    always null. This is verified (the value must equal the invoice number),
    not just assumed.
  - business_id is "HRB <digits>" -- "Amtsgericht <city>" is context, dropped.
  - doc_id is derived from the pdf filename stem (not printed in the document).
  - Dates are DD.MM.YYYY -> ISO. Money is German-formatted (1.234,56) ->
    canonical "1234.56". Quantities are printed as plain digit strings with no
    thousands separator, even at 4 digits (e.g. "1227").

Fails loudly (ParserLayoutError) on any label, header, structure, or
arithmetic mismatch with what was induced above -- see the hard-boundaries
brief this parser was written against. No fallback/guessing behaviour.
"""

from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
import re

import pdfplumber


class ParserLayoutError(Exception):
    """Raised when the PDF does not match the layout this parser was induced from."""


# ---------------------------------------------------------------------------
# Constants describing the induced layout
# ---------------------------------------------------------------------------

_HEADER_ROW = "BEZEICHNUNG MENGE EINHEIT EINZELPREIS UST % GESAMT"
_ITEM_UNIT = "ST"
_REVERSE_CHARGE_TEXT = "Steuerfreie innergemeinschaftliche Lieferung"
_KAEUFER_LABEL = "KÄUFER"
_BANK_LABEL = "Bankverbindung"

_COUNTRY_MAP = {"Deutschland": "DE", "Finnland": "FI"}
_CURRENCY_MAP = {"€": "EUR"}
_VAT_RATE_MAP = {"0": "0.0"}

_DE_AMOUNT_RE = re.compile(r"^\d{1,3}(?:\.\d{3})*,\d{2}$")
_INT_RE = re.compile(r"^\d+$")
_DDMMYYYY_RE = re.compile(r"^(\d{2})\.(\d{2})\.(\d{4})$")

_RECHNUNG_NR_RE = re.compile(r"^Rechnung-Nr\.\s+(\S+)$")
_STREET_DATE_RE = re.compile(r"^(.+?)\s+Rechnungsdatum\s+(\d{2}\.\d{2}\.\d{4})$")
_CITY_DATE_RE = re.compile(r"^(\d{5})\s+(.+?),\s+(\S+)\s+Leistungsdatum\s+(\d{2}\.\d{2}\.\d{4})$")
_HRB_RE = re.compile(r"^HRB\s+(\d+),\s+Amtsgericht\s+\S.*$")
_FAELLIG_RE = re.compile(r"^Fälligkeitsdatum\s+(\d{2}\.\d{2}\.\d{4})$")
_SUPPLIER_VAT_RE = re.compile(r"^USt-IdNr\.\s+(\S+)$")
_BESTELLNR_RE = re.compile(r"^Bestellnummer\s+(\S+)$")
_BUYER_CITY_RE = re.compile(r"^(\d{5})\s+(.+?),\s+(\S+)$")
_HANDELSREGISTER_RE = re.compile(r"^Handelsregister:\s+(\S+)$")
_BUYER_VAT_RE = re.compile(r"^USt-IdNr\.:\s+(\S+)$")
_NETTO_RE = re.compile(r"^Netto\s+(\d{1,3}(?:\.\d{3})*,\d{2})\s+(\S+)$")
_UST_RE = re.compile(r"^Umsatzsteuer\s+(\d+)\s+%\s+(\d{1,3}(?:\.\d{3})*,\d{2})\s+(\S+)$")
_BRUTTO_RE = re.compile(r"^Brutto\s+(\d{1,3}(?:\.\d{3})*,\d{2})\s+(\S+)$")
_IBAN_BIC_RE = re.compile(r"^IBAN:\s+(\S+)\s+BIC:\s+(\S+)$")
_ZAHLUNGSBED_RE = re.compile(r"^Zahlungsbedingungen:\s+(.+)$")
_VERWENDUNGSZWECK_RE = re.compile(r"^Verwendungszweck:\s+(\S+)$")


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def _match(regex, line, label):
    m = regex.match(line)
    if not m:
        raise ParserLayoutError(f"expected {label}, got: {line!r}")
    return m


def _amount_to_canonical(token, context):
    if not _DE_AMOUNT_RE.match(token):
        raise ParserLayoutError(f"{context}: {token!r} is not a recognised German decimal amount")
    return token.replace(".", "").replace(",", ".")


def _date_to_iso(token, context):
    m = _DDMMYYYY_RE.match(token)
    if not m:
        raise ParserLayoutError(f"{context}: {token!r} is not a DD.MM.YYYY date")
    day, month, year = (int(x) for x in m.groups())
    from datetime import date as _date

    try:
        d = _date(year, month, day)
    except ValueError as exc:
        raise ParserLayoutError(f"{context}: {token!r} is not a valid calendar date ({exc})")
    return d.isoformat()


def _country_to_iso(name, context):
    try:
        return _COUNTRY_MAP[name]
    except KeyError:
        raise ParserLayoutError(f"{context}: unrecognised country name {name!r}")


def _currency_to_iso(symbol, context):
    try:
        return _CURRENCY_MAP[symbol]
    except KeyError:
        raise ParserLayoutError(f"{context}: unrecognised currency symbol {symbol!r}")


def _rate_token_to_canonical(token, context):
    try:
        return _VAT_RATE_MAP[token]
    except KeyError:
        raise ParserLayoutError(f"{context}: unrecognised VAT rate token {token!r} for supplier s3")


def _parse_item_line(raw, line_no):
    tokens = raw.split()
    unit_positions = [i for i, t in enumerate(tokens) if t == _ITEM_UNIT]
    if len(unit_positions) != 1:
        raise ParserLayoutError(
            f"line {line_no}: expected exactly one {_ITEM_UNIT!r} unit token, "
            f"found {len(unit_positions)} in {raw!r}"
        )
    unit_idx = unit_positions[0]
    if unit_idx < 1:
        raise ParserLayoutError(f"line {line_no}: no quantity token before unit in {raw!r}")
    if len(tokens) != unit_idx + 4:
        raise ParserLayoutError(
            f"line {line_no}: expected <description...> <qty> ST <price> <vat%> <total>, "
            f"got {raw!r}"
        )

    description = " ".join(tokens[: unit_idx - 1])
    if not description:
        raise ParserLayoutError(f"line {line_no}: empty description in {raw!r}")

    quantity_tok = tokens[unit_idx - 1]
    if not _INT_RE.match(quantity_tok):
        raise ParserLayoutError(f"line {line_no}: quantity {quantity_tok!r} is not a plain integer")

    price_tok = tokens[unit_idx + 1]
    vat_tok = tokens[unit_idx + 2]
    total_tok = tokens[unit_idx + 3]

    unit_price = _amount_to_canonical(price_tok, f"line {line_no} unit price")
    vat_rate = _rate_token_to_canonical(vat_tok, f"line {line_no} VAT rate")
    line_total = _amount_to_canonical(total_tok, f"line {line_no} line total")

    expected_total = (Decimal(quantity_tok) * Decimal(unit_price)).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )
    if expected_total != Decimal(line_total):
        raise ParserLayoutError(
            f"line {line_no}: {quantity_tok} x {unit_price} = {expected_total}, "
            f"printed line total is {line_total}"
        )

    return {
        "description": description,
        "quantity": quantity_tok,
        "unit": _ITEM_UNIT,
        "unit_price": unit_price,
        "vat_rate": vat_rate,
        "line_total": line_total,
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def parse(pdf_path: str) -> dict:
    with pdfplumber.open(pdf_path) as pdf:
        if len(pdf.pages) != 1:
            raise ParserLayoutError(
                f"expected a single-page invoice (induction set was all single-page), "
                f"found {len(pdf.pages)} pages"
            )
        text = pdf.pages[0].extract_text()

    if not text:
        raise ParserLayoutError("no extractable text layer on page 1")

    lines = text.splitlines()

    def line_at(i, label):
        if i >= len(lines):
            raise ParserLayoutError(f"document ended before expected {label}")
        return lines[i]

    idx = 0

    supplier_name = line_at(idx, "supplier name line").strip()
    if not supplier_name:
        raise ParserLayoutError("empty supplier name line")
    idx += 1

    m = _match(_RECHNUNG_NR_RE, line_at(idx, "'Rechnung-Nr.' line"), "'Rechnung-Nr.' line")
    invoice_number = m.group(1)
    idx += 1

    m = _match(
        _STREET_DATE_RE,
        line_at(idx, "supplier street / Rechnungsdatum line"),
        "supplier street / Rechnungsdatum line",
    )
    supplier_street = m.group(1)
    issue_date = _date_to_iso(m.group(2), "Rechnungsdatum")
    idx += 1

    m = _match(
        _CITY_DATE_RE,
        line_at(idx, "supplier postcode/city/country / Leistungsdatum line"),
        "supplier postcode/city/country / Leistungsdatum line",
    )
    supplier_postcode, supplier_city, supplier_country_name = m.group(1), m.group(2), m.group(3)
    supply_date = _date_to_iso(m.group(4), "Leistungsdatum")
    supplier_country = _country_to_iso(supplier_country_name, "supplier country")
    idx += 1

    m = _match(
        _HRB_RE,
        line_at(idx, "'HRB ..., Amtsgericht ...' line"),
        "'HRB ..., Amtsgericht ...' line",
    )
    supplier_business_id = f"HRB {m.group(1)}"
    idx += 1

    m = _match(
        _FAELLIG_RE,
        line_at(idx, "'Fälligkeitsdatum' line"),
        "'Fälligkeitsdatum' line",
    )
    due_date = _date_to_iso(m.group(1), "Fälligkeitsdatum")
    idx += 1

    m = _match(
        _SUPPLIER_VAT_RE,
        line_at(idx, "supplier 'USt-IdNr.' line"),
        "supplier 'USt-IdNr.' line",
    )
    supplier_vat_id = m.group(1)
    idx += 1

    m = _match(_BESTELLNR_RE, line_at(idx, "'Bestellnummer' line"), "'Bestellnummer' line")
    po_number = m.group(1)
    idx += 1

    kaeufer_line = line_at(idx, "'KÄUFER' line").strip()
    if kaeufer_line != _KAEUFER_LABEL:
        raise ParserLayoutError(f"expected {_KAEUFER_LABEL!r} line, got: {kaeufer_line!r}")
    idx += 1

    buyer_name = line_at(idx, "buyer name line").strip()
    if not buyer_name:
        raise ParserLayoutError("empty buyer name line")
    idx += 1

    buyer_street = line_at(idx, "buyer street line").strip()
    if not buyer_street:
        raise ParserLayoutError("empty buyer street line")
    idx += 1

    m = _match(
        _BUYER_CITY_RE,
        line_at(idx, "buyer postcode/city/country line"),
        "buyer postcode/city/country line",
    )
    buyer_postcode, buyer_city, buyer_country_name = m.group(1), m.group(2), m.group(3)
    buyer_country = _country_to_iso(buyer_country_name, "buyer country")
    idx += 1

    m = _match(
        _HANDELSREGISTER_RE,
        line_at(idx, "'Handelsregister:' line"),
        "'Handelsregister:' line",
    )
    buyer_business_id = m.group(1)
    idx += 1

    m = _match(
        _BUYER_VAT_RE,
        line_at(idx, "buyer 'USt-IdNr.:' line"),
        "buyer 'USt-IdNr.:' line",
    )
    buyer_vat_id = m.group(1)
    idx += 1

    header_row = line_at(idx, "line-item table header").strip()
    if header_row != _HEADER_ROW:
        raise ParserLayoutError(f"expected table header {_HEADER_ROW!r}, got: {header_row!r}")
    idx += 1

    item_lines = []
    while True:
        raw = line_at(idx, "line item or 'Netto' totals line")
        if raw.startswith("Netto"):
            break
        item_lines.append(_parse_item_line(raw, idx + 1))
        idx += 1

    if not item_lines:
        raise ParserLayoutError("no line items found before 'Netto' line")

    m = _match(_NETTO_RE, line_at(idx, "'Netto' totals line"), "'Netto' totals line")
    net_canonical = _amount_to_canonical(m.group(1), "Netto amount")
    currency = _currency_to_iso(m.group(2), "Netto line currency symbol")
    idx += 1

    m = _match(_UST_RE, line_at(idx, "'Umsatzsteuer' totals line"), "'Umsatzsteuer' totals line")
    vat_rate_canonical = _rate_token_to_canonical(m.group(1), "Umsatzsteuer rate")
    vat_amount_canonical = _amount_to_canonical(m.group(2), "Umsatzsteuer amount")
    ust_currency = _currency_to_iso(m.group(3), "Umsatzsteuer line currency symbol")
    if ust_currency != currency:
        raise ParserLayoutError(
            f"Umsatzsteuer line currency {ust_currency!r} does not match Netto line currency {currency!r}"
        )
    idx += 1

    m = _match(_BRUTTO_RE, line_at(idx, "'Brutto' totals line"), "'Brutto' totals line")
    gross_canonical = _amount_to_canonical(m.group(1), "Brutto amount")
    brutto_currency = _currency_to_iso(m.group(2), "Brutto line currency symbol")
    if brutto_currency != currency:
        raise ParserLayoutError(
            f"Brutto line currency {brutto_currency!r} does not match Netto line currency {currency!r}"
        )
    idx += 1

    reverse_charge_line = line_at(idx, "reverse-charge mention line").strip()
    if reverse_charge_line != _REVERSE_CHARGE_TEXT:
        raise ParserLayoutError(
            f"expected reverse-charge mention {_REVERSE_CHARGE_TEXT!r}, got: {reverse_charge_line!r}"
        )
    idx += 1

    bank_label = line_at(idx, "'Bankverbindung' line").strip()
    if bank_label != _BANK_LABEL:
        raise ParserLayoutError(f"expected {_BANK_LABEL!r} line, got: {bank_label!r}")
    idx += 1

    m = _match(
        _IBAN_BIC_RE,
        line_at(idx, "'IBAN: ... BIC: ...' line"),
        "'IBAN: ... BIC: ...' line",
    )
    iban, bic = m.group(1), m.group(2)
    idx += 1

    m = _match(
        _ZAHLUNGSBED_RE,
        line_at(idx, "'Zahlungsbedingungen:' line"),
        "'Zahlungsbedingungen:' line",
    )
    payment_terms = m.group(1)
    idx += 1

    m = _match(
        _VERWENDUNGSZWECK_RE,
        line_at(idx, "'Verwendungszweck:' line"),
        "'Verwendungszweck:' line",
    )
    verwendungszweck = m.group(1)
    idx += 1

    if verwendungszweck != invoice_number:
        raise ParserLayoutError(
            f"'Verwendungszweck:' value {verwendungszweck!r} does not match "
            f"invoice number {invoice_number!r} -- this parser assumes it is always "
            f"a restatement of the invoice number, never a structured reference"
        )

    if idx != len(lines):
        raise ParserLayoutError(
            f"unexpected trailing content after 'Verwendungszweck:' line: {lines[idx:]!r}"
        )

    # ---- arithmetic reconciliation -----------------------------------
    net_dec = Decimal(net_canonical)
    vat_dec = Decimal(vat_amount_canonical)
    gross_dec = Decimal(gross_canonical)

    lines_sum = sum((Decimal(li["line_total"]) for li in item_lines), Decimal("0.00"))
    if lines_sum != net_dec:
        raise ParserLayoutError(f"line totals sum to {lines_sum} but printed Netto is {net_dec}")

    distinct_rates = {li["vat_rate"] for li in item_lines}
    if distinct_rates != {vat_rate_canonical}:
        raise ParserLayoutError(
            f"line item VAT rate(s) {sorted(distinct_rates)} do not match the single "
            f"Umsatzsteuer rate {vat_rate_canonical!r} (this parser only supports a "
            f"single VAT rate group, the only pattern observed for this supplier)"
        )

    expected_vat = (net_dec * Decimal(vat_rate_canonical) / Decimal("100")).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )
    if expected_vat != vat_dec:
        raise ParserLayoutError(
            f"expected VAT amount {expected_vat} from rate {vat_rate_canonical}, printed {vat_dec}"
        )

    if net_dec + vat_dec != gross_dec:
        raise ParserLayoutError(f"Netto {net_dec} + Umsatzsteuer {vat_dec} != Brutto {gross_dec}")

    doc_id = Path(pdf_path).stem

    return {
        "schema_version": "1.0",
        "doc_id": doc_id,
        "supplier": {
            "name": supplier_name,
            "street": supplier_street,
            "postcode": supplier_postcode,
            "city": supplier_city,
            "country": supplier_country,
            "vat_id": supplier_vat_id,
            "business_id": supplier_business_id,
        },
        "buyer": {
            "name": buyer_name,
            "street": buyer_street,
            "postcode": buyer_postcode,
            "city": buyer_city,
            "country": buyer_country,
            "vat_id": buyer_vat_id,
            "business_id": buyer_business_id,
        },
        "invoice": {
            "number": invoice_number,
            "type": "invoice",
            "issue_date": issue_date,
            "supply_date": supply_date,
            "due_date": due_date,
            "payment_terms": payment_terms,
            "currency": currency,
            "po_number": po_number,
            "reference_type": None,
            "reference_value": None,
            "original_invoice_number": None,
            "reverse_charge_mention": reverse_charge_line,
        },
        "bank": {
            "iban": iban,
            "bic": bic,
            "bankgiro": None,
        },
        "lines": item_lines,
        "vat_summary": [
            {"rate": vat_rate_canonical, "base": net_canonical, "amount": vat_amount_canonical}
        ],
        "totals": {
            "net": net_canonical,
            "vat": vat_amount_canonical,
            "gross": gross_canonical,
        },
    }


# ---------------------------------------------------------------------------
# Mandatory self-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import json
    import sys

    args = sys.argv[1:]
    pairs = []

    if len(args) == 1 and args[0].lower().endswith(".json"):
        with open(args[0], "r", encoding="utf-8") as fh:
            manifest = json.load(fh)
        for item in manifest:
            pairs.append((item[0], item[1]))
    else:
        if len(args) == 0 or len(args) % 2 != 0:
            print(
                "Usage: parser_s3.py (pdf_path accepted_parse_json_path)... | manifest.json",
                file=sys.stderr,
            )
            sys.exit(2)
        for i in range(0, len(args), 2):
            pairs.append((args[i], args[i + 1]))

    failures = 0
    for pdf_path, json_path in pairs:
        with open(json_path, "r", encoding="utf-8") as fh:
            expected = json.load(fh)
        try:
            actual = parse(pdf_path)
        except ParserLayoutError as exc:
            print(f"FAIL {pdf_path}: ParserLayoutError: {exc}")
            failures += 1
            continue
        if actual == expected:
            print(f"PASS {pdf_path}")
        else:
            print(f"FAIL {pdf_path}: output mismatch")
            print(f"  expected: {expected}")
            print(f"  actual:   {actual}")
            failures += 1

    total = len(pairs)
    print(f"\n{total - failures}/{total} PASS")
    sys.exit(1 if failures else 0)
