"""parser_s2.py -- deterministic parser for supplier s2, Paijat-Pakkaus Oy.

Provenance
----------
Machine-generated by the overseer agent (model: Claude Sonnet 5), 2026-07-03,
per design/overseer_brief_v1.md (v1.0). Induced from 6 accepted LLM parses,
their source PDFs, and their pdfplumber text/word-coordinate dumps, for
doc_ids:
    2025-01_s2_01, 2025-01_s2_02, 2025-01_s2_03,
    2025-02_s2_01, 2025-02_s2_02, 2025-03_s2_01
No other files (no answer keys, no generator/template code, no other
suppliers' files) were consulted while writing this module.

Layout this parser targets (single page, compact monospace text layout,
observed identically across all 6 induction documents; line numbers are
0-indexed positions in `page.extract_text().splitlines()`):

    0: "Paijat-Pakkaus Oy"
    1: "<street>, <postcode> <city> -- Y-tunnus <business_id> -- ALV-tunnus <vat_id>"
    2: "Lasku <number> Laskun paiva <DD.MM.YYYY> Erapaiva <DD.MM.YYYY> Viitenumero <ref>"
    3: "Tilausnumero <po_number>"
    4: "<buyer name>, <buyer street>, <buyer postcode> <buyer city> (Y-tunnus <buyer business_id>)"
    5: "Nimike Maara Yksikko A-hinta Yhteensa"                      <- verbatim column header
    6 .. 6+k-1: "<description> <qty> kpl <unit_price> <line_total>"  <- k line items;
        NOTE: there is NO per-line VAT-rate column. A single document-level
        VAT rate is printed once, in the totals block, and is carried onto
        every parsed line (matching how the accepted parses represent it).
    then, in this fixed order:
        "Veroton yhteensa <net>"
        "ALV <rate> % <vat_amount>"
        "Maksettava <gross> EUR-sign"
        "Maksuehto: <payment_terms> -- Viitenumero: <ref, repeated>"
        "Pankkiyhteys <iban> BIC <bic>"

Numbers use a comma decimal separator and are never thousands-grouped
(observed up to 4-digit quantities, e.g. 1013, printed as a single unspaced
token) -- this parser assumes contiguous digit runs and does not attempt to
strip thousands separators, because none were observed.

Every landmark label, column header, block ordering and cross-figure
consistency check below (line-item qty * unit_price == line_total; sum of
line totals == printed net; net + vat == gross; the two Viitenumero
occurrences agreeing) is verified. Any deviation raises ParserLayoutError
rather than being silently guessed at or coerced.
"""

from __future__ import annotations

import re
from decimal import Decimal, InvalidOperation
from pathlib import Path

import pdfplumber


class ParserLayoutError(Exception):
    """Raised when the PDF does not match the exact layout this parser was induced from."""


# ---------------------------------------------------------------------------
# Layout constants and landmark patterns (all induced from the 6 documents)
# ---------------------------------------------------------------------------

_SUPPLIER_NAME = "Päijät-Pakkaus Oy"

_HEADER_ROW = "Nimike Määrä Yksikkö A-hinta Yhteensä"

_EXPECTED_UNIT = "kpl"

_ALLOWED_VAT_RATES = {"25.5", "14.0", "10.0", "0.0"}

_RE_SUPPLIER_ADDR = re.compile(
    r"^(?P<street>.+?),\s*(?P<postcode>\d{5})\s+(?P<city>\S+)\s+--\s+"
    r"Y-tunnus\s+(?P<business_id>\d{7}-\d)\s+--\s+"
    r"ALV-tunnus\s+(?P<vat_id>[A-Z]{2}\d{8})$"
)

_RE_INVOICE_HEAD = re.compile(
    r"^Lasku\s+(?P<number>\S+)\s+Laskun päivä\s+(?P<issue>\d{2}\.\d{2}\.\d{4})\s+"
    r"Eräpäivä\s+(?P<due>\d{2}\.\d{2}\.\d{4})\s+Viitenumero\s+(?P<ref>\S+)$"
)

_RE_PO = re.compile(r"^Tilausnumero\s+(?P<po>\S+)$")

_RE_BUYER = re.compile(
    r"^(?P<name>.+?),\s*(?P<street>.+?),\s*(?P<postcode>\d{5})\s+(?P<city>\S+)\s+"
    r"\(Y-tunnus\s+(?P<business_id>\d{7}-\d)\)$"
)

_RE_ITEM = re.compile(
    r"^(?P<desc>.+?)\s+(?P<qty>\d+)\s+(?P<unit>\S+)\s+"
    r"(?P<price>\d+,\d{2})\s+(?P<total>\d+,\d{2})$"
)

_RE_NET = re.compile(r"^Veroton yhteensä\s+(?P<net>\d+,\d{2})$")
_RE_VAT = re.compile(r"^ALV\s+(?P<rate>\d+(?:,\d+)?)\s+%\s+(?P<amount>\d+,\d{2})$")
_RE_GROSS = re.compile(r"^Maksettava\s+(?P<gross>\d+,\d{2})\s*€$")
_RE_TERMS = re.compile(
    r"^Maksuehto:\s+(?P<terms>.+?)\s+--\s+Viitenumero:\s+(?P<ref2>\S+)$"
)
_RE_BANK = re.compile(r"^Pankkiyhteys\s+(?P<iban>\S+)\s+BIC\s+(?P<bic>\S+)$")

_CENTS = Decimal("0.01")
_TENTH = Decimal("0.1")


def _money(raw: str, where: str) -> str:
    """Canonicalise a comma-decimal amount to a '.'-decimal, 2-dp string."""
    try:
        value = Decimal(raw.replace(",", "."))
    except InvalidOperation as exc:
        raise ParserLayoutError(f"{where}: unparsable amount {raw!r}") from exc
    return str(value.quantize(_CENTS))


def _to_iso(raw: str, where: str) -> str:
    m = re.match(r"^(?P<d>\d{2})\.(?P<m>\d{2})\.(?P<y>\d{4})$", raw)
    if not m:
        raise ParserLayoutError(f"{where}: unparsable date {raw!r}")
    day, month, year = int(m.group("d")), int(m.group("m")), m.group("y")
    if not (1 <= month <= 12 and 1 <= day <= 31):
        raise ParserLayoutError(f"{where}: implausible date {raw!r}")
    return f"{year}-{m.group('m')}-{m.group('d')}"


def parse(pdf_path: str) -> dict:
    """Parse a Paijat-Pakkaus Oy (supplier s2) invoice PDF into the accepted-parse schema.

    Raises ParserLayoutError (never returns a guessed/partial record) the moment
    any expected label, column header, block ordering, or cross-figure
    consistency check fails.
    """
    with pdfplumber.open(pdf_path) as pdf:
        if len(pdf.pages) != 1:
            raise ParserLayoutError(
                f"expected exactly 1 page, found {len(pdf.pages)} (not seen in induction set)"
            )
        text = pdf.pages[0].extract_text()

    if text is None or text.strip() == "":
        raise ParserLayoutError("no extractable text layer on page 1")

    lines = text.splitlines()

    if len(lines) < 6:
        raise ParserLayoutError(
            f"expected at least 6 header lines before the item table, got {len(lines)}"
        )

    # -- line 0: supplier name (fixed landmark for this supplier-specific parser) --
    if lines[0] != _SUPPLIER_NAME:
        raise ParserLayoutError(
            f"line 1: expected supplier name {_SUPPLIER_NAME!r}, got {lines[0]!r}"
        )

    # -- line 1: supplier address / Y-tunnus / ALV-tunnus --
    m = _RE_SUPPLIER_ADDR.match(lines[1])
    if not m:
        raise ParserLayoutError(f"line 2 did not match the supplier-address pattern: {lines[1]!r}")
    supplier_vat_id = m.group("vat_id")
    country = supplier_vat_id[:2]
    supplier = {
        "name": _SUPPLIER_NAME,
        "street": m.group("street"),
        "postcode": m.group("postcode"),
        "city": m.group("city"),
        "country": country,
        "vat_id": supplier_vat_id,
        "business_id": m.group("business_id"),
    }

    # -- line 2: "Lasku <number> Laskun paiva ... Erapaiva ... Viitenumero <ref>" --
    m = _RE_INVOICE_HEAD.match(lines[2])
    if not m:
        raise ParserLayoutError(f"line 3 did not match the invoice-header pattern: {lines[2]!r}")
    invoice_number = m.group("number")
    issue_date = _to_iso(m.group("issue"), "issue_date")
    due_date = _to_iso(m.group("due"), "due_date")
    reference_value = m.group("ref")

    # -- line 3: "Tilausnumero <po_number>" --
    m = _RE_PO.match(lines[3])
    if not m:
        raise ParserLayoutError(f"line 4 did not match the PO-number pattern: {lines[3]!r}")
    po_number = m.group("po")

    # -- line 4: buyer name/address/business id --
    m = _RE_BUYER.match(lines[4])
    if not m:
        raise ParserLayoutError(f"line 5 did not match the buyer-address pattern: {lines[4]!r}")
    buyer = {
        "name": m.group("name"),
        "street": m.group("street"),
        "postcode": m.group("postcode"),
        "city": m.group("city"),
        "country": country,
        "vat_id": None,
        "business_id": m.group("business_id"),
    }

    # -- line 5: column header, verbatim --
    if lines[5] != _HEADER_ROW:
        raise ParserLayoutError(f"line 6: expected column header {_HEADER_ROW!r}, got {lines[5]!r}")

    # -- line items: from line 6 until the "Veroton yhteensa" totals line --
    idx = 6
    parsed_lines = []
    while idx < len(lines) and not lines[idx].startswith("Veroton yhteensä"):
        raw_line = lines[idx]
        m = _RE_ITEM.match(raw_line)
        if not m:
            raise ParserLayoutError(
                f"line {idx + 1} is neither a recognisable line item nor the totals row: {raw_line!r}"
            )
        desc = m.group("desc").strip()
        qty = m.group("qty")
        unit = m.group("unit")
        if unit != _EXPECTED_UNIT:
            raise ParserLayoutError(
                f"line {idx + 1}: unexpected unit {unit!r} (only {_EXPECTED_UNIT!r} was observed)"
            )
        unit_price = _money(m.group("price"), f"line {idx + 1} unit_price")
        line_total = _money(m.group("total"), f"line {idx + 1} line_total")

        expected_total = (Decimal(qty) * Decimal(unit_price)).quantize(_CENTS)
        if expected_total != Decimal(line_total):
            raise ParserLayoutError(
                f"line {idx + 1} arithmetic mismatch: {qty} x {unit_price} = "
                f"{expected_total}, printed line_total is {line_total}"
            )

        parsed_lines.append(
            {
                "description": desc,
                "quantity": qty,
                "unit": unit,
                "unit_price": unit_price,
                "vat_rate": None,  # filled in once the document-level rate is known
                "line_total": line_total,
            }
        )
        idx += 1

    if not parsed_lines:
        raise ParserLayoutError("no line items found between the column header and the totals block")

    if idx >= len(lines):
        raise ParserLayoutError("reached end of text before the totals block ('Veroton yhteensä' line)")

    # -- "Veroton yhteensa <net>" --
    m = _RE_NET.match(lines[idx])
    if not m:
        raise ParserLayoutError(f"line {idx + 1} did not match the net-total pattern: {lines[idx]!r}")
    net = _money(m.group("net"), "net total")
    idx += 1

    # -- "ALV <rate> % <vat_amount>" --
    if idx >= len(lines):
        raise ParserLayoutError("reached end of text before the ALV (VAT) line")
    m = _RE_VAT.match(lines[idx])
    if not m:
        raise ParserLayoutError(f"line {idx + 1} did not match the VAT-summary pattern: {lines[idx]!r}")
    rate_raw = m.group("rate")
    vat_amount = _money(m.group("amount"), "VAT amount")
    idx += 1

    try:
        rate_dec = Decimal(rate_raw.replace(",", "."))
    except InvalidOperation as exc:
        raise ParserLayoutError(f"unparsable VAT rate {rate_raw!r}") from exc
    rate_str = str(rate_dec.quantize(_TENTH))
    if rate_str not in _ALLOWED_VAT_RATES:
        raise ParserLayoutError(
            f"VAT rate {rate_str!r} is not one of the allowed canonical rates {sorted(_ALLOWED_VAT_RATES)}"
        )

    # -- "Maksettava <gross> EUR-sign" --
    if idx >= len(lines):
        raise ParserLayoutError("reached end of text before the Maksettava (gross) line")
    m = _RE_GROSS.match(lines[idx])
    if not m:
        raise ParserLayoutError(f"line {idx + 1} did not match the gross-total pattern: {lines[idx]!r}")
    gross = _money(m.group("gross"), "gross total")
    idx += 1

    # -- "Maksuehto: <terms> -- Viitenumero: <ref2>" --
    if idx >= len(lines):
        raise ParserLayoutError("reached end of text before the Maksuehto (payment terms) line")
    m = _RE_TERMS.match(lines[idx])
    if not m:
        raise ParserLayoutError(f"line {idx + 1} did not match the payment-terms pattern: {lines[idx]!r}")
    payment_terms = m.group("terms")
    ref2 = m.group("ref2")
    if ref2 != reference_value:
        raise ParserLayoutError(
            f"reference number mismatch: header Viitenumero {reference_value!r} vs "
            f"footer Viitenumero {ref2!r}"
        )
    idx += 1

    # -- "Pankkiyhteys <iban> BIC <bic>" --
    if idx >= len(lines):
        raise ParserLayoutError("reached end of text before the Pankkiyhteys (bank) line")
    m = _RE_BANK.match(lines[idx])
    if not m:
        raise ParserLayoutError(f"line {idx + 1} did not match the bank-details pattern: {lines[idx]!r}")
    iban = m.group("iban")
    bic = m.group("bic")
    idx += 1

    if idx != len(lines):
        raise ParserLayoutError(
            f"unexpected trailing content after the bank-details line: {lines[idx:]!r}"
        )

    # -- cross-figure arithmetic reconciliation --
    summed = sum((Decimal(li["line_total"]) for li in parsed_lines), Decimal("0")).quantize(_CENTS)
    if summed != Decimal(net):
        raise ParserLayoutError(f"sum of line totals {summed} != printed net total {net}")

    if (Decimal(net) + Decimal(vat_amount)).quantize(_CENTS) != Decimal(gross):
        raise ParserLayoutError(
            f"net {net} + VAT {vat_amount} = {(Decimal(net) + Decimal(vat_amount)).quantize(_CENTS)}, "
            f"printed gross is {gross}"
        )

    # the document carries a single VAT rate for every line (no per-line VAT column)
    for li in parsed_lines:
        li["vat_rate"] = rate_str

    doc_id = Path(pdf_path).stem

    return {
        "schema_version": "1.0",
        "doc_id": doc_id,
        "supplier": supplier,
        "buyer": buyer,
        "invoice": {
            "number": invoice_number,
            "type": "invoice",
            "issue_date": issue_date,
            "supply_date": None,
            "due_date": due_date,
            "payment_terms": payment_terms,
            "currency": "EUR",
            "po_number": po_number,
            "reference_type": "viitenumero",
            "reference_value": reference_value,
            "original_invoice_number": None,
            "reverse_charge_mention": None,
        },
        "bank": {"iban": iban, "bic": bic, "bankgiro": None},
        "lines": parsed_lines,
        "vat_summary": [{"rate": rate_str, "base": net, "amount": vat_amount}],
        "totals": {"net": net, "vat": vat_amount, "gross": gross},
    }


if __name__ == "__main__":
    import json
    import sys

    def _load_pairs(argv: list[str]) -> list[tuple[str, str]]:
        if len(argv) == 1 and argv[0].lower().endswith(".json"):
            manifest = json.loads(Path(argv[0]).read_text(encoding="utf-8"))
            pairs = []
            for entry in manifest:
                if isinstance(entry, dict):
                    pairs.append((entry["pdf"], entry["json"]))
                else:
                    pdf_p, json_p = entry
                    pairs.append((pdf_p, json_p))
            return pairs
        if len(argv) % 2 != 0:
            raise SystemExit(
                "usage: parser_s2.py (pdf json)... | parser_s2.py manifest.json"
            )
        return list(zip(argv[0::2], argv[1::2]))

    arg_pairs = _load_pairs(sys.argv[1:])
    if not arg_pairs:
        raise SystemExit("no (pdf_path, accepted_parse_json_path) pairs given")

    n_fail = 0
    for pdf_arg, json_arg in arg_pairs:
        doc_id = Path(pdf_arg).stem
        try:
            got = parse(pdf_arg)
        except Exception as exc:  # self-test must report every failure, not hide it
            print(f"FAIL {doc_id}: parser raised {type(exc).__name__}: {exc}")
            n_fail += 1
            continue

        expected = json.loads(Path(json_arg).read_text(encoding="utf-8"))
        if got == expected:
            print(f"PASS {doc_id}")
        else:
            print(f"FAIL {doc_id}: parsed record does not match the accepted parse")
            all_keys = list(expected.keys())
            for key in all_keys:
                if got.get(key) != expected.get(key):
                    print(f"  field {key!r} differs:")
                    print(f"    expected = {expected.get(key)!r}")
                    print(f"    got      = {got.get(key)!r}")
            n_fail += 1

    n_total = len(arg_pairs)
    print(f"{n_total - n_fail}/{n_total} PASS")
    sys.exit(1 if n_fail else 0)
