"""
parser_s8v2.py -- deterministic parser for Tyokalu-Tiira Oy (supplier s8),
SECOND invoice layout.

Machine-generated by the overseer agent (Claude, Sonnet 5), 3 July 2026,
following design/overseer_brief_v1.md. This supplier changed invoicing
software mid-2025; its old template (parser_s8.py, invoice numbers in the
"T-NNNN" series) no longer applies. This module handles the new template,
whose invoice numbers run in a "YYYY-NNNN" series, adopted from ~August
2025 onward. It was induced strictly from N = 6 accepted LLM parses and
their source documents, and must NOT be used as evidence about the old
layout or any other supplier.

Induction set (doc_id):
    2025-08_s8_01, 2025-08_s8_02, 2025-09_s8_01, 2025-09_s8_02,
    2025-10_s8_01, 2025-10_s8_02

Inputs read while writing this module (see brief for the exact hard
boundary -- nothing else was opened):
    data/runs/llm_parses/<doc_id>.json         (accepted parses)
    data/documents/<doc_id>.pdf                (source PDFs)
    data/runs/text_layers/<doc_id>.txt         (pdfplumber extract_text dumps)
    data/runs/text_layers/<doc_id>.words.json  (pdfplumber extract_words dumps)

Layout landmarks this parser keys on
------------------------------------
- A dark header band holding, on the left, the supplier name in large
  type, and on the right a four-line block: "Lasku <number>", "Laskun
  paiva <date>", "Erapaiva <date>", "Viitenumero <ref>", "Tilausnumero
  <po>" (PO number is always printed, unlike the old layout).
- Invoice numbers in a "YYYY-NNNN" series (old layout used "T-NNNN"); this
  is used as a hard discriminator so a mis-routed old-layout document
  fails loudly here instead of being silently misparsed.
- A one-line "OSTAJA" buyer block: name, street, "postcode city",
  "Y-tunnus: <business id>".
- The line-item table header "NIMIKEKOODI NIMIKE MAARA YKSIKKO ALV %
  A-HINTA YHTEENSA", repeated verbatim on continuation pages (marked
  "Lasku <number> (jatkuu)"). NIMIKEKOODI carries a fixed-format product
  code (TK-NNNN) that is layout furniture only: every row has one, it is
  used here purely as a row-start landmark, and it is never emitted,
  because the accepted-parse schema has no product-code field.
- IMPORTANT: the item table's column x-positions are NOT stable across
  documents, or even across pages of the same document -- the table
  appears to reflow/auto-size per page (confirmed by comparing
  extract_words dumps: e.g. the MAARA column starts at x=290.6 on most
  pages but at x=265.6 or x=280.6 on others with fewer/shorter rows).
  Coordinate-bucketing columns would therefore be fragile. Instead, each
  item row is read as plain text (extract_text(), which reconstructs
  correct reading order regardless of the column reflow) and anchored on
  its FIRST token (the product code, validated by regex) and its LAST
  FIVE tokens (quantity, unit, VAT rate, unit price, line total, each
  validated by a strict format regex); everything in between is taken
  verbatim as the description. This sidesteps the column drift entirely.
- A left-aligned totals block: "Veroton yhteensa <amount> EUR",
  "ALV <rate> % <amount> EUR", "Maksettava <amount> EUR". Every induction
  document has exactly one VAT bracket, at 25.5%.
- A footer with three fixed lines: "Y-tunnus <id> -- ALV-tunnus <id>",
  "Maksuehto: <terms> -- Viitenumero: <ref>",
  "Pankkiyhteys: <IBAN> BIC: <BIC>".
- Supplier identity (name/street/postcode/city/business id/VAT id) was
  byte-for-byte identical across all 6 induction documents; this parser
  treats that identity as a landmark and fails loudly if it does not
  match, since a mismatch would mean this is not actually an invoice from
  this supplier.
"""

import re
from datetime import datetime
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from pathlib import Path

import pdfplumber


class ParserLayoutError(Exception):
    """Raised whenever the PDF does not match the layout this parser was built for."""


# --- fixed supplier identity, constant across every induction document ---
_SUPPLIER_NAME = "Työkalu-Tiira Oy"
_SUPPLIER_STREET = "Teollisuuskatu 19"
_SUPPLIER_POSTCODE = "15170"
_SUPPLIER_CITY = "Lahti"
_SUPPLIER_BUSINESS_ID = "2277889-2"
_SUPPLIER_VAT_ID = "FI22778892"

_ITEM_HEADER_LINE = "NIMIKEKOODI NIMIKE MÄÄRÄ YKSIKKÖ ALV % A-HINTA YHTEENSÄ"

_ALLOWED_VAT_RATES = {"25.5", "14.0", "10.0", "0.0"}

# --- header-block line patterns (page 1) ---
_RE_LASKU = re.compile(r"^Lasku\s+(?P<num>\S+)(?:\s+\(jatkuu\))?$")
_RE_NAME_DATE = re.compile(r"^(?P<name>.+?)\s+Laskun päivä\s+(?P<date>\d{2}\.\d{2}\.\d{4})$")
_RE_DUE = re.compile(r"^Eräpäivä\s+(?P<date>\d{2}\.\d{2}\.\d{4})$")
_RE_ADDR = re.compile(
    r"^(?P<street>.+?),\s+(?P<postcode>\d{5})\s+(?P<city>.+?)\s+·\s+"
    r"Y-tunnus\s+(?P<bid>\S+)\s+Viitenumero\s+(?P<ref>\S+)$"
)
_RE_PO = re.compile(r"^Tilausnumero\s+(?P<po>\S+)$")
_RE_BUYER_POSTCODE_CITY = re.compile(r"^(?P<postcode>\d{5})\s+(?P<city>.+)$")
_RE_BUYER_BID = re.compile(r"^Y-tunnus:\s+(?P<bid>\S+)$")

# --- totals + footer patterns (final page only) ---
_RE_NET = re.compile(r"^Veroton yhteensä\s+(?P<net>[\d\s]+,\d{2})\s*€$")
_RE_VAT_LINE = re.compile(r"^ALV\s+(?P<rate>\d{1,2},\d)\s*%\s+(?P<amount>[\d\s]+,\d{2})\s*€$")
_RE_GROSS = re.compile(r"^Maksettava\s+(?P<gross>[\d\s]+,\d{2})\s*€$")
_RE_FOOTER_IDS = re.compile(r"^Y-tunnus\s+(?P<bid>\S+)\s+--\s+ALV-tunnus\s+(?P<vid>\S+)$")
_RE_TERMS = re.compile(r"^Maksuehto:\s+(?P<terms>.+?)\s+--\s+Viitenumero:\s+(?P<ref>\S+)$")
_RE_BANK = re.compile(r"^Pankkiyhteys:\s+(?P<iban>\S+)\s+BIC:\s+(?P<bic>\S+)$")

# --- value-level patterns ---
_RE_INVOICE_NUMBER = re.compile(r"^\d{4}-\d{4,}$")
_RE_PRODUCT_CODE = re.compile(r"^TK-\d{4}$")
_RE_QTY = re.compile(r"^\d+$")
_RE_VAT_TOK = re.compile(r"^\d{1,2},\d$")
_RE_MONEY_TOK = re.compile(r"^\d+,\d{2}$")


def _fi_date_to_iso(date_str: str) -> str:
    try:
        return datetime.strptime(date_str, "%d.%m.%Y").strftime("%Y-%m-%d")
    except ValueError as exc:
        raise ParserLayoutError(f"unparseable date: {date_str!r}") from exc


def _fi_money_to_canonical(raw: str) -> str:
    cleaned = re.sub(r"\s", "", raw).replace(",", ".")
    try:
        value = Decimal(cleaned)
    except InvalidOperation as exc:
        raise ParserLayoutError(f"unparseable money amount: {raw!r}") from exc
    quantized = value.quantize(Decimal("0.01"))
    if value != quantized:
        raise ParserLayoutError(f"money amount not to the cent: {raw!r}")
    return f"{quantized}"


def _parse_item_line(line: str) -> dict:
    tokens = line.split()
    if len(tokens) < 7:
        raise ParserLayoutError(f"item line has too few tokens ({len(tokens)}): {line!r}")

    code = tokens[0]
    if not _RE_PRODUCT_CODE.match(code):
        raise ParserLayoutError(f"unexpected product code format {code!r} in line {line!r}")

    qty_tok, unit_tok, vat_tok, price_tok, total_tok = tokens[-5:]
    description_tokens = tokens[1:-5]
    if not description_tokens:
        raise ParserLayoutError(f"item line missing description: {line!r}")
    if not unit_tok:
        raise ParserLayoutError(f"item line missing unit token: {line!r}")

    if not _RE_QTY.match(qty_tok):
        raise ParserLayoutError(f"unexpected quantity format {qty_tok!r} in line {line!r}")
    if not _RE_VAT_TOK.match(vat_tok):
        raise ParserLayoutError(f"unexpected VAT rate format {vat_tok!r} in line {line!r}")
    vat_rate = vat_tok.replace(",", ".")
    if vat_rate not in _ALLOWED_VAT_RATES:
        raise ParserLayoutError(f"VAT rate {vat_rate!r} outside the canonical set, line {line!r}")
    if not _RE_MONEY_TOK.match(price_tok):
        raise ParserLayoutError(f"unexpected unit price format {price_tok!r} in line {line!r}")
    if not _RE_MONEY_TOK.match(total_tok):
        raise ParserLayoutError(f"unexpected line total format {total_tok!r} in line {line!r}")

    unit_price = price_tok.replace(",", ".")
    line_total = total_tok.replace(",", ".")

    expected_total = (Decimal(qty_tok) * Decimal(unit_price)).quantize(Decimal("0.01"))
    if expected_total != Decimal(line_total):
        raise ParserLayoutError(
            f"line arithmetic does not reconcile: {qty_tok} x {unit_price} = "
            f"{expected_total} but printed total is {line_total} (line {line!r})"
        )

    return {
        "description": " ".join(description_tokens),
        "quantity": qty_tok,
        "unit": unit_tok,
        "unit_price": unit_price,
        "vat_rate": vat_rate,
        "line_total": line_total,
    }


def _take(page_lines: list, pos_box: list, what: str) -> str:
    if pos_box[0] >= len(page_lines):
        raise ParserLayoutError(f"ran out of lines while expecting {what}")
    line = page_lines[pos_box[0]]
    pos_box[0] += 1
    return line


def parse(pdf_path: str) -> dict:
    """Parse a Tyokalu-Tiira Oy (supplier s8) NEW-layout invoice PDF.

    Returns a dict in the exact schema of the accepted LLM parses.
    Raises ParserLayoutError the moment anything about the layout,
    labelling, or arithmetic is not as observed in the induction set.
    """
    with pdfplumber.open(pdf_path) as pdf:
        if len(pdf.pages) == 0:
            raise ParserLayoutError("PDF has no pages")
        pages_lines = []
        for page in pdf.pages:
            text = page.extract_text()
            if text is None:
                raise ParserLayoutError("a page has no extractable text layer")
            cleaned = [ln.strip() for ln in text.split("\n")]
            pages_lines.append([ln for ln in cleaned if ln])

    if not pages_lines or not pages_lines[0]:
        raise ParserLayoutError("first page has no text")

    lines0 = pages_lines[0]
    p0 = [0]

    line = _take(lines0, p0, "'Lasku <number>' line")
    m = _RE_LASKU.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Lasku <number>' as first line, got {line!r}")
    invoice_number = m.group("num")
    if not _RE_INVOICE_NUMBER.match(invoice_number):
        raise ParserLayoutError(
            f"invoice number {invoice_number!r} is not in the 'YYYY-NNNN' series this "
            "parser (new s8 layout) was built for -- an old 'T-NNNN' layout invoice "
            "should not be routed here"
        )

    line = _take(lines0, p0, "supplier name + 'Laskun päivä' line")
    m = _RE_NAME_DATE.match(line)
    if not m:
        raise ParserLayoutError(f"expected supplier name + 'Laskun päivä' line, got {line!r}")
    supplier_name = m.group("name").strip()
    if supplier_name != _SUPPLIER_NAME:
        raise ParserLayoutError(f"unexpected supplier name {supplier_name!r}")
    issue_date = _fi_date_to_iso(m.group("date"))

    line = _take(lines0, p0, "'Eräpäivä' line")
    m = _RE_DUE.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Eräpäivä' line, got {line!r}")
    due_date = _fi_date_to_iso(m.group("date"))

    line = _take(lines0, p0, "supplier address / Y-tunnus / Viitenumero line")
    m = _RE_ADDR.match(line)
    if not m:
        raise ParserLayoutError(
            f"expected supplier address/Y-tunnus/Viitenumero line, got {line!r}"
        )
    supplier_street = m.group("street")
    supplier_postcode = m.group("postcode")
    supplier_city = m.group("city")
    supplier_business_id_hdr = m.group("bid")
    reference_value_hdr = m.group("ref")
    if (
        supplier_street != _SUPPLIER_STREET
        or supplier_postcode != _SUPPLIER_POSTCODE
        or supplier_city != _SUPPLIER_CITY
    ):
        raise ParserLayoutError(
            f"unexpected supplier address: {supplier_street!r} {supplier_postcode!r} "
            f"{supplier_city!r}"
        )
    if supplier_business_id_hdr != _SUPPLIER_BUSINESS_ID:
        raise ParserLayoutError(
            f"unexpected supplier business id in header: {supplier_business_id_hdr!r}"
        )

    line = _take(lines0, p0, "'Tilausnumero' line")
    m = _RE_PO.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Tilausnumero' line, got {line!r}")
    po_number = m.group("po")

    line = _take(lines0, p0, "'OSTAJA' heading")
    if line != "OSTAJA":
        raise ParserLayoutError(f"expected 'OSTAJA' heading, got {line!r}")

    buyer_name = _take(lines0, p0, "buyer name line")
    buyer_street = _take(lines0, p0, "buyer street line")

    line = _take(lines0, p0, "buyer postcode/city line")
    m = _RE_BUYER_POSTCODE_CITY.match(line)
    if not m:
        raise ParserLayoutError(f"expected buyer postcode/city line, got {line!r}")
    buyer_postcode = m.group("postcode")
    buyer_city = m.group("city")

    line = _take(lines0, p0, "buyer 'Y-tunnus:' line")
    m = _RE_BUYER_BID.match(line)
    if not m:
        raise ParserLayoutError(f"expected buyer 'Y-tunnus:' line, got {line!r}")
    buyer_business_id = m.group("bid")

    line = _take(lines0, p0, "item table header")
    if line != _ITEM_HEADER_LINE:
        raise ParserLayoutError(f"expected item table header, got {line!r}")

    # --- item rows, possibly spanning multiple pages ---
    raw_item_lines = []
    totals_lines = None
    totals_page_idx = None

    for page_idx, page_lines in enumerate(pages_lines):
        if page_idx == 0:
            start = p0[0]
        else:
            cpos = [0]
            line = _take(page_lines, cpos, "continuation 'Lasku ... (jatkuu)' line")
            m = _RE_LASKU.match(line)
            if not m:
                raise ParserLayoutError(
                    f"expected continuation 'Lasku ... (jatkuu)' line, got {line!r}"
                )
            if "(jatkuu)" not in line:
                raise ParserLayoutError(
                    f"expected '(jatkuu)' marker on continuation page, got {line!r}"
                )
            if m.group("num") != invoice_number:
                raise ParserLayoutError(
                    f"continuation page invoice number {m.group('num')!r} does not "
                    f"match {invoice_number!r}"
                )
            line = _take(page_lines, cpos, "item table header on continuation page")
            if line != _ITEM_HEADER_LINE:
                raise ParserLayoutError(
                    f"expected item table header on continuation page, got {line!r}"
                )
            start = cpos[0]

        i = start
        n = len(page_lines)
        while i < n:
            candidate = page_lines[i]
            if _RE_NET.match(candidate):
                totals_lines = page_lines[i:]
                totals_page_idx = page_idx
                break
            raw_item_lines.append(candidate)
            i += 1
        if totals_lines is not None:
            break
    else:
        raise ParserLayoutError("reached end of document without finding the totals block")

    if totals_page_idx != len(pages_lines) - 1:
        raise ParserLayoutError(
            "totals block was found before the final page; unexpected extra page(s) follow it"
        )
    if not raw_item_lines:
        raise ParserLayoutError("no item lines found between the table header and totals block")

    parsed_lines = [_parse_item_line(ln) for ln in raw_item_lines]

    # --- totals + footer block (6 fixed lines on the final page) ---
    tpos = [0]
    line = _take(totals_lines, tpos, "'Veroton yhteensä' line")
    m = _RE_NET.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Veroton yhteensä' line, got {line!r}")
    net = _fi_money_to_canonical(m.group("net"))

    line = _take(totals_lines, tpos, "'ALV n,n %% amount' line")
    m = _RE_VAT_LINE.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'ALV n,n %% amount €' line, got {line!r}")
    vat_rate_summary = m.group("rate").replace(",", ".")
    if vat_rate_summary not in _ALLOWED_VAT_RATES:
        raise ParserLayoutError(f"VAT summary rate {vat_rate_summary!r} outside canonical set")
    vat_amount = _fi_money_to_canonical(m.group("amount"))

    line = _take(totals_lines, tpos, "'Maksettava' line")
    m = _RE_GROSS.match(line)
    if not m:
        raise ParserLayoutError(f"expected 'Maksettava amount €' line, got {line!r}")
    gross = _fi_money_to_canonical(m.group("gross"))

    line = _take(totals_lines, tpos, "footer Y-tunnus/ALV-tunnus line")
    m = _RE_FOOTER_IDS.match(line)
    if not m:
        raise ParserLayoutError(f"expected footer Y-tunnus/ALV-tunnus line, got {line!r}")
    supplier_business_id_ftr = m.group("bid")
    supplier_vat_id = m.group("vid")
    if supplier_business_id_ftr != _SUPPLIER_BUSINESS_ID:
        raise ParserLayoutError(
            f"unexpected supplier business id in footer: {supplier_business_id_ftr!r}"
        )
    if supplier_vat_id != _SUPPLIER_VAT_ID:
        raise ParserLayoutError(f"unexpected supplier VAT id in footer: {supplier_vat_id!r}")

    line = _take(totals_lines, tpos, "footer Maksuehto/Viitenumero line")
    m = _RE_TERMS.match(line)
    if not m:
        raise ParserLayoutError(f"expected footer Maksuehto/Viitenumero line, got {line!r}")
    payment_terms = m.group("terms")
    reference_value_ftr = m.group("ref")

    line = _take(totals_lines, tpos, "footer Pankkiyhteys/BIC line")
    m = _RE_BANK.match(line)
    if not m:
        raise ParserLayoutError(f"expected footer Pankkiyhteys/BIC line, got {line!r}")
    iban = m.group("iban")
    bic = m.group("bic")

    if tpos[0] != len(totals_lines):
        raise ParserLayoutError("unexpected extra content after the footer block")

    # --- cross-checks between the two places the reference number is printed ---
    if reference_value_hdr != reference_value_ftr:
        raise ParserLayoutError(
            f"reference value mismatch between header ({reference_value_hdr!r}) "
            f"and footer ({reference_value_ftr!r})"
        )

    # --- arithmetic reconciliation ---
    lines_total_sum = sum((Decimal(l["line_total"]) for l in parsed_lines), Decimal("0.00"))
    if lines_total_sum != Decimal(net):
        raise ParserLayoutError(
            f"sum of line totals ({lines_total_sum}) does not reconcile with the "
            f"printed net total ({net})"
        )

    distinct_rates = {l["vat_rate"] for l in parsed_lines}
    if distinct_rates != {vat_rate_summary}:
        raise ParserLayoutError(
            f"line VAT rates {sorted(distinct_rates)} do not match the single VAT "
            f"bracket printed in the totals block ({vat_rate_summary!r}); mixed-rate "
            "invoices were not observed in the induction set and are not handled"
        )

    expected_vat = (Decimal(net) * Decimal(vat_rate_summary) / Decimal("100")).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )
    if expected_vat != Decimal(vat_amount):
        raise ParserLayoutError(
            f"VAT amount does not reconcile: {net} x {vat_rate_summary}% = {expected_vat} "
            f"but printed VAT is {vat_amount}"
        )

    expected_gross = (Decimal(net) + Decimal(vat_amount)).quantize(Decimal("0.01"))
    if expected_gross != Decimal(gross):
        raise ParserLayoutError(
            f"gross does not reconcile: {net} + {vat_amount} = {expected_gross} but "
            f"printed Maksettava is {gross}"
        )

    doc_id = Path(pdf_path).stem

    return {
        "schema_version": "1.0",
        "doc_id": doc_id,
        "supplier": {
            "name": supplier_name,
            "street": supplier_street,
            "postcode": supplier_postcode,
            "city": supplier_city,
            "country": "FI",
            "vat_id": supplier_vat_id,
            "business_id": supplier_business_id_ftr,
        },
        "buyer": {
            "name": buyer_name,
            "street": buyer_street,
            "postcode": buyer_postcode,
            "city": buyer_city,
            "country": "FI",
            "vat_id": None,
            "business_id": buyer_business_id,
        },
        "invoice": {
            "number": invoice_number,
            "type": "invoice",
            "issue_date": issue_date,
            "supply_date": None,
            "due_date": due_date,
            "payment_terms": payment_terms,
            "currency": "EUR",
            "po_number": po_number,
            "reference_type": "viitenumero",
            "reference_value": reference_value_ftr,
            "original_invoice_number": None,
            "reverse_charge_mention": None,
        },
        "bank": {
            "iban": iban,
            "bic": bic,
            "bankgiro": None,
        },
        "lines": parsed_lines,
        "vat_summary": [
            {"rate": vat_rate_summary, "base": net, "amount": vat_amount},
        ],
        "totals": {
            "net": net,
            "vat": vat_amount,
            "gross": gross,
        },
    }


if __name__ == "__main__":
    import json
    import sys

    def _load_pairs(argv):
        if len(argv) == 1 and argv[0].lower().endswith(".json"):
            with open(argv[0], "r", encoding="utf-8") as fh:
                manifest = json.load(fh)
            return [(entry[0], entry[1]) for entry in manifest]
        if len(argv) % 2 != 0:
            raise SystemExit("expected an even number of arguments: pdf json pdf json ...")
        return [(argv[i], argv[i + 1]) for i in range(0, len(argv), 2)]

    def _deep_equal(a, b, path="$"):
        if isinstance(a, dict) and isinstance(b, dict):
            if a.keys() != b.keys():
                return False, f"{path}: key mismatch {sorted(a.keys())} vs {sorted(b.keys())}"
            for k in a:
                ok, msg = _deep_equal(a[k], b[k], f"{path}.{k}")
                if not ok:
                    return False, msg
            return True, ""
        if isinstance(a, list) and isinstance(b, list):
            if len(a) != len(b):
                return False, f"{path}: length mismatch {len(a)} vs {len(b)}"
            for i, (x, y) in enumerate(zip(a, b)):
                ok, msg = _deep_equal(x, y, f"{path}[{i}]")
                if not ok:
                    return False, msg
            return True, ""
        if a != b:
            return False, f"{path}: {a!r} != {b!r}"
        return True, ""

    pairs = _load_pairs(sys.argv[1:])
    if not pairs:
        raise SystemExit("no (pdf_path, accepted_parse_json_path) pairs given")

    n_pass = 0
    for pdf_path, json_path in pairs:
        label = Path(pdf_path).stem
        try:
            result = parse(pdf_path)
        except ParserLayoutError as exc:
            print(f"FAIL {label}: ParserLayoutError: {exc}")
            continue
        with open(json_path, "r", encoding="utf-8") as fh:
            expected = json.load(fh)
        ok, msg = _deep_equal(result, expected)
        if ok:
            print(f"PASS {label}")
            n_pass += 1
        else:
            print(f"FAIL {label}: {msg}")

    total = len(pairs)
    print(f"{n_pass}/{total} PASS")
    if n_pass != total:
        sys.exit(1)
