"""
Deterministic parser for supplier s4 (Moebeltyg Viskan AB).

Machine-generated by the overseer agent (Claude Sonnet 5) on 2026-07-03, following
`design/overseer_brief_v1.md`. Induced from 6 accepted LLM parses and their source
PDFs / pdfplumber text and word-coordinate dumps, doc_ids:
    2025-01_s4_01, 2025-01_s4_02, 2025-02_s4_01, 2025-02_s4_02,
    2025-03_s4_01, 2025-03_s4_02

Layout summary (verified against all 6 induction documents):
    - Single-column Swedish "faktura" letterhead. Page 1 top block, in strict
      line order (via pdfplumber page.extract_text()):
        Moebeltyg Viskan AB / Fakturanr <no> / Viskagatan 14 /
        Fakturadatum <date> / 504 62 Boras, Sverige / Foerfallodatum <date> /
        Org.nr 556123-4567 / Ordernummer <po> / Momsreg.nr SE556123456701 /
        KOEPARE / Pyoekkipaja Oy / Sorvaajankatu 11 / 15520 Lahti, Finland /
        Org.nr: 2417551-8 / Momsreg.nr: FI24175518 /
        "BENAEMNING ANTAL ENHET A-PRIS SUMMA" (line-item table header).
    - Line items: "<description> <qty> <unit> <unit_price> <line_total>",
      unit in {"m", "st"}, amounts in Swedish format (space thousands, comma
      decimals), no per-line VAT column.
    - If the item table spans more than one page, every page after the first
      opens with "Faktura <invoice_number> (forts.)" followed by a repeated
      "BENAEMNING ANTAL ENHET A-PRIS SUMMA" header row before more item rows
      (seen in 2025-03_s4_02, a 2-page invoice).
    - The final page ends with: Netto <amount> kr / Moms <pct> % <amount> kr /
      Att betala <amount> kr / the fixed Art. 138 reverse-charge sentence /
      a "BANKGIRO OCR BETALNINGSVILLKOR FOERFALLODATUM ATT BETALA" band header
      and one values row (bankgiro, OCR ref, "<N> dagar netto", due date,
      amount + "kr"). No IBAN/BIC anywhere on this supplier's layout.
    - Currency SEK throughout; VAT is always 0% (0.0) under the intra-EU
      Art. 138 exemption for this Swedish supplier -> Finnish buyer pair.

Anything that departs from the above (missing/reordered/renamed landmark,
unreconciled arithmetic, an unexpected extra page, a non-zero VAT rate, a
mismatched due date/gross between the header and the payment band, etc.)
raises ParserLayoutError so the router can fall back to the LLM path.
"""

from __future__ import annotations

import datetime
import json
import re
import sys
from decimal import Decimal
from pathlib import Path

import pdfplumber

SCHEMA_VERSION = "1.0"

SUPPLIER = {
    "name": "Möbeltyg Viskan AB",
    "street": "Viskagatan 14",
    "postcode": "504 62",
    "city": "Borås",
    "country": "SE",
    "vat_id": "SE556123456701",
    "business_id": "556123-4567",
}

BUYER = {
    "name": "Pyökkipaja Oy",
    "street": "Sorvaajankatu 11",
    "postcode": "15520",
    "city": "Lahti",
    "country": "FI",
    "vat_id": "FI24175518",
    "business_id": "2417551-8",
}

BANKGIRO = "5123-4567"

REVERSE_CHARGE_TEXT = (
    "Undantag från skatteplikt – unionsintern leverans (Intra-EU supply, Art. 138)"
)

# Swedish-formatted amount: 1-3 leading digits, then any number of
# space-grouped 3-digit blocks, then a comma and exactly 2 decimal digits.
# e.g. "391,52", "1 567,09", "34 040,29".
MONEY_RE = r"\d{1,3}(?: \d{3})*,\d{2}"


class ParserLayoutError(Exception):
    """Raised whenever the PDF does not match the induced s4 layout exactly."""


def _money(raw: str, label: str) -> str:
    """Canonicalise a verified Swedish money string to '.'-decimal, 2dp form."""
    if not re.fullmatch(MONEY_RE, raw):
        raise ParserLayoutError(f"{label}: not a valid Swedish amount: {raw!r}")
    normalised = raw.replace(" ", "").replace(",", ".")
    value = Decimal(normalised)
    if value != value.quantize(Decimal("0.01")):
        raise ParserLayoutError(f"{label}: amount not 2-decimal: {raw!r}")
    return str(value.quantize(Decimal("0.01")))


def _quantity(raw: str, label: str) -> str:
    if not re.fullmatch(r"\d+", raw):
        raise ParserLayoutError(f"{label}: not an integer quantity: {raw!r}")
    if len(raw) > 1 and raw[0] == "0":
        raise ParserLayoutError(f"{label}: quantity has a leading zero: {raw!r}")
    return raw


def _extract_page_lines(page, page_index: int) -> list[str]:
    text = page.extract_text()
    if text is None or text.strip() == "":
        raise ParserLayoutError(f"page {page_index + 1}: no extractable text")
    return [line.strip() for line in text.split("\n")]


class _LineCursor:
    """Walks a list of stripped text lines, matching expected landmarks in order."""

    def __init__(self, lines: list[str], page_label: str):
        self.lines = lines
        self.page_label = page_label
        self.pos = 0

    def peek(self) -> str | None:
        if self.pos >= len(self.lines):
            return None
        return self.lines[self.pos]

    def expect(self, pattern: str, label: str) -> re.Match:
        line = self.peek()
        if line is None:
            raise ParserLayoutError(
                f"{self.page_label}: expected {label} but ran out of lines"
            )
        m = re.match(pattern, line)
        if not m:
            raise ParserLayoutError(
                f"{self.page_label}: expected {label}, got {line!r}"
            )
        self.pos += 1
        return m

    def expect_literal(self, literal: str, label: str) -> None:
        self.expect(r"^" + re.escape(literal) + r"$", label)


TABLE_HEADER_RE = r"^BENÄMNING\s+ANTAL\s+ENHET\s+À-PRIS\s+SUMMA$"
ITEM_ROW_RE = (
    r"^(?P<desc>.+?)\s+(?P<qty>\d+)\s+(?P<unit>m|st)\s+"
    rf"(?P<unit_price>{MONEY_RE})\s+(?P<line_total>{MONEY_RE})$"
)
NETTO_RE = rf"^Netto\s+({MONEY_RE})\s+kr$"
MOMS_RE = rf"^Moms\s+(\d+)\s+%\s+({MONEY_RE})\s+kr$"
ATT_BETALA_RE = rf"^Att betala\s+({MONEY_RE})\s+kr$"
BANK_HEADER_RE = (
    r"^BANKGIRO\s+OCR\s+BETALNINGSVILLKOR\s+FÖRFALLODATUM\s+ATT BETALA$"
)
BANK_VALUES_RE = (
    r"^(?P<bankgiro>\d{4}-\d{4})\s+(?P<ocr>\d+)\s+"
    r"(?P<terms>\d+ dagar netto)\s+(?P<due>\d{4}-\d{2}-\d{2})\s+"
    rf"(?P<amt>{MONEY_RE})\s+kr$"
)


def _parse_item_row(line: str) -> dict:
    m = re.match(ITEM_ROW_RE, line)
    if not m:
        raise ParserLayoutError(f"unrecognised line-item row: {line!r}")
    desc = m.group("desc")
    qty = _quantity(m.group("qty"), f"line-item {desc!r} quantity")
    unit_price = _money(m.group("unit_price"), f"line-item {desc!r} unit_price")
    line_total = _money(m.group("line_total"), f"line-item {desc!r} line_total")
    expected_total = (Decimal(qty) * Decimal(unit_price)).quantize(Decimal("0.01"))
    if expected_total != Decimal(line_total):
        raise ParserLayoutError(
            f"line-item {desc!r}: {qty} x {unit_price} = {expected_total}, "
            f"but printed line_total is {line_total}"
        )
    return {
        "description": desc,
        "quantity": qty,
        "unit": m.group("unit"),
        "unit_price": unit_price,
        "vat_rate": "0.0",
        "line_total": line_total,
    }


def parse(pdf_path: str) -> dict:
    doc_id = Path(pdf_path).stem

    with pdfplumber.open(pdf_path) as pdf:
        pages = pdf.pages
        if len(pages) == 0:
            raise ParserLayoutError("PDF has no pages")

        pages_lines = [
            _extract_page_lines(page, i) for i, page in enumerate(pages)
        ]

        # ---- Page 1: header block -------------------------------------
        cur = _LineCursor(pages_lines[0], "page 1")
        cur.expect_literal(SUPPLIER["name"], "supplier name")
        invoice_number = cur.expect(
            r"^Fakturanr\s+(\S+)$", "invoice number"
        ).group(1)
        cur.expect_literal(SUPPLIER["street"], "supplier street")
        issue_date = cur.expect(
            r"^Fakturadatum\s+(\d{4}-\d{2}-\d{2})$", "issue date"
        ).group(1)
        cur.expect_literal(
            f"{SUPPLIER['postcode']} {SUPPLIER['city']}, Sverige",
            "supplier city/country line",
        )
        due_date_header = cur.expect(
            r"^Förfallodatum\s+(\d{4}-\d{2}-\d{2})$", "due date"
        ).group(1)
        cur.expect_literal(f"Org.nr {SUPPLIER['business_id']}", "supplier business id")
        po_number = cur.expect(r"^Ordernummer\s+(\S+)$", "PO number").group(1)
        cur.expect_literal(f"Momsreg.nr {SUPPLIER['vat_id']}", "supplier VAT id")
        cur.expect_literal("KÖPARE", "KÖPARE marker")
        cur.expect_literal(BUYER["name"], "buyer name")
        cur.expect_literal(BUYER["street"], "buyer street")
        cur.expect_literal(
            f"{BUYER['postcode']} {BUYER['city']}, Finland",
            "buyer city/country line",
        )
        cur.expect_literal(f"Org.nr: {BUYER['business_id']}", "buyer business id")
        cur.expect_literal(f"Momsreg.nr: {BUYER['vat_id']}", "buyer VAT id")
        cur.expect(TABLE_HEADER_RE, "line-item table header")

        # ---- Line items, possibly spanning several pages ---------------
        lines_out: list[dict] = []
        n_pages = len(pages_lines)
        footer_lines: list[str] | None = None

        for page_i in range(n_pages):
            if page_i == 0:
                idx = cur.pos
                plines = pages_lines[0]
            else:
                plines = pages_lines[page_i]
                page_cur = _LineCursor(plines, f"page {page_i + 1}")
                page_cur.expect(
                    r"^Faktura\s+" + re.escape(invoice_number) + r"\s+\(forts\.\)$",
                    "continuation marker",
                )
                page_cur.expect(TABLE_HEADER_RE, "repeated line-item table header")
                idx = page_cur.pos

            is_last_page = page_i == n_pages - 1
            reached_netto = False
            while idx < len(plines):
                line = plines[idx]
                if re.match(NETTO_RE, line):
                    reached_netto = True
                    break
                lines_out.append(_parse_item_row(line))
                idx += 1

            if is_last_page:
                if not reached_netto:
                    raise ParserLayoutError(
                        f"page {page_i + 1}: reached end of page without finding "
                        f"the 'Netto' totals line"
                    )
                footer_lines = plines[idx:]
            else:
                if reached_netto:
                    raise ParserLayoutError(
                        f"page {page_i + 1}: found 'Netto' totals line on a "
                        f"non-final page (unexpected extra page structure)"
                    )

        if not lines_out:
            raise ParserLayoutError("no line items found")
        assert footer_lines is not None

        # ---- Footer / totals block (final page only) -------------------
        fcur = _LineCursor(footer_lines, "footer")
        m_netto = fcur.expect(NETTO_RE, "Netto line")
        net = _money(m_netto.group(1), "Netto total")

        m_moms = fcur.expect(MOMS_RE, "Moms line")
        if m_moms.group(1) != "0":
            raise ParserLayoutError(
                f"unexpected non-zero VAT rate on Moms line: {m_moms.group(1)}%"
            )
        vat_amount = _money(m_moms.group(2), "Moms amount")
        if vat_amount != "0.00":
            raise ParserLayoutError(
                f"Moms is 0% but printed amount is not 0.00: {vat_amount}"
            )

        m_att = fcur.expect(ATT_BETALA_RE, "Att betala line")
        gross = _money(m_att.group(1), "Att betala total")

        fcur.expect_literal(REVERSE_CHARGE_TEXT, "reverse-charge exemption sentence")
        fcur.expect(BANK_HEADER_RE, "bank/payment band header")

        m_bank = fcur.expect(BANK_VALUES_RE, "bank/payment band values")
        bankgiro = m_bank.group("bankgiro")
        if bankgiro != BANKGIRO:
            raise ParserLayoutError(
                f"unexpected bankgiro number: {bankgiro} (expected {BANKGIRO})"
            )
        ocr_reference = m_bank.group("ocr")
        payment_terms = m_bank.group("terms")
        due_date_band = m_bank.group("due")
        band_amount = _money(m_bank.group("amt"), "bank band amount")

        # ---- Cross-field reconciliation --------------------------------
        if due_date_band != due_date_header:
            raise ParserLayoutError(
                f"due date mismatch: header says {due_date_header}, "
                f"payment band says {due_date_band}"
            )
        if band_amount != gross:
            raise ParserLayoutError(
                f"amount mismatch: Att betala is {gross}, "
                f"payment band amount is {band_amount}"
            )

        # payment_terms was captured via BANK_VALUES_RE's "terms" group, which
        # already anchors it to the "<digits> dagar netto" shape.
        term_days = int(payment_terms.split(" ", 1)[0])
        issue_dt = datetime.date.fromisoformat(issue_date)
        due_dt = datetime.date.fromisoformat(due_date_header)
        if (due_dt - issue_dt).days != term_days:
            raise ParserLayoutError(
                f"payment terms say {term_days} days, but due_date - issue_date "
                f"= {(due_dt - issue_dt).days} days"
            )

        lines_total = sum(Decimal(l["line_total"]) for l in lines_out)
        if lines_total != Decimal(net):
            raise ParserLayoutError(
                f"line items sum to {lines_total}, but printed Netto is {net}"
            )
        if (Decimal(net) + Decimal(vat_amount)) != Decimal(gross):
            raise ParserLayoutError(
                f"net ({net}) + vat ({vat_amount}) != gross ({gross})"
            )

        # Any remaining non-blank lines after the payment band are an
        # unexpected extra layout element on this supplier's invoice.
        rest = footer_lines[fcur.pos :]
        if any(l.strip() for l in rest):
            raise ParserLayoutError(
                f"unexpected trailing content after payment band: {rest!r}"
            )

    return {
        "schema_version": SCHEMA_VERSION,
        "doc_id": doc_id,
        "supplier": dict(SUPPLIER),
        "buyer": dict(BUYER),
        "invoice": {
            "number": invoice_number,
            "type": "invoice",
            "issue_date": issue_date,
            "supply_date": None,
            "due_date": due_date_header,
            "payment_terms": payment_terms,
            "currency": "SEK",
            "po_number": po_number,
            "reference_type": "ocr",
            "reference_value": ocr_reference,
            "original_invoice_number": None,
            "reverse_charge_mention": REVERSE_CHARGE_TEXT,
        },
        "bank": {
            "iban": None,
            "bic": None,
            "bankgiro": bankgiro,
        },
        "lines": lines_out,
        "vat_summary": [
            {"rate": "0.0", "base": net, "amount": vat_amount},
        ],
        "totals": {
            "net": net,
            "vat": vat_amount,
            "gross": gross,
        },
    }


def _run_self_test(pairs: list[tuple[str, str]]) -> int:
    n_fail = 0
    for pdf_path, json_path in pairs:
        doc_id = Path(pdf_path).stem
        try:
            result = parse(pdf_path)
        except ParserLayoutError as exc:
            print(f"FAIL {doc_id}: ParserLayoutError: {exc}")
            n_fail += 1
            continue
        with open(json_path, "r", encoding="utf-8") as f:
            expected = json.load(f)
        if result == expected:
            print(f"PASS {doc_id}")
        else:
            print(f"FAIL {doc_id}: parsed output does not match accepted parse")
            for key in sorted(set(result) | set(expected)):
                if result.get(key) != expected.get(key):
                    print(f"  field {key!r} differs:")
                    print(f"    parsed:   {result.get(key)!r}")
                    print(f"    accepted: {expected.get(key)!r}")
            n_fail += 1
    total = len(pairs)
    print(f"\n{total - n_fail}/{total} PASS")
    return 1 if n_fail else 0


def _load_pairs_from_args(argv: list[str]) -> list[tuple[str, str]]:
    if len(argv) == 1 and argv[0].lower().endswith(".json"):
        with open(argv[0], "r", encoding="utf-8") as f:
            manifest = json.load(f)
        pairs = []
        for entry in manifest:
            if isinstance(entry, dict):
                pairs.append((entry["pdf"], entry["json"]))
            else:
                pdf_path, json_path = entry
                pairs.append((pdf_path, json_path))
        return pairs
    if len(argv) % 2 != 0:
        raise SystemExit(
            "expected an even number of (pdf_path, json_path) arguments, "
            "or a single manifest .json path"
        )
    return [(argv[i], argv[i + 1]) for i in range(0, len(argv), 2)]


if __name__ == "__main__":
    arg_pairs = _load_pairs_from_args(sys.argv[1:])
    if not arg_pairs:
        print(
            "usage: parser_s4.py (pdf_path json_path)... | manifest.json",
            file=sys.stderr,
        )
        sys.exit(2)
    sys.exit(_run_self_test(arg_pairs))
