"""Deterministic parser for supplier s8 -- Tyokalu-Tiira Oy.

Machine-generated by the overseer agent (Claude Sonnet 5, claude-sonnet-5),
2026-07-03, from N=6 accepted LLM parses and their source documents. This
module replaces the LLM path for this supplier's invoices going forward.

Induced from (base dir "Case Studies/03 Invoices/"):
  data/runs/llm_parses/2025-01_s8_01.json  + data/documents/2025-01_s8_01.pdf
  data/runs/llm_parses/2025-01_s8_02.json  + data/documents/2025-01_s8_02.pdf
  data/runs/llm_parses/2025-02_s8_01.json  + data/documents/2025-02_s8_01.pdf
  data/runs/llm_parses/2025-02_s8_02.json  + data/documents/2025-02_s8_02.pdf
  data/runs/llm_parses/2025-03_s8_01.json  + data/documents/2025-03_s8_01.pdf
  data/runs/llm_parses/2025-03_s8_02.json  + data/documents/2025-03_s8_02.pdf
(plus each doc's plain-text and word-coordinate pdfplumber dumps under
data/runs/text_layers/, used only to study the layout -- not read at run time).

Layout summary (single-page Finnish MRO/tools invoice, one fixed template):
  Line  0: supplier name, alone                       "Tyokalu-Tiira Oy"
  Line  1: "Lasku T-NNNN"                              invoice number
  Line  2: "<street> Laskun paiva DD.MM.YYYY"          (two header columns
                                                         merged onto one text
                                                         row by pdfplumber's
                                                         default y-tolerance)
  Line  3: "<postcode> <city>"                         supplier address
  Line  4: "Erapaiva DD.MM.YYYY"                       due date
  Line  5: "Y-tunnus: NNNNNNN-N"                        supplier business id
  Line  6: "Viitenumero NNNNNNNN"                       reference (viitenumero)
  Line  7: "Tilausnumero PO-YYYY-NNN"                   PO number
  Line  8: "OSTAJA"
  Line  9: buyer name, alone
  Line 10: buyer street, alone
  Line 11: "<postcode> <city>"                          buyer address
  Line 12: "Y-tunnus: NNNNNNN-N"                        buyer business id
  Line 13: "NIMIKE MAARA YKSIKKO A-HINTA ALV % YHTEENSA" column header
  Lines 14..: one row per line item (count varies, 3-11 observed):
             "<description> <qty> kpl <unit_price>,dd 25,5 <line_total>,dd"
             (unit is always "kpl"; VAT rate is always 25,5 for this
             supplier -- both are literal anchors in the row pattern, not
             a generic match, per the induction notes)
  Then, immediately after the last item row:
             "Veroton yhteensa <net> €"
             "ALV 25,5 % <vat> €"
             "Maksettava <gross> €"
             "Y-tunnus NNNNNNN-N -- ALV-tunnus FINNNNNNNN"
             "Maksuehto: <terms> -- Viitenumero: NNNNNNNN"
             "Pankkiyhteys: FINN...  BIC: XXXXXXXX"
  No further lines after that (single page, nothing else on it).

Fields with no textual anchor anywhere on the document (not printed at all
in this layout) are filled with the constant observed in all 6 induction
documents rather than parsed: supplier/buyer country ("FI" -- inferred from
the FI-prefixed VAT id, IBAN and 5-digit Finnish postcodes, never printed as
its own token), buyer.vat_id, bank.bankgiro, invoice.supply_date,
invoice.original_invoice_number, invoice.reverse_charge_mention (all None).

Fail-loud philosophy: every literal label, every fixed line position, the
"kpl" unit and the "25,5" VAT rate are hard-anchored in the regexes below.
Any reordering, renamed label, extra/missing line, non-kpl unit, non-25,5
VAT rate, multi-page document, or arithmetic that does not reconcile raises
ParserLayoutError -- this hands the document back to the LLM path rather
than emitting a silently wrong record.
"""

import re
import sys
import json
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from datetime import datetime
from pathlib import Path

import pdfplumber

__all__ = ["parse", "ParserLayoutError"]


class ParserLayoutError(Exception):
    """Raised the moment this document's layout deviates from the induced
    Tyokalu-Tiira Oy template in any way. An exception here is the intended
    success mode of the overseer system (it routes the document back to the
    LLM path) -- never suppress it or fall back to a best-effort parse."""


# ---------------------------------------------------------------------------
# Constants observed as invariant across all 6 induction documents.
# ---------------------------------------------------------------------------

SUPPLIER_NAME = "Työkalu-Tiira Oy"
SUPPLIER_BUSINESS_ID = "2277889-2"
SUPPLIER_COUNTRY = "FI"
BUYER_COUNTRY = "FI"
HEADER_ROW = "NIMIKE MÄÄRÄ YKSIKKÖ A-HINTA ALV % YHTEENSÄ"
EXPECTED_VAT_RATE_CANON = "25.5"

# ---------------------------------------------------------------------------
# Line-level patterns, anchored to the exact fixed-position label text.
# ---------------------------------------------------------------------------

RE_LASKU = re.compile(r"^Lasku (T-\d{4})$")
RE_STREET_AND_ISSUE_DATE = re.compile(
    r"^(?P<street>.+?) Laskun päivä (?P<date>\d{2}\.\d{2}\.\d{4})$"
)
RE_POSTCODE_CITY = re.compile(r"^(?P<postcode>\d{5}) (?P<city>.+)$")
RE_ERAPAIVA = re.compile(r"^Eräpäivä (?P<date>\d{2}\.\d{2}\.\d{4})$")
RE_YTUNNUS_COLON = re.compile(r"^Y-tunnus: (?P<bid>\d{7}-\d)$")
RE_VIITENUMERO = re.compile(r"^Viitenumero (?P<ref>\d+)$")
RE_TILAUSNUMERO = re.compile(r"^Tilausnumero (?P<po>PO-\d{4}-\d{3})$")

RE_ITEM = re.compile(
    r"^(?P<desc>.+?) (?P<qty>\d+) kpl (?P<price>\d+,\d{2}) 25,5 (?P<total>\d+,\d{2})$"
)

RE_VEROTON = re.compile(r"^Veroton yhteensä (?P<amount>[\d ]+,\d{2}) €$")
RE_ALV = re.compile(r"^ALV 25,5 % (?P<amount>[\d ]+,\d{2}) €$")
RE_MAKSETTAVA = re.compile(r"^Maksettava (?P<amount>[\d ]+,\d{2}) €$")
RE_FOOTER_IDS = re.compile(
    r"^Y-tunnus (?P<bid>\d{7}-\d) -- ALV-tunnus (?P<vat>FI\d+)$"
)
RE_FOOTER_TERMS = re.compile(
    r"^Maksuehto: (?P<terms>.+?) -- Viitenumero: (?P<ref>\d+)$"
)
RE_FOOTER_BANK = re.compile(
    r"^Pankkiyhteys: (?P<iban>FI\d+) BIC: (?P<bic>[A-Z0-9]{8,11})$"
)


# ---------------------------------------------------------------------------
# Small canonicalisation helpers -- each raises ParserLayoutError on any
# value that does not fit the canonical shape, rather than guessing.
# ---------------------------------------------------------------------------

def _money(raw, ctx):
    compact = raw.replace(" ", "").replace(" ", "")
    if not re.fullmatch(r"\d+,\d{2}", compact):
        raise ParserLayoutError(f"{ctx}: {raw!r} is not a recognisable money amount")
    try:
        value = Decimal(compact.replace(",", "."))
    except InvalidOperation as exc:
        raise ParserLayoutError(f"{ctx}: could not parse money amount {raw!r}") from exc
    return f"{value:.2f}"


def _qty(raw, ctx):
    if not re.fullmatch(r"\d+", raw):
        raise ParserLayoutError(f"{ctx}: {raw!r} is not a recognisable integer quantity")
    return str(int(raw))


def _iso_date(raw, ctx):
    try:
        return datetime.strptime(raw, "%d.%m.%Y").strftime("%Y-%m-%d")
    except ValueError as exc:
        raise ParserLayoutError(f"{ctx}: {raw!r} is not a valid DD.MM.YYYY date") from exc


def _decimal(s):
    return Decimal(s)


# ---------------------------------------------------------------------------
# Main entry point.
# ---------------------------------------------------------------------------

def parse(pdf_path: str) -> dict:
    with pdfplumber.open(pdf_path) as pdf:
        if len(pdf.pages) != 1:
            raise ParserLayoutError(
                f"expected exactly 1 page, found {len(pdf.pages)} -- multi-page "
                "layout not observed in the induction set"
            )
        text = pdf.pages[0].extract_text()

    if not text:
        raise ParserLayoutError("no extractable text on page 1")

    lines = [ln for ln in text.split("\n") if ln.strip() != ""]

    if len(lines) < 14:
        raise ParserLayoutError(
            f"expected at least 14 header/buyer lines before the item table, "
            f"found only {len(lines)} non-blank lines total"
        )

    # --- supplier identity block (lines 0-7) ---------------------------------
    if lines[0].strip() != SUPPLIER_NAME:
        raise ParserLayoutError(
            f"line 0: expected supplier name {SUPPLIER_NAME!r}, found {lines[0]!r} "
            "-- this parser is specific to Tyokalu-Tiira Oy's layout"
        )
    supplier_name = lines[0].strip()

    m = RE_LASKU.match(lines[1])
    if not m:
        raise ParserLayoutError(f"line 1: expected 'Lasku T-NNNN', found {lines[1]!r}")
    invoice_number = m.group(1)

    m = RE_STREET_AND_ISSUE_DATE.match(lines[2])
    if not m:
        raise ParserLayoutError(
            f"line 2: expected '<street> Laskun päivä DD.MM.YYYY', found {lines[2]!r}"
        )
    supplier_street = m.group("street").strip()
    issue_date = _iso_date(m.group("date"), "line 2 issue date")

    m = RE_POSTCODE_CITY.match(lines[3])
    if not m:
        raise ParserLayoutError(f"line 3: expected '<postcode> <city>', found {lines[3]!r}")
    supplier_postcode, supplier_city = m.group("postcode"), m.group("city").strip()

    m = RE_ERAPAIVA.match(lines[4])
    if not m:
        raise ParserLayoutError(f"line 4: expected 'Eräpäivä DD.MM.YYYY', found {lines[4]!r}")
    due_date = _iso_date(m.group("date"), "line 4 due date")

    m = RE_YTUNNUS_COLON.match(lines[5])
    if not m:
        raise ParserLayoutError(f"line 5: expected 'Y-tunnus: NNNNNNN-N', found {lines[5]!r}")
    supplier_business_id = m.group("bid")
    if supplier_business_id != SUPPLIER_BUSINESS_ID:
        raise ParserLayoutError(
            f"line 5: expected supplier business id {SUPPLIER_BUSINESS_ID!r}, "
            f"found {supplier_business_id!r}"
        )

    m = RE_VIITENUMERO.match(lines[6])
    if not m:
        raise ParserLayoutError(f"line 6: expected 'Viitenumero NNNNNNNN', found {lines[6]!r}")
    reference_value_header = m.group("ref")

    m = RE_TILAUSNUMERO.match(lines[7])
    if not m:
        raise ParserLayoutError(f"line 7: expected 'Tilausnumero PO-YYYY-NNN', found {lines[7]!r}")
    po_number = m.group("po")

    # --- buyer block (lines 8-12) --------------------------------------------
    if lines[8].strip() != "OSTAJA":
        raise ParserLayoutError(f"line 8: expected 'OSTAJA', found {lines[8]!r}")

    buyer_name = lines[9].strip()
    if not buyer_name:
        raise ParserLayoutError("line 9: expected buyer name, found blank line")
    buyer_street = lines[10].strip()
    if not buyer_street:
        raise ParserLayoutError("line 10: expected buyer street, found blank line")

    m = RE_POSTCODE_CITY.match(lines[11])
    if not m:
        raise ParserLayoutError(f"line 11: expected '<postcode> <city>', found {lines[11]!r}")
    buyer_postcode, buyer_city = m.group("postcode"), m.group("city").strip()

    m = RE_YTUNNUS_COLON.match(lines[12])
    if not m:
        raise ParserLayoutError(f"line 12: expected 'Y-tunnus: NNNNNNN-N', found {lines[12]!r}")
    buyer_business_id = m.group("bid")

    # --- item table header (line 13) -----------------------------------------
    if lines[13].strip() != HEADER_ROW:
        raise ParserLayoutError(
            f"line 13: expected column header {HEADER_ROW!r}, found {lines[13]!r}"
        )

    # --- item rows: everything up to the 'Veroton yhteensa' line -------------
    idx_veroton = None
    for i in range(14, len(lines)):
        if lines[i].startswith("Veroton yhteensä"):
            idx_veroton = i
            break
    if idx_veroton is None:
        raise ParserLayoutError("could not find the 'Veroton yhteensä' totals line")
    if idx_veroton == 14:
        raise ParserLayoutError("no item rows found between the header and the totals block")

    item_lines = lines[14:idx_veroton]
    parsed_lines = []
    for i, raw_line in enumerate(item_lines):
        m = RE_ITEM.match(raw_line)
        if not m:
            raise ParserLayoutError(
                f"item row {i} (line {14 + i}): does not match the expected "
                f"'<description> <qty> kpl <price> 25,5 <total>' pattern: {raw_line!r}"
            )
        desc = m.group("desc").strip()
        if not desc:
            raise ParserLayoutError(f"item row {i}: empty description in {raw_line!r}")
        qty = _qty(m.group("qty"), f"item row {i} quantity")
        price = _money(m.group("price"), f"item row {i} unit price")
        total = _money(m.group("total"), f"item row {i} line total")

        computed_total = (_decimal(qty) * _decimal(price)).quantize(
            Decimal("0.01"), rounding=ROUND_HALF_UP
        )
        if computed_total != _decimal(total):
            raise ParserLayoutError(
                f"item row {i} ({desc!r}): {qty} x {price} = {computed_total}, "
                f"does not reconcile to printed line total {total}"
            )

        parsed_lines.append(
            {
                "description": desc,
                "quantity": qty,
                "unit": "kpl",
                "unit_price": price,
                "vat_rate": EXPECTED_VAT_RATE_CANON,
                "line_total": total,
            }
        )

    # --- totals block (idx_veroton .. idx_veroton+5) --------------------------
    required_tail = idx_veroton + 6
    if len(lines) != required_tail:
        raise ParserLayoutError(
            f"expected exactly 6 lines after the item table (totals + footer), "
            f"found {len(lines) - idx_veroton} -- possible extra/missing trailing content"
        )

    m = RE_VEROTON.match(lines[idx_veroton])
    if not m:
        raise ParserLayoutError(f"expected 'Veroton yhteensä <amount> €', found {lines[idx_veroton]!r}")
    net = _money(m.group("amount"), "net total")

    m = RE_ALV.match(lines[idx_veroton + 1])
    if not m:
        raise ParserLayoutError(f"expected 'ALV 25,5 % <amount> €', found {lines[idx_veroton + 1]!r}")
    vat = _money(m.group("amount"), "VAT amount")

    m = RE_MAKSETTAVA.match(lines[idx_veroton + 2])
    if not m:
        raise ParserLayoutError(f"expected 'Maksettava <amount> €', found {lines[idx_veroton + 2]!r}")
    gross = _money(m.group("amount"), "gross total")

    m = RE_FOOTER_IDS.match(lines[idx_veroton + 3])
    if not m:
        raise ParserLayoutError(
            f"expected 'Y-tunnus NNNNNNN-N -- ALV-tunnus FINNNNNNNN', found {lines[idx_veroton + 3]!r}"
        )
    footer_business_id, supplier_vat_id = m.group("bid"), m.group("vat")
    if footer_business_id != supplier_business_id:
        raise ParserLayoutError(
            f"supplier business id mismatch: header {supplier_business_id!r} vs "
            f"footer {footer_business_id!r}"
        )
    if supplier_vat_id != "FI" + supplier_business_id.replace("-", ""):
        raise ParserLayoutError(
            f"supplier VAT id {supplier_vat_id!r} does not derive from business id "
            f"{supplier_business_id!r} as FI + digits"
        )

    m = RE_FOOTER_TERMS.match(lines[idx_veroton + 4])
    if not m:
        raise ParserLayoutError(
            f"expected 'Maksuehto: <terms> -- Viitenumero: NNNNNNNN', found {lines[idx_veroton + 4]!r}"
        )
    payment_terms = m.group("terms").strip()
    reference_value_footer = m.group("ref")
    if reference_value_footer != reference_value_header:
        raise ParserLayoutError(
            f"viitenumero mismatch: header {reference_value_header!r} vs "
            f"footer {reference_value_footer!r}"
        )

    m = RE_FOOTER_BANK.match(lines[idx_veroton + 5])
    if not m:
        raise ParserLayoutError(
            f"expected 'Pankkiyhteys: FI... BIC: XXXXXXXX', found {lines[idx_veroton + 5]!r}"
        )
    iban, bic = m.group("iban"), m.group("bic")

    # --- arithmetic reconciliation --------------------------------------------
    sum_lines = sum(_decimal(pl["line_total"]) for pl in parsed_lines)
    net_dec = _decimal(net)
    vat_dec = _decimal(vat)
    gross_dec = _decimal(gross)

    if sum_lines != net_dec:
        raise ParserLayoutError(
            f"line totals sum to {sum_lines}, printed net total is {net_dec} -- does not reconcile"
        )
    if net_dec + vat_dec != gross_dec:
        raise ParserLayoutError(
            f"net {net_dec} + VAT {vat_dec} = {net_dec + vat_dec}, printed gross is {gross_dec} "
            "-- does not reconcile"
        )
    expected_vat = (net_dec * Decimal("0.255")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    if expected_vat != vat_dec:
        raise ParserLayoutError(
            f"net {net_dec} x 25.5% rounds to {expected_vat}, printed VAT is {vat_dec} "
            "-- does not reconcile"
        )

    doc_id = Path(pdf_path).stem

    return {
        "schema_version": "1.0",
        "doc_id": doc_id,
        "supplier": {
            "name": supplier_name,
            "street": supplier_street,
            "postcode": supplier_postcode,
            "city": supplier_city,
            "country": SUPPLIER_COUNTRY,
            "vat_id": supplier_vat_id,
            "business_id": supplier_business_id,
        },
        "buyer": {
            "name": buyer_name,
            "street": buyer_street,
            "postcode": buyer_postcode,
            "city": buyer_city,
            "country": BUYER_COUNTRY,
            "vat_id": None,
            "business_id": buyer_business_id,
        },
        "invoice": {
            "number": invoice_number,
            "type": "invoice",
            "issue_date": issue_date,
            "supply_date": None,
            "due_date": due_date,
            "payment_terms": payment_terms,
            "currency": "EUR",
            "po_number": po_number,
            "reference_type": "viitenumero",
            "reference_value": reference_value_header,
            "original_invoice_number": None,
            "reverse_charge_mention": None,
        },
        "bank": {
            "iban": iban,
            "bic": bic,
            "bankgiro": None,
        },
        "lines": parsed_lines,
        "vat_summary": [
            {"rate": EXPECTED_VAT_RATE_CANON, "base": net, "amount": vat}
        ],
        "totals": {"net": net, "vat": vat, "gross": gross},
    }


# ---------------------------------------------------------------------------
# Self-test: parse each induction document and deep-compare to its accepted
# LLM parse. Usage:
#   python parser_s8.py                              (uses the 6 induction
#                                                       docs via relative paths)
#   python parser_s8.py manifest.json                 ([[pdf, json], ...] or
#                                                       [{"pdf":..,"json":..}, ...])
#   python parser_s8.py a.pdf a.json b.pdf b.json ...  (explicit pairs)
# ---------------------------------------------------------------------------

def _default_pairs():
    base = Path(__file__).resolve().parents[2]  # .../03 Invoices
    doc_ids = [
        "2025-01_s8_01",
        "2025-01_s8_02",
        "2025-02_s8_01",
        "2025-02_s8_02",
        "2025-03_s8_01",
        "2025-03_s8_02",
    ]
    pairs = []
    for doc_id in doc_ids:
        pdf_path = base / "data" / "documents" / f"{doc_id}.pdf"
        json_path = base / "data" / "runs" / "llm_parses" / f"{doc_id}.json"
        pairs.append((str(pdf_path), str(json_path)))
    return pairs


def _load_manifest_pairs(argv):
    if len(argv) == 1 and argv[0].lower().endswith(".json"):
        with open(argv[0], "r", encoding="utf-8") as f:
            manifest = json.load(f)
        pairs = []
        for entry in manifest:
            if isinstance(entry, dict):
                pairs.append((entry["pdf"], entry["json"]))
            else:
                pdf_path, json_path = entry
                pairs.append((pdf_path, json_path))
        return pairs
    if len(argv) % 2 != 0:
        raise SystemExit("expected an even number of (pdf, json) arguments")
    return [(argv[i], argv[i + 1]) for i in range(0, len(argv), 2)]


def _run_self_test(pairs):
    all_ok = True
    for pdf_path, json_path in pairs:
        label = Path(pdf_path).stem
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                expected = json.load(f)
            actual = parse(pdf_path)
            if actual == expected:
                print(f"PASS {label}")
            else:
                all_ok = False
                print(f"FAIL {label}: parsed output does not match accepted parse")
                for key in expected:
                    if actual.get(key) != expected.get(key):
                        print(f"       field {key!r} differs:")
                        print(f"         expected: {expected.get(key)!r}")
                        print(f"         actual:   {actual.get(key)!r}")
        except ParserLayoutError as exc:
            all_ok = False
            print(f"FAIL {label}: ParserLayoutError: {exc}")
        except Exception as exc:  # noqa: BLE001 -- self-test wants to report, not crash
            all_ok = False
            print(f"FAIL {label}: unexpected {type(exc).__name__}: {exc}")
    return all_ok


if __name__ == "__main__":
    argv = sys.argv[1:]
    test_pairs = _load_manifest_pairs(argv) if argv else _default_pairs()
    ok = _run_self_test(test_pairs)
    sys.exit(0 if ok else 1)
