"""
Deterministic parser for supplier s7 (Lounastupa Helmi Oy).

Machine-generated by the overseer agent (Claude Sonnet 5), 2026-07-03, per
`design/overseer_brief_v1.md` v1.0.

Induced exclusively from the 6 accepted LLM parses / PDFs / pdfplumber text
and word-coordinate dumps for doc_ids:
    2025-01_s7_01, 2025-02_s7_01, 2025-03_s7_01,
    2025-04_s7_01, 2025-05_s7_01, 2025-06_s7_01

Layout summary (see report for full landmark list): a one-page Finnish
canteen invoice ("Lasku") with a fixed sequence of labelled lines
(Lasku / Laskun päivä / Eräpäivä / Ostaja ... / Viitenumero / item table
header / exactly one item row / Veroton yhteensä / ALV / Maksettava /
footer line / BIC code), always 14 % VAT, one "Henkilöstöruokailu, <kuukausi>
<year>" line item per invoice (quantity in "ateria"), payment terms always
"<N> pv netto" with the due date exactly N days after the issue date.

This module raises ParserLayoutError the moment anything it relies on is
missing, reordered, renamed, or arithmetically inconsistent. An exception is
the intended success mode for an unrecognised layout (the router falls back
to the LLM path); this parser never guesses.
"""

import json
import re
import sys
from datetime import date, timedelta
from decimal import ROUND_HALF_EVEN, Decimal
from pathlib import Path

import pdfplumber

SCHEMA_VERSION = "1.0"

# Supplier identity is fixed for this layout; it is still read off the page
# (not hard-coded into the record) and cross-checked against the printed
# Y-tunnus / ALV-tunnus for consistency.
FI_MONTHS = {
    "tammikuu": 1,
    "helmikuu": 2,
    "maaliskuu": 3,
    "huhtikuu": 4,
    "toukokuu": 5,
    "kesäkuu": 6,
    "heinäkuu": 7,
    "elokuu": 8,
    "syyskuu": 9,
    "lokakuu": 10,
    "marraskuu": 11,
    "joulukuu": 12,
}
_MONTH_ALTERNATION = "|".join(FI_MONTHS.keys())

SUPPLIER_NAME_RE = re.compile(r"^(?P<name>\S.*\S|\S)$")
SUPPLIER_ADDR_RE = re.compile(
    r"^(?P<street>[^,]+),\s*(?P<postcode>\d{5})\s+(?P<city>[^·]+?)\s*"
    r"·\s*Y-tunnus\s+(?P<business_id>[\w-]+)$"
)
INVOICE_NUMBER_RE = re.compile(r"^Lasku\s+(?P<number>\d+)$")
ISSUE_DATE_RE = re.compile(r"^Laskun päivä\s+(?P<date>\d{2}\.\d{2}\.\d{4})$")
DUE_DATE_RE = re.compile(r"^Eräpäivä\s+(?P<date>\d{2}\.\d{2}\.\d{4})$")
BUYER_RE = re.compile(
    r"^Ostaja\s+(?P<name>[^,]+),\s*(?P<street>[^,]+),\s*(?P<postcode>\d{5})\s+"
    r"(?P<city>[^()]+?)\s*\(Y-tunnus\s+(?P<business_id>[\w-]+)\)$"
)
REFERENCE_RE = re.compile(r"^Viitenumero\s+(?P<value>\d+)$")
TABLE_HEADER_RE = re.compile(r"^Nimike\s+Määrä\s+A-hinta\s+Yhteensä$")
ITEM_RE = re.compile(
    r"^(?P<desc>Henkilöstöruokailu, (?:" + _MONTH_ALTERNATION + r") \d{4})\s+"
    r"(?P<qty>\d+)\s+ateria\s+(?P<unit_price>\d+,\d{2})\s+(?P<line_total>\d+,\d{2})$"
)
ITEM_DESC_RE = re.compile(
    r"^Henkilöstöruokailu, (?P<month>" + _MONTH_ALTERNATION + r") (?P<year>\d{4})$"
)
NET_RE = re.compile(r"^Veroton yhteensä\s+(?P<net>\d+,\d{2})\s*€$")
VAT_RE = re.compile(r"^ALV\s+(?P<rate>\d+)\s*%\s+(?P<amount>\d+,\d{2})\s*€$")
GROSS_RE = re.compile(r"^Maksettava\s+(?P<gross>\d+,\d{2})\s*€$")
FOOTER_RE = re.compile(
    r"^ALV-tunnus\s+(?P<vat_id>\S+)\s*·\s*Maksuehto:\s*(?P<terms>.+?)\s*·\s*"
    r"Pankkiyhteys\s+(?P<iban>\S+)\s*·\s*BIC$"
)
BIC_RE = re.compile(r"^(?P<bic>[A-Z0-9]{8}([A-Z0-9]{3})?)$")
PAYMENT_TERMS_RE = re.compile(r"^(?P<days>\d+)\s*pv\s*netto$")

ALLOWED_VAT_RATES = {"14": "14.0"}  # this supplier's product category is 14 % VAT only


class ParserLayoutError(Exception):
    """Raised when the document does not match the induced s7 layout exactly.

    An instance of this exception is a SUCCESS mode of the pipeline (it
    triggers the LLM fallback) -- never silently guess a value instead of
    raising this.
    """


def _money(text, field_name):
    m = re.fullmatch(r"(\d+),(\d{2})", text)
    if not m:
        raise ParserLayoutError(f"{field_name}: not a canonical Finnish amount: {text!r}")
    return f"{m.group(1)}.{m.group(2)}"


def _finnish_date(text, field_name):
    m = re.fullmatch(r"(\d{2})\.(\d{2})\.(\d{4})", text)
    if not m:
        raise ParserLayoutError(f"{field_name}: not a dd.mm.yyyy date: {text!r}")
    day, month, year = (int(g) for g in m.groups())
    try:
        return date(year, month, day)
    except ValueError as exc:
        raise ParserLayoutError(f"{field_name}: invalid calendar date {text!r}: {exc}") from exc


def _match(regex, line, label):
    m = regex.match(line)
    if not m:
        raise ParserLayoutError(f"expected {label}, got: {line!r}")
    return m


def parse(pdf_path: str) -> dict:
    """Parse one Lounastupa Helmi Oy (supplier s7) invoice PDF.

    Returns a record in the accepted-parse schema (schema_version 1.0).
    Raises ParserLayoutError the instant any expected landmark, label, or
    reconciling arithmetic check fails.
    """
    doc_id = Path(pdf_path).stem

    with pdfplumber.open(pdf_path) as pdf:
        if len(pdf.pages) != 1:
            raise ParserLayoutError(
                f"expected a single-page invoice, got {len(pdf.pages)} pages"
            )
        text = pdf.pages[0].extract_text()

    if not text:
        raise ParserLayoutError("no extractable text layer on page 1")

    lines = text.splitlines()
    idx = 0

    def next_line(label):
        nonlocal idx
        if idx >= len(lines):
            raise ParserLayoutError(f"reached end of page before finding {label}")
        line = lines[idx]
        idx += 1
        return line

    # --- Supplier header block -------------------------------------------------
    supplier_name = _match(SUPPLIER_NAME_RE, next_line("supplier name line"), "supplier name line")[
        "name"
    ].strip()

    addr_m = _match(SUPPLIER_ADDR_RE, next_line("supplier address line"), "supplier address line")

    # --- Invoice number / dates --------------------------------------------
    number_m = _match(INVOICE_NUMBER_RE, next_line("'Lasku <number>' line"), "'Lasku <number>' line")
    issue_date_obj = _finnish_date(
        _match(ISSUE_DATE_RE, next_line("'Laskun päivä' line"), "'Laskun päivä' line")["date"],
        "issue_date",
    )
    due_date_obj = _finnish_date(
        _match(DUE_DATE_RE, next_line("'Eräpäivä' line"), "'Eräpäivä' line")["date"],
        "due_date",
    )

    # --- Buyer block (wraps across 1-2 physical lines; join until Viitenumero) -
    buyer_parts = []
    while idx < len(lines) and not lines[idx].startswith("Viitenumero"):
        buyer_parts.append(lines[idx])
        idx += 1
    if idx >= len(lines):
        raise ParserLayoutError("did not find 'Viitenumero' line after buyer block")
    buyer_str = " ".join(buyer_parts)
    buyer_m = _match(BUYER_RE, buyer_str, "buyer block ('Ostaja ...(Y-tunnus ...)')")

    reference_m = _match(REFERENCE_RE, next_line("'Viitenumero' line"), "'Viitenumero' line")

    # --- Line item table ----------------------------------------------------
    _match(TABLE_HEADER_RE, next_line("item table header"), "item table header 'Nimike Määrä A-hinta Yhteensä'")

    item_lines = []
    while idx < len(lines) and not lines[idx].startswith("Veroton yhteensä"):
        item_lines.append(lines[idx])
        idx += 1
    if idx >= len(lines):
        raise ParserLayoutError("did not find 'Veroton yhteensä' line after item table")
    if not item_lines:
        raise ParserLayoutError("item table has no line items")

    parsed_lines = []
    for raw_line in item_lines:
        item_m = _match(ITEM_RE, raw_line, "invoice line item")
        desc = item_m["desc"]
        qty_text = item_m["qty"]
        unit_price = _money(item_m["unit_price"], "line unit_price")
        line_total = _money(item_m["line_total"], "line line_total")

        # Rounding mode is round-half-to-even (not round-half-up): confirmed by
        # 2025-04_s7_01 where 794.75 x 14% = 111.265 exactly, and the printed
        # ALV amount is 111.26, not 111.27.
        expected_total = (Decimal(qty_text) * Decimal(unit_price)).quantize(
            Decimal("0.01"), rounding=ROUND_HALF_EVEN
        )
        if expected_total != Decimal(line_total):
            raise ParserLayoutError(
                f"line arithmetic does not reconcile: {qty_text} x {unit_price} = "
                f"{expected_total}, printed line_total is {line_total}"
            )

        desc_m = _match(ITEM_DESC_RE, desc, "line description 'Henkilöstöruokailu, <kuukausi> <year>'")
        month_idx = FI_MONTHS[desc_m["month"]]
        year = int(desc_m["year"])
        if year != issue_date_obj.year or month_idx != issue_date_obj.month:
            raise ParserLayoutError(
                f"line item month/year ({desc_m['month']} {year}) does not match "
                f"issue_date month ({issue_date_obj.isoformat()})"
            )

        parsed_lines.append(
            {
                "description": desc,
                "quantity": qty_text,
                "unit": "ateria",
                "unit_price": unit_price,
                "vat_rate": "14.0",
                "line_total": line_total,
            }
        )

    # --- Totals block ---------------------------------------------------------
    net = _money(_match(NET_RE, next_line("'Veroton yhteensä' line"), "'Veroton yhteensä' line")["net"], "net")

    vat_m = _match(VAT_RE, next_line("'ALV' line"), "'ALV' line")
    rate_text = vat_m["rate"]
    if rate_text not in ALLOWED_VAT_RATES:
        raise ParserLayoutError(f"unexpected VAT rate for this supplier: {rate_text}%")
    vat_rate_canonical = ALLOWED_VAT_RATES[rate_text]
    vat_amount = _money(vat_m["amount"], "vat amount")

    gross = _money(_match(GROSS_RE, next_line("'Maksettava' line"), "'Maksettava' line")["gross"], "gross")

    # Reconcile: sum of line totals == net; net * rate == vat; net + vat == gross
    sum_of_lines = sum((Decimal(l["line_total"]) for l in parsed_lines), Decimal("0.00"))
    if sum_of_lines != Decimal(net):
        raise ParserLayoutError(
            f"sum of line totals ({sum_of_lines}) does not reconcile with printed net ({net})"
        )
    expected_vat = (Decimal(net) * Decimal(rate_text) / Decimal("100")).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_EVEN
    )
    if expected_vat != Decimal(vat_amount):
        raise ParserLayoutError(
            f"VAT arithmetic does not reconcile: {net} x {rate_text}% = {expected_vat}, "
            f"printed ALV amount is {vat_amount}"
        )
    expected_gross = Decimal(net) + Decimal(vat_amount)
    if expected_gross != Decimal(gross):
        raise ParserLayoutError(
            f"gross arithmetic does not reconcile: {net} + {vat_amount} = {expected_gross}, "
            f"printed Maksettava is {gross}"
        )

    # --- Footer (ALV-tunnus / Maksuehto / IBAN / BIC label) --------------------
    footer_m = _match(FOOTER_RE, next_line("footer line ('ALV-tunnus ... BIC')"), "footer line")
    bic_m = _match(BIC_RE, next_line("BIC code line"), "BIC code line")

    if idx != len(lines):
        raise ParserLayoutError(
            f"unexpected trailing content after BIC line: {lines[idx:]!r}"
        )

    supplier_business_id = addr_m["business_id"]
    supplier_vat_id = footer_m["vat_id"]
    if supplier_vat_id != "FI" + supplier_business_id.replace("-", ""):
        raise ParserLayoutError(
            f"supplier ALV-tunnus {supplier_vat_id!r} does not derive from "
            f"Y-tunnus {supplier_business_id!r}"
        )
    supplier_country = supplier_vat_id[:2]
    if supplier_country != "FI":
        raise ParserLayoutError(f"unexpected supplier country prefix: {supplier_country!r}")

    payment_terms = footer_m["terms"]
    terms_m = _match(PAYMENT_TERMS_RE, payment_terms, "payment terms '<N> pv netto'")
    expected_due = issue_date_obj + timedelta(days=int(terms_m["days"]))
    if expected_due != due_date_obj:
        raise ParserLayoutError(
            f"due_date {due_date_obj.isoformat()} is not issue_date "
            f"({issue_date_obj.isoformat()}) + {terms_m['days']} days "
            f"({expected_due.isoformat()})"
        )

    record = {
        "schema_version": SCHEMA_VERSION,
        "doc_id": doc_id,
        "supplier": {
            "name": supplier_name,
            "street": addr_m["street"],
            "postcode": addr_m["postcode"],
            "city": addr_m["city"],
            "country": supplier_country,
            "vat_id": supplier_vat_id,
            "business_id": supplier_business_id,
        },
        "buyer": {
            "name": buyer_m["name"],
            "street": buyer_m["street"],
            "postcode": buyer_m["postcode"],
            "city": buyer_m["city"],
            # Buyer VAT id is never printed on this layout; buyer country is
            # never printed either, and every one of the 6 induction
            # documents has the same Finnish buyer -- treated as fixed for
            # this layout (see overseer report).
            "country": "FI",
            "vat_id": None,
            "business_id": buyer_m["business_id"],
        },
        "invoice": {
            "number": number_m["number"],
            "type": "invoice",
            "issue_date": issue_date_obj.isoformat(),
            "supply_date": None,
            "due_date": due_date_obj.isoformat(),
            "payment_terms": payment_terms,
            "currency": "EUR",
            "po_number": None,
            "reference_type": "viitenumero",
            "reference_value": reference_m["value"],
            "original_invoice_number": None,
            "reverse_charge_mention": None,
        },
        "bank": {
            "iban": footer_m["iban"],
            "bic": bic_m["bic"],
            "bankgiro": None,
        },
        "lines": parsed_lines,
        "vat_summary": [
            {"rate": vat_rate_canonical, "base": net, "amount": vat_amount},
        ],
        "totals": {"net": net, "vat": vat_amount, "gross": gross},
    }
    return record


def _run_self_test(pairs):
    all_ok = True
    for pdf_path, json_path in pairs:
        doc_id = Path(pdf_path).stem
        try:
            result = parse(pdf_path)
        except ParserLayoutError as exc:
            print(f"FAIL {doc_id}: ParserLayoutError: {exc}")
            all_ok = False
            continue
        except Exception as exc:  # noqa: BLE001 - self-test must report, not hide, any error
            print(f"FAIL {doc_id}: unexpected {type(exc).__name__}: {exc}")
            all_ok = False
            continue

        with open(json_path, encoding="utf-8") as f:
            expected = json.load(f)

        if result == expected:
            print(f"PASS {doc_id}")
        else:
            all_ok = False
            print(f"FAIL {doc_id}: parsed record does not match accepted parse")
            for key in expected:
                if result.get(key) != expected.get(key):
                    print(f"       field {key!r} differs:")
                    print(f"         expected: {expected.get(key)!r}")
                    print(f"         parsed:   {result.get(key)!r}")
    return all_ok


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        print("usage: parser_s7.py (pdf json)+  |  parser_s7.py manifest.json", file=sys.stderr)
        sys.exit(2)

    if len(args) == 1 and args[0].endswith(".json"):
        with open(args[0], encoding="utf-8") as f:
            manifest = json.load(f)
        test_pairs = []
        for entry in manifest:
            if isinstance(entry, dict):
                test_pairs.append((entry["pdf"], entry["json"]))
            else:
                test_pairs.append((entry[0], entry[1]))
    else:
        if len(args) % 2 != 0:
            print("error: expected an even number of (pdf, json) path arguments", file=sys.stderr)
            sys.exit(2)
        test_pairs = list(zip(args[0::2], args[1::2]))

    ok = _run_self_test(test_pairs)
    sys.exit(0 if ok else 1)
