# Generated by the overseer step of the ERP Cleanup pipeline.
# Date: 2026-07-03
# Generating model: claude-sonnet-5 (Claude Code subagent)
#
# Source doc_ids (raw documents + their accepted LLM parses, used as the sole
# induction basis for this parser):
#   2025-01_ME2M_01, 2025-01_ME2M_02, 2025-01_ME2M_03, 2025-01_ME2M_04,
#   2025-02_ME2M_01, 2025-02_ME2M_02, 2025-02_ME2M_03, 2025-02_ME2M_04
#
# Induced from the LLM path's accepted parses; the answer key was never read.
#
# Document type: SAP ME2M "Bestellungen nach Material" (purchase orders by
# material) report. Pure stdlib, deterministic, no I/O.
#
# Layout notes (induced from the 8 sample documents):
#   - Header block (page 1 only):
#       Bestellungen nach Material ... Seite <n>     (title, repeats per page)
#       <dashes>                                     (bare separator, repeats per page)
#       Einkaufsorganisation: <code>   <company name> (company name discarded)
#       Selektionszeitraum: <DD.MM.YYYY> - <DD.MM.YYYY>
#       Datum: <DD.MM.YYYY>   Benutzer: <user>
#       [Selektionsvariante: <name>]                   (optional, discarded)
#   - A pipe-delimited table follows, framed by rules made only of '-' and '+'.
#     The frame/title/blank lines repeat verbatim on every form-feed page and
#     carry no data; they are skipped unconditionally rather than parsed by
#     position, so pagination never has to be special-cased.
#   - Columns are resolved BY LABEL from the header row on each occurrence
#     (split on '|', strip each cell), not by fixed character offsets, since
#     column widths vary between documents (they widen to fit the longest
#     vendor/material-text value in that particular report run).
#   - Rows for one vendor are contiguous and followed by a
#     "  Summe <full vendor name>   <amount> <currency>" subtotal line -
#     except that the subtotal can be pushed past a page break, landing on
#     the page *after* its data rows (observed on 2025-01_ME2M_02 and
#     2025-02_ME2M_02/03). Because all non-content boilerplate is skipped
#     uniformly, the parser just keeps one "pending vendor group" open across
#     that gap and closes it on the first "Summe" line it sees, wherever it
#     lands.
#   - Kreditorenname (vendor name) cells on data rows are frequently
#     truncated to fit the column width; the "Summe" line always carries the
#     FULL vendor name. vendor_number is recovered by matching the pending
#     group's (possibly truncated) row-level vendor name as a string prefix
#     of the subtotal's full name.

import re
from datetime import datetime

__all__ = ["parse"]

EXPECTED_COLUMNS = [
    "Bestellnr", "Pos", "Bestelldat.", "Lieferant", "Kreditorenname",
    "Material", "Kurztext", "Menge", "Nettopreis", "Nettowert", "Whg",
    "Noch offen Mge", "Noch offen Wert",
]

_FRAME_RE = re.compile(r'^[-+]+$')
_TITLE_RE = re.compile(r'^Bestellungen nach Material\b')
_VARIANTE_RE = re.compile(r'^Selektionsvariante:')
_EINKAUF_RE = re.compile(r'^Einkaufsorganisation:\s*(\S+)')
_SELEKTION_RE = re.compile(r'^Selektionszeitraum:\s*(.+)$')
_DATUM_RE = re.compile(r'^Datum:\s*(\d{2}\.\d{2}\.\d{4})\s+Benutzer:\s*(\S+)')
_QTY_UNIT_RE = re.compile(r'^(-?[0-9.,]+)\s+(\S+)$')


def _de_to_float(s: str) -> float:
    """Convert a German-locale number ('1.234,56', trailing-minus negative) to float."""
    s = s.strip()
    if not s:
        raise ValueError("empty numeric field")
    negative = False
    if s.endswith('-'):
        negative = True
        s = s[:-1].strip()
    if s.startswith('-'):
        negative = True
        s = s[1:].strip()
    s = s.replace('.', '').replace(',', '.')
    try:
        value = float(s)
    except ValueError:
        raise ValueError(f"cannot parse German-locale number: {s!r}")
    return -value if negative else value


def _de_date_to_iso(s: str) -> str:
    try:
        return datetime.strptime(s.strip(), "%d.%m.%Y").strftime("%Y-%m-%d")
    except ValueError:
        raise ValueError(f"cannot parse date: {s!r}")


def _split_row(line: str) -> list:
    parts = line.split('|')
    if len(parts) < 2 or parts[0].strip() != '' or parts[-1].strip() != '':
        raise ValueError(f"malformed pipe-delimited row: {line!r}")
    return [p.strip() for p in parts[1:-1]]


def _parse_qty_unit(cell: str):
    m = _QTY_UNIT_RE.match(cell.strip())
    if not m:
        raise ValueError(f"cannot parse quantity/unit cell: {cell!r}")
    return _de_to_float(m.group(1)), m.group(2)


def parse(text: str) -> dict:
    """Parse an SAP ME2M 'Bestellungen nach Material' report into structured data.

    Returns a dict with keys 'header', 'line_items', 'totals'
    (totals = {'vendor_subtotals': [...], 'grand_total': float}).
    Raises ValueError on any structural mismatch with the induced format.
    """
    lines = text.replace('\f', '\n').splitlines()

    header = {}
    line_items = []
    vendor_subtotals = []
    grand_total = None
    columns = None

    pending_vendor_number = None
    pending_vendor_name = None

    for raw_line in lines:
        line = raw_line.rstrip('\n')
        stripped = line.strip()

        if not stripped:
            continue
        if _TITLE_RE.match(stripped):
            continue
        if _FRAME_RE.match(stripped):
            continue
        if _VARIANTE_RE.match(stripped):
            continue

        m = _EINKAUF_RE.match(stripped)
        if m:
            header['purch_org'] = m.group(1)
            continue
        m = _SELEKTION_RE.match(stripped)
        if m:
            header['selection_scope'] = m.group(1).strip()
            continue
        m = _DATUM_RE.match(stripped)
        if m:
            header['report_date'] = _de_date_to_iso(m.group(1))
            header['user'] = m.group(2)
            continue

        if stripped.startswith('|'):
            cells = _split_row(line)

            if cells and cells[0] == 'Bestellnr':
                if cells != EXPECTED_COLUMNS:
                    raise ValueError(f"unexpected column header set: {cells}")
                columns = cells
                continue

            # Data row.
            if columns is None:
                raise ValueError("data row encountered before a column header row")
            if len(cells) != len(columns):
                raise ValueError(
                    f"data row has {len(cells)} cells, expected {len(columns)}: {line!r}"
                )
            row = dict(zip(columns, cells))

            if not row['Bestellnr'].isdigit():
                raise ValueError(f"unexpected Bestellnr cell (not numeric): {row['Bestellnr']!r}")
            try:
                item_no = int(row['Pos'])
            except ValueError:
                raise ValueError(f"cannot parse Pos as int: {row['Pos']!r}")

            qty, unit = _parse_qty_unit(row['Menge'])
            open_qty, open_unit = _parse_qty_unit(row['Noch offen Mge'])
            if open_unit != unit:
                raise ValueError(
                    f"unit mismatch between Menge ({unit}) and Noch offen Mge "
                    f"({open_unit}) on PO {row['Bestellnr']}"
                )

            vendor_number = row['Lieferant']
            vendor_name = row['Kreditorenname']

            line_items.append({
                "po_number": row['Bestellnr'],
                "item": item_no,
                "order_date": _de_date_to_iso(row['Bestelldat.']),
                "vendor_number": vendor_number,
                "vendor_name": vendor_name,
                "material": row['Material'],
                "material_text": row['Kurztext'],
                "quantity": round(qty, 3),
                "unit": unit,
                "net_price": round(_de_to_float(row['Nettopreis']), 2),
                "net_value": round(_de_to_float(row['Nettowert']), 2),
                "currency": row['Whg'],
                "still_to_deliver_qty": round(open_qty, 3),
                "still_to_deliver_value": round(_de_to_float(row['Noch offen Wert']), 2),
            })

            if pending_vendor_number is None:
                pending_vendor_number = vendor_number
                pending_vendor_name = vendor_name
            elif vendor_number != pending_vendor_number:
                raise ValueError(
                    f"PO {row['Bestellnr']} belongs to vendor {vendor_number}, but vendor "
                    f"{pending_vendor_number} ({pending_vendor_name!r}) has no subtotal line yet"
                )
            continue

        if stripped.startswith('Summe '):
            parts = stripped.split()
            if len(parts) < 3:
                raise ValueError(f"malformed subtotal line: {line!r}")
            currency = parts[-1]
            amount_str = parts[-2]
            name = ' '.join(parts[1:-2])
            if pending_vendor_number is None:
                raise ValueError(f"subtotal line for {name!r} has no open vendor group")
            if not name.startswith(pending_vendor_name):
                raise ValueError(
                    f"subtotal vendor name {name!r} does not extend the pending row's "
                    f"vendor name {pending_vendor_name!r}"
                )
            vendor_subtotals.append({
                "vendor_number": pending_vendor_number,
                "total_value": round(_de_to_float(amount_str), 2),
            })
            pending_vendor_number = None
            pending_vendor_name = None
            continue

        if stripped.startswith('Gesamtsumme'):
            parts = stripped.split()
            if len(parts) < 3:
                raise ValueError(f"malformed grand total line: {line!r}")
            if pending_vendor_number is not None:
                raise ValueError(
                    f"grand total reached while vendor {pending_vendor_number} "
                    f"({pending_vendor_name!r}) still has no subtotal line"
                )
            grand_total = round(_de_to_float(parts[-2]), 2)
            continue

        raise ValueError(f"unrecognized line in ME2M document: {line!r}")

    for key in ("purch_org", "selection_scope", "report_date", "user"):
        if key not in header:
            raise ValueError(f"missing header field: {key}")
    if columns is None:
        raise ValueError("no column header row found")
    if not line_items:
        raise ValueError("no line items found")
    if grand_total is None:
        raise ValueError("no Gesamtsumme (grand total) line found")
    if pending_vendor_number is not None:
        raise ValueError(
            f"document ended while vendor {pending_vendor_number} "
            f"({pending_vendor_name!r}) still has no subtotal line"
        )

    computed_total = round(sum(v['total_value'] for v in vendor_subtotals), 2)
    if abs(computed_total - grand_total) > 0.01:
        raise ValueError(
            f"sum of vendor subtotals ({computed_total}) does not match "
            f"grand total ({grand_total})"
        )

    return {
        "header": header,
        "line_items": line_items,
        "totals": {
            "vendor_subtotals": vendor_subtotals,
            "grand_total": grand_total,
        },
    }
