# Generated by the overseer step of the ERP Cleanup pipeline.
# Date: 2026-07-03
# Generating model: claude-sonnet-5 (Claude Code subagent)
#
# Source doc_ids (raw documents + their accepted LLM parses, used as the sole
# induction basis for this parser):
#   2025-01_MB52_01, 2025-01_MB52_02, 2025-01_MB52_03, 2025-01_MB52_04,
#   2025-02_MB52_01, 2025-02_MB52_02, 2025-02_MB52_03, 2025-02_MB52_04
#
# Induced from the LLM path's accepted parses; the answer key was never read.
#
# Document type: SAP MB52 "Lagerbestandsübersicht" (warehouse stock overview).
# Pure stdlib, deterministic, no I/O.
#
# --- Layout, as induced from the 8 examples ---------------------------------
# Page 1 only:
#   Lagerbestandsübersicht ... Seite <n>
#   ------------------------------------------------------------------
#   Werke: <code>[, <code>...]   <company name>          (company name unused)
#   Datum: <DD.MM.YYYY>   Benutzer: <user>
#   [Selektionsvariante: <name>]                          (optional, unused)
#   <blank>
#   Material   Materialkurztext   Einh  Frei verwendbar  In Qual.-prüf.  Gesperrt  Wert frei verw.  Whg
#   ------------------------------------------------------------------
# Every page (incl. page 1) then carries stock rows, hierarchically grouped:
#   Werk <code>  <city>                                   (unindented; sets plant)
#     Lagerort <code>                                     (2-space indent; sets storage location)
#       <material> <material_text> <unit> <qty1> <qty2> <qty3> <value> <currency>  (4-space indent)
# On a form-feed page break, only the title/dash/column-header lines repeat
# (never Werke:/Datum:/Selektionsvariante:, never Werk/Lagerort). This means a
# Lagerort's rows can resume directly after a page's column header with no
# repeated "Werk"/"Lagerort" line -- so plant/storage_location context must
# survive across the form feed. The raw form-feed byte itself lands on its own
# line and is whitespace, so it is skipped like any other blank line.
# At the very end (once per plant, in Werk order, then once overall):
#   * Werk <code> gesamt   <value> <currency>
#   * Gesamtwert           <value> <currency>
#
# Numbers are German-formatted ('.' thousands, ',' decimal). ST rows are
# integer quantities (no decimal comma); KG (and any other non-ST unit) rows
# carry exactly 3 decimals. Values are always 2-decimal money.
#
# Column widths (material_text padding, gaps) jitter between documents, so
# rows are parsed by token structure (search from the right for unit + three
# numeric quantities + value + currency), never by fixed character offsets.

import re

__all__ = ["parse"]

_NUM = r'\d{1,3}(?:\.\d{3})*(?:,\d+)?'

_RE_TITLE = re.compile(r'^Lagerbestandsübersicht\b')
_RE_DASHES = re.compile(r'^-+$')
_RE_WERKE = re.compile(r'^Werke:\s*(?P<plants>[0-9,\s]+?)\s{2,}(?P<company>.+?)\s*$')
_RE_DATUM = re.compile(
    r'^Datum:\s*(?P<d>\d{2})\.(?P<m>\d{2})\.(?P<y>\d{4})\s+Benutzer:\s*(?P<user>\S+)\s*$'
)
_RE_SELVAR = re.compile(r'^Selektionsvariante:')
_RE_COLUMN_HEADER = re.compile(r'^Material\s+Materialkurztext\b')
_COLUMN_HEADER_REQUIRED = (
    "Einh", "Frei verwendbar", "In Qual", "Gesperrt", "Wert frei verw", "Whg",
)

# Top-level ("Werk 1000  Tampere") -- no leading indent. Must not catch
# "Werke:" (no space right after "Werk") or "* Werk 1000 gesamt" (leading '*').
_RE_WERK = re.compile(r'^Werk\s+(?P<code>\S+)\s+(?P<city>.+?)\s*$')
# "  Lagerort 0001" -- indented under a Werk.
_RE_LAGERORT = re.compile(r'^\s+Lagerort\s+(?P<code>\S+)\s*$')

# A stock row: material code, free-text description (possibly truncated
# mid-word), unit, three quantities, value, currency. The description is
# matched non-greedily so the engine backtracks until it finds a token that
# (a) is all-uppercase letters (a plausible unit) and (b) is immediately
# followed by exactly three well-formed numbers, a well-formed money value,
# and a 3-letter currency code -- which is what actually disambiguates the
# unit from all-caps fragments inside the description (e.g. "DIN", or a
# description truncated down to a bare single capital letter).
_RE_MATERIAL = re.compile(
    r'^\s*(?P<material>\d{6,})\s+(?P<text>.*?)\s+(?P<unit>[A-Z]{1,3})\s+'
    r'(?P<qty1>' + _NUM + r')\s+'
    r'(?P<qty2>' + _NUM + r')\s+'
    r'(?P<qty3>' + _NUM + r')\s+'
    r'(?P<value>' + _NUM + r')\s+'
    r'(?P<currency>[A-Z]{3})\s*$'
)
# Cheap pre-check: does this line even look like it is trying to be a
# material row (indented, starts with a long digit run)? Used only to decide
# whether a full-match failure is a "material row" failure (loud, specific)
# or genuinely unrecognized furniture.
_RE_MATERIAL_LOOKS_LIKE = re.compile(r'^\s*\d{6,}\s')

_RE_WERK_TOTAL = re.compile(
    r'^\*\s*Werk\s+(?P<code>\S+)\s+gesamt\s+(?P<value>' + _NUM + r')\s+(?P<currency>[A-Z]{3})\s*$'
)
_RE_GRAND_TOTAL = re.compile(
    r'^\*\s*Gesamtwert\s+(?P<value>' + _NUM + r')\s+(?P<currency>[A-Z]{3})\s*$'
)


def _parse_number(raw):
    """'3.024,233' -> 3024.233 ; '3.940' -> 3940.0 ; '112' -> 112.0."""
    s = raw.strip()
    if not re.fullmatch(_NUM, s):
        raise ValueError("unparseable numeric token %r" % (raw,))
    s = s.replace('.', '').replace(',', '.')
    try:
        return float(s)
    except ValueError:
        raise ValueError("unparseable numeric token %r" % (raw,))


def _parse_quantity(raw, unit):
    """ST quantities are plain integers (thousands-dot only, no comma); all
    other units (KG, M, ...) carry exactly 3 decimals."""
    value = _parse_number(raw)
    if unit == "ST":
        if ',' in raw:
            raise ValueError(
                "ST quantity %r has a decimal comma, expected an integer" % (raw,)
            )
        return int(value)
    return round(value, 3)


def _parse_money(raw):
    return round(_parse_number(raw), 2)


def parse(text: str) -> dict:
    """Parse an SAP MB52 'Lagerbestandsübersicht' text export.

    Returns a dict with keys 'header', 'line_items', 'totals' matching the
    accepted-parse JSON schema for this document type. Raises ValueError if
    the document's structure does not match the induced MB52 layout.
    """
    if not text or not text.strip():
        raise ValueError("empty document")

    plants = None
    report_date = None
    user = None
    seen_column_header = False

    line_items = []
    plant_totals = []
    grand_total = None

    current_plant = None
    current_loc = None

    for raw_line in text.splitlines():
        line = raw_line.rstrip('\n')
        if not line.strip():
            continue

        stripped = line.strip()

        if _RE_TITLE.match(stripped) or _RE_DASHES.match(stripped):
            continue

        if _RE_SELVAR.match(stripped):
            continue

        m = _RE_WERKE.match(stripped)
        if m:
            plants = [p.strip() for p in m.group("plants").split(",") if p.strip()]
            continue

        m = _RE_DATUM.match(stripped)
        if m:
            report_date = "%s-%s-%s" % (m.group("y"), m.group("m"), m.group("d"))
            user = m.group("user")
            continue

        if _RE_COLUMN_HEADER.match(stripped):
            missing = [tok for tok in _COLUMN_HEADER_REQUIRED if tok not in stripped]
            if missing:
                raise ValueError(
                    "unknown column-header set (missing %s): %r" % (missing, stripped)
                )
            seen_column_header = True
            continue

        m = _RE_WERK.match(line)
        if m:
            current_plant = m.group("code")
            current_loc = None
            continue

        m = _RE_LAGERORT.match(line)
        if m:
            if current_plant is None:
                raise ValueError(
                    "Lagerort row encountered before any Werk context: %r" % (line,)
                )
            current_loc = m.group("code")
            continue

        if stripped.startswith("*"):
            m = _RE_WERK_TOTAL.match(stripped)
            if m:
                plant_totals.append({
                    "plant": m.group("code"),
                    "value_total": _parse_money(m.group("value")),
                })
                continue
            m = _RE_GRAND_TOTAL.match(stripped)
            if m:
                grand_total = _parse_money(m.group("value"))
                continue
            raise ValueError("unparseable totals row: %r" % (line,))

        m = _RE_MATERIAL.match(line)
        if m:
            if current_plant is None or current_loc is None:
                raise ValueError(
                    "material row appears before any Werk/Lagerort context: %r"
                    % (line,)
                )
            unit = m.group("unit")
            line_items.append({
                "material": m.group("material"),
                "material_text": m.group("text").strip(),
                "plant": current_plant,
                "storage_location": current_loc,
                "unit": unit,
                "unrestricted": _parse_quantity(m.group("qty1"), unit),
                "quality_inspection": _parse_quantity(m.group("qty2"), unit),
                "blocked": _parse_quantity(m.group("qty3"), unit),
                "value_unrestricted": _parse_money(m.group("value")),
                "currency": m.group("currency"),
            })
            continue

        if _RE_MATERIAL_LOOKS_LIKE.match(line):
            raise ValueError("unparseable material row: %r" % (line,))

        raise ValueError("unrecognized line in MB52 document: %r" % (line,))

    if plants is None:
        raise ValueError("missing 'Werke:' header line")
    if report_date is None or user is None:
        raise ValueError("missing or unparseable 'Datum:'/'Benutzer:' header line")
    if not seen_column_header:
        raise ValueError("missing line-item column header")
    if not line_items:
        raise ValueError("no line items found")
    if grand_total is None:
        raise ValueError("missing '* Gesamtwert' totals line")
    if not plant_totals:
        raise ValueError("missing '* Werk <code> gesamt' totals line(s)")

    header = {
        "plants": plants,
        "report_date": report_date,
        "user": user,
    }

    totals = {
        "plant_totals": plant_totals,
        "grand_value_total": grand_total,
    }

    return {
        "header": header,
        "line_items": line_items,
        "totals": totals,
    }
