# Generated by the overseer step of the ERP Cleanup pipeline.
# Date: 2026-07-03
# Generating model: claude-sonnet-5 (Claude Code subagent)
#
# Source doc_ids (raw documents + their accepted LLM parses, used as the sole
# induction basis for this parser):
#   2025-01_FBL3N_01, 2025-01_FBL3N_02, 2025-01_FBL3N_03, 2025-01_FBL3N_04,
#   2025-02_FBL3N_01, 2025-02_FBL3N_02, 2025-02_FBL3N_03, 2025-02_FBL3N_04
#
# Induced from the LLM path's accepted parses; the answer key was never read.
#
# Document type: SAP FBL3N "Sachkonten Einzelpostenliste" (G/L account line
# item list). Pure stdlib, deterministic, no I/O.

import re
from datetime import datetime

__all__ = ["parse"]

_DATE = r'\d{2}\.\d{2}\.\d{4}'
_MONEY = r'[\d.]+,\d{2}-?'

# --- Header key/value lines -------------------------------------------------
# These appear once, near the top of the document, in the order:
#   Buchungskreis: <code>   <company name>            (company name discarded)
#   Sachkonto: <code>   <account name>
#   Zeitraum: <DD.MM.YYYY> - <DD.MM.YYYY>
#   Datum: <DD.MM.YYYY>   Benutzer: <user>
#   [Selektionsvariante: <name>]                        (optional, discarded)

_RE_BUCHUNGSKREIS = re.compile(r'^Buchungskreis:\s*(\S+)', re.MULTILINE)
_RE_SACHKONTO = re.compile(r'^Sachkonto:\s*(\S+)\s+(.+)$', re.MULTILINE)
_RE_ZEITRAUM = re.compile(
    r'^Zeitraum:\s*(' + _DATE + r')\s*-\s*(' + _DATE + r')\s*$', re.MULTILINE
)
_RE_DATUM = re.compile(
    r'^Datum:\s*(' + _DATE + r')\s+Benutzer:\s*(\S+)', re.MULTILINE
)

# The column header repeats on every page (form-feed pagination). Its exact
# inter-column spacing varies from document to document (the numeric columns
# are right-aligned and can be wider than their labels), so the check below
# only fixes the label order/identity, not column widths.
_RE_COLUMN_HEADER = re.compile(
    r'^Buch\.datum\s+Belegnr\s+BelArt\s+S/H\s+Betrag\s+Steuerbetr\.\s+'
    r'AusglBeleg\s+Referenz\s+Text\s*$',
    re.MULTILINE,
)

_RE_TITLE = 'Sachkonten Einzelpostenliste'

# --- Line item rows ----------------------------------------------------------
# Buch.datum Belegnr    BelArt S/H          Betrag   Steuerbetr. AusglBeleg Referenz  Text
# Belegnr (document number) and AusglBeleg (clearing document) are always
# 10-digit SAP document numbers. AusglBeleg and Referenz are both optional
# (blank cell -> column simply absent from the row, since these are
# whitespace/token-separated, not fixed-column-sliced). Referenz is always an
# uppercase-letters-then-digits code, which is what lets us tell it apart
# from Text (free-form, mixed-case German words, possibly multi-word).
_RE_LINE = re.compile(
    r'^(?P<date>' + _DATE + r')\s+'
    r'(?P<docnum>\d{10})\s+'
    r'(?P<doctype>[A-Z]{2})\s+'
    r'(?P<dc>[SH])\s+'
    r'(?P<amount>' + _MONEY + r')\s+'
    r'(?P<tax>' + _MONEY + r')\s+'
    r'(?:(?P<clearing>\d{10})\s+)?'
    r'(?:(?P<reference>[A-Z]+\d+)\s+)?'
    r'(?P<text>\S.*)$'
)
_RE_DATE_START = re.compile(r'^' + _DATE)

# --- Totals block (end of report, once) --------------------------------------
# * Summe Soll        <amount>
# * Summe Haben        <amount>
# * Saldo              <amount>
# * Summe Steuerbetrag <amount>   (not part of the output schema; ignored)
_RE_TOTALS = re.compile(
    r'^\*\s*(Summe Soll|Summe Haben|Saldo|Summe Steuerbetrag)\s+(' + _MONEY + r')\s*$'
)


def _german_amount_to_float(raw):
    """'1.234,56' -> 1234.56 ; trailing '-' -> negative. Rounded to 2 dp."""
    s = raw.strip()
    negative = s.endswith('-')
    if negative:
        s = s[:-1]
    s = s.replace('.', '').replace(',', '.')
    try:
        value = float(s)
    except ValueError:
        raise ValueError("could not parse amount %r" % (raw,))
    if negative:
        value = -value
    return round(value, 2)


def _german_date_to_iso(raw):
    try:
        dt = datetime.strptime(raw.strip(), '%d.%m.%Y')
    except ValueError:
        raise ValueError("could not parse date %r" % (raw,))
    return dt.strftime('%Y-%m-%d')


def parse(text: str) -> dict:
    """Parse an SAP FBL3N 'Sachkonten Einzelpostenliste' text export.

    Returns a dict with keys 'header', 'line_items', 'totals' matching the
    accepted-parse JSON schema for this document type. Raises ValueError if
    the document's structure does not match the induced FBL3N layout.
    """
    if not text or not text.strip():
        raise ValueError("empty document")

    text = text.replace('\r\n', '\n').replace('\r', '\n')

    if _RE_TITLE not in text:
        raise ValueError(
            "missing report title %r -- not an FBL3N Sachkonten "
            "Einzelpostenliste export" % (_RE_TITLE,)
        )

    m = _RE_BUCHUNGSKREIS.search(text)
    if not m:
        raise ValueError("missing 'Buchungskreis:' header line")
    company_code = m.group(1)

    m = _RE_SACHKONTO.search(text)
    if not m:
        raise ValueError("missing 'Sachkonto:' header line")
    gl_account = m.group(1)
    gl_account_name = m.group(2).strip()

    m = _RE_ZEITRAUM.search(text)
    if not m:
        raise ValueError("missing or unparseable 'Zeitraum:' header line")
    period_from = _german_date_to_iso(m.group(1))
    period_to = _german_date_to_iso(m.group(2))

    m = _RE_DATUM.search(text)
    if not m:
        raise ValueError("missing or unparseable 'Datum:'/'Benutzer:' header line")
    report_date = _german_date_to_iso(m.group(1))
    user = m.group(2)

    if not _RE_COLUMN_HEADER.search(text):
        raise ValueError(
            "unknown column set: line-item column header does not match the "
            "induced 'Buch.datum Belegnr BelArt S/H Betrag Steuerbetr. "
            "AusglBeleg Referenz Text' layout"
        )

    header = {
        "company_code": company_code,
        "gl_account": gl_account,
        "gl_account_name": gl_account_name,
        "period_from": period_from,
        "period_to": period_to,
        "report_date": report_date,
        "user": user,
    }

    line_items = []
    totals_raw = {}

    for raw_line in text.split('\n'):
        line = raw_line.rstrip()
        if not line.strip():
            continue

        if _RE_DATE_START.match(line):
            m = _RE_LINE.match(line)
            if not m:
                raise ValueError("unparseable line-item row: %r" % (line,))
            line_items.append({
                "posting_date": _german_date_to_iso(m.group('date')),
                "document_number": m.group('docnum'),
                "document_type": m.group('doctype'),
                "debit_credit": m.group('dc'),
                "amount": _german_amount_to_float(m.group('amount')),
                "tax_amount": _german_amount_to_float(m.group('tax')),
                "clearing_document": m.group('clearing'),
                "reference": m.group('reference'),
                "text": m.group('text').strip(),
            })
            continue

        if line.lstrip().startswith('*'):
            m = _RE_TOTALS.match(line.strip())
            if not m:
                raise ValueError("unparseable totals row: %r" % (line,))
            label, amount_raw = m.group(1), m.group(2)
            totals_raw[label] = _german_amount_to_float(amount_raw)
            continue

        # Furniture: report title, dashed separators, repeated column
        # headers, pagination ("Seite N"), header key/value lines already
        # captured above, optional Selektionsvariante line, etc. Skip.

    if not line_items:
        raise ValueError("no line items found")

    missing = [
        label for label in ("Summe Soll", "Summe Haben", "Saldo")
        if label not in totals_raw
    ]
    if missing:
        raise ValueError("missing totals line(s): %s" % (", ".join(missing),))

    totals = {
        "sum_debit": totals_raw["Summe Soll"],
        "sum_credit": totals_raw["Summe Haben"],
        "balance": totals_raw["Saldo"],
    }

    return {
        "header": header,
        "line_items": line_items,
        "totals": totals,
    }
