# Generated by the overseer step of the ERP Cleanup pipeline.
# Date: 2026-07-03
# Generating model: claude-sonnet-5 (Claude Code subagent)
# Source doc_ids (SAP transaction VA05, "Liste Verkaufsbelege"):
#   2025-01_VA05_01, 2025-01_VA05_02, 2025-01_VA05_03, 2025-01_VA05_04,
#   2025-02_VA05_01, 2025-02_VA05_02, 2025-02_VA05_03, 2025-02_VA05_04
# Induced from the LLM path's accepted parses; the answer key was never read.
"""Deterministic parser for SAP VA05 "Liste Verkaufsbelege" text exports.

Pure standard-library implementation (re, datetime only). No file I/O, no
network access, nothing non-deterministic. The only public entry point is
``parse(text) -> dict``.

Format induced from the 8 example documents:

    Liste Verkaufsbelege ... Seite     1
    ------------------------------------
    Verkaufsorganisation: 1000   <company name, ignored>
    Zeitraum: DD.MM.YYYY - DD.MM.YYYY
    Datum: DD.MM.YYYY   Benutzer: <user>
    <blank line>
    |Verkaufsbeleg|Belegdatum|Auftraggeber|Material|       Menge|     Nettowert|Whg |Lieferstatus  |
    ------------------------------------------------------------------------------------------------
    | 5000010001    | 06.01.2025 | Rantanen Teollisuus Oy  | 60000406 |  376 ST | 28.346,45 | EUR | Vollständig au |
    ...
      Gesamtsumme                                                 735.453,65 EUR

Multi-page documents insert a form-feed character between pages and repeat
the "Liste Verkaufsbelege ... Seite N" title, the dashed rules, and the
pipe-delimited column-header row on each subsequent page. The
Verkaufsorganisation/Zeitraum/Datum meta block and the final "Gesamtsumme"
total each appear exactly once, on the first and last page respectively.
The parser handles this by scanning every line independently: it looks up
header metadata anywhere in the document (first match wins), skips any line
that is a repeated column-header row, and treats every other pipe-bounded
row as a line item — so pagination requires no special-casing beyond that.
"""

import re
from datetime import datetime

__all__ = ["parse"]

# The exact set of column labels the table header must contain (order does
# not matter, but every VA05 example uses this order). Any other set of
# labels means the report layout has changed and we must not guess.
_EXPECTED_COLUMNS = frozenset(
    {
        "Verkaufsbeleg",
        "Belegdatum",
        "Auftraggeber",
        "Material",
        "Menge",
        "Nettowert",
        "Whg",
        "Lieferstatus",
    }
)

_GERMAN_NUMBER_RE = re.compile(r"\d+(\.\d{3})*(,\d+)?")


def _parse_de_date(raw):
    """Convert 'DD.MM.YYYY' to an ISO 'YYYY-MM-DD' string."""
    s = raw.strip()
    try:
        dt = datetime.strptime(s, "%d.%m.%Y")
    except ValueError as exc:
        raise ValueError(f"unparseable date {raw!r}") from exc
    return dt.strftime("%Y-%m-%d")


def _parse_de_number(raw, field_name):
    """Convert a German-locale number ('1.234,56', trailing '-' negative) to float."""
    s = raw.strip()
    if not s:
        raise ValueError(f"empty numeric value for {field_name}")
    negative = s.endswith("-")
    if negative:
        s = s[:-1].strip()
    if not _GERMAN_NUMBER_RE.fullmatch(s):
        raise ValueError(f"unparseable German number {raw!r} for {field_name}")
    cleaned = s.replace(".", "").replace(",", ".")
    value = float(cleaned)
    return -value if negative else value


def _split_pipe_row(line):
    """Split a '|'-bounded row into its inner cells.

    Requires the line to both start and end with '|' (ignoring surrounding
    whitespace). Raises ValueError instead of guessing if that shape is not
    met, so malformed rows are rejected rather than silently mis-split.
    """
    parts = line.split("|")
    if len(parts) < 2 or parts[0].strip() != "" or parts[-1].strip() != "":
        raise ValueError(f"row is not a well-formed pipe-bounded table row: {line!r}")
    return parts[1:-1]


def _build_line_item(cells, col_index):
    def cell(name):
        return cells[col_index[name]].strip()

    sales_document = cell("Verkaufsbeleg")
    if not sales_document:
        raise ValueError("empty Verkaufsbeleg cell")

    doc_date = _parse_de_date(cell("Belegdatum"))
    sold_to = cell("Auftraggeber")
    material = cell("Material")

    menge_raw = cell("Menge")
    menge_parts = menge_raw.split()
    if len(menge_parts) != 2:
        raise ValueError(
            f"unparseable Menge cell (expected 'quantity unit'): {menge_raw!r}"
        )
    quantity_str, unit = menge_parts
    order_quantity = _parse_de_number(quantity_str, "order_quantity")

    net_value = round(_parse_de_number(cell("Nettowert"), "net_value"), 2)
    currency = cell("Whg")
    delivery_status = cell("Lieferstatus")

    if not delivery_status:
        raise ValueError("empty Lieferstatus cell")

    return {
        "sales_document": sales_document,
        "doc_date": doc_date,
        "sold_to": sold_to,
        "material": material,
        "order_quantity": order_quantity,
        "unit": unit,
        "net_value": net_value,
        "currency": currency,
        "delivery_status": delivery_status,
    }


def parse(text: str) -> dict:
    """Parse a VA05 "Liste Verkaufsbelege" export into a structured dict.

    Returns a dict with keys "header", "line_items", "totals" matching the
    accepted-parse schema. Raises ValueError on anything that does not match
    the induced format (unknown column set, wrong cell counts, unparseable
    cells, missing/duplicate totals) rather than guessing.
    """
    if not isinstance(text, str) or not text.strip():
        raise ValueError("empty document")

    # ---- header metadata (appears once, on the first page) ----
    m_org = re.search(r"Verkaufsorganisation:\s*(\S+)", text)
    if not m_org:
        raise ValueError("missing 'Verkaufsorganisation' header line")
    sales_org = m_org.group(1)

    m_period = re.search(
        r"Zeitraum:\s*(\d{2}\.\d{2}\.\d{4})\s*-\s*(\d{2}\.\d{2}\.\d{4})", text
    )
    if not m_period:
        raise ValueError("missing or unparseable 'Zeitraum' header line")
    period_from = _parse_de_date(m_period.group(1))
    period_to = _parse_de_date(m_period.group(2))

    m_datum = re.search(
        r"Datum:\s*(\d{2}\.\d{2}\.\d{4})\s+Benutzer:\s*(\S+)", text
    )
    if not m_datum:
        raise ValueError("missing or unparseable 'Datum'/'Benutzer' header line")
    report_date = _parse_de_date(m_datum.group(1))
    user = m_datum.group(2)

    header = {
        "sales_org": sales_org,
        "period_from": period_from,
        "period_to": period_to,
        "report_date": report_date,
        "user": user,
    }

    # ---- table rows (may span multiple form-feed-separated pages) ----
    header_cols = None
    col_index = None
    line_items = []

    for raw_line in text.splitlines():
        line = raw_line.rstrip("\n")
        stripped = line.strip()
        if not stripped or stripped[0] != "|":
            # Blank lines, form-feed markers, dashed rules, the title line,
            # the meta block, and the Gesamtsumme total all fall through
            # here untouched — none of them are pipe-bounded table rows.
            continue

        cells = _split_pipe_row(line)
        first_cell = cells[0].strip()

        if first_cell == "Verkaufsbeleg":
            labels = [c.strip() for c in cells]
            if len(labels) != len(set(labels)) or set(labels) != _EXPECTED_COLUMNS:
                raise ValueError(f"unknown column set in table header: {labels!r}")
            if header_cols is None:
                header_cols = labels
                col_index = {name: i for i, name in enumerate(labels)}
            elif labels != header_cols:
                raise ValueError(
                    f"inconsistent column headers across pages: "
                    f"{labels!r} != {header_cols!r}"
                )
            continue  # header row is not a data row

        if header_cols is None:
            raise ValueError("data row encountered before a column-header row")

        if len(cells) != len(header_cols):
            raise ValueError(
                f"row has {len(cells)} cells, expected {len(header_cols)}: {line!r}"
            )

        line_items.append(_build_line_item(cells, col_index))

    if header_cols is None:
        raise ValueError("no pipe-delimited column-header row found")
    if not line_items:
        raise ValueError("no line items found")

    # ---- grand total ----
    total_matches = re.findall(r"Gesamtsumme\s+(\S+)\s+EUR", text)
    if len(total_matches) != 1:
        raise ValueError(
            f"expected exactly one 'Gesamtsumme ... EUR' total line, "
            f"found {len(total_matches)}"
        )
    total_net_value = round(_parse_de_number(total_matches[0], "total_net_value"), 2)

    return {
        "header": header,
        "line_items": line_items,
        "totals": {"total_net_value": total_net_value},
    }
