"""Deterministic parser for SAP FBL1N (Kreditoren Einzelpostenliste /
vendor line item list) reports.

Generated by: the overseer step of the ERP Cleanup pipeline
Date: 2026-07-03
Generating model: claude-sonnet-5 (Claude Code subagent)
Source doc_ids (the 8 accepted LLM parses this parser was induced from):
    2025-01_FBL1N_01, 2025-01_FBL1N_02, 2025-01_FBL1N_03, 2025-01_FBL1N_04,
    2025-02_FBL1N_01, 2025-02_FBL1N_02, 2025-02_FBL1N_03, 2025-02_FBL1N_04

Induced from the LLM path's accepted parses; the answer key was never read.
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Optional

__all__ = ["parse"]

# --------------------------------------------------------------------------
# Constants describing the induced report format
# --------------------------------------------------------------------------

_STATUS_MAP = {
    "08": "cleared",
    "09": "partial",
    "0A": "open",
}

# Column header line is fixed width/spacing in every observed sample; built
# via explicit repeat-counts (rather than a literal string) so the spacing
# is unambiguous to a reader/maintainer.
_COLUMN_HEADER = (
    "St" + " " * 4 + "Belegnr" + " " * 4 + "BelArt" + " " + "Belegdatum" + " "
    + "Buchungsdatum" + " " + "Fälligkeit" + " " + "S/H" + " " * 10
    + "Betrag" + " " + "Whg" + " " * 2 + "AusglBeleg"
)

_PAGE_HEADER_RE = re.compile(r"^Kreditoren Einzelpostenliste\s+Seite\s+\d+\s*$")
_DASH_RE = re.compile(r"^-+$")
_KREDITOR_RE = re.compile(r"^Kreditor:\s+(\S+)\s+(.*)$")
_BUCHUNGSKREIS_RE = re.compile(r"^Buchungskreis:\s+(\S+)\s+(.*)$")
_STICHTAG_RE = re.compile(r"^Stichtag:\s+(\d{2}\.\d{2}\.\d{4})\s+Benutzer:\s+(\S+)\s*$")

_ROW_STATUS_RE = re.compile(r"^@([0-9A-Z]{2})@$")
_DATE_RE = re.compile(r"^\d{2}\.\d{2}\.\d{4}$")
_AMOUNT_RE = re.compile(r"^\d{1,3}(?:\.\d{3})*,\d{2}-?$")

_SUMME_OFFEN_RE = re.compile(r"^\*\s+Summe offen/teilweise\s+(\S+)\s+([0-9.,\-]+)\s*$")
_SUMME_AUSGL_RE = re.compile(r"^\*\s+Summe ausgeglichen\s+(\S+)\s+([0-9.,\-]+)\s*$")


# --------------------------------------------------------------------------
# Low-level value parsing
# --------------------------------------------------------------------------


def _parse_german_date(value: str) -> str:
    """DD.MM.YYYY -> ISO YYYY-MM-DD."""
    try:
        dt = datetime.strptime(value, "%d.%m.%Y")
    except ValueError as exc:
        raise ValueError(f"unparseable date: {value!r}") from exc
    return dt.strftime("%Y-%m-%d")


def _parse_german_amount(value: str) -> float:
    """'1.234,56' -> 1234.56 ; trailing '-' -> negative."""
    if not _AMOUNT_RE.match(value):
        raise ValueError(f"unparseable amount: {value!r}")
    negative = value.endswith("-")
    core = value[:-1] if negative else value
    number = float(core.replace(".", "").replace(",", "."))
    return -number if negative else number


# --------------------------------------------------------------------------
# Page splitting
# --------------------------------------------------------------------------


def _split_pages(text: str) -> list[str]:
    """Split the report into one raw block of text per vendor page.

    Vendor pages are separated by a form-feed character (\\x0c) sitting on
    its own line between the "* Summe ausgeglichen ..." line of one vendor
    and the "Kreditoren Einzelpostenliste" header of the next.
    """
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    raw_pages = normalized.split("\x0c")
    pages = [p.strip("\n") for p in raw_pages if p.strip()]
    if not pages:
        raise ValueError("document contains no vendor pages")
    return pages


# --------------------------------------------------------------------------
# Line-by-line page parsing
# --------------------------------------------------------------------------


class _LineCursor:
    """Sequential, fail-loud reader over a page's lines."""

    def __init__(self, lines: list[str]):
        self._lines = lines
        self._i = 0

    def next(self) -> str:
        if self._i >= len(self._lines):
            raise ValueError("unexpected end of page while parsing")
        line = self._lines[self._i]
        self._i += 1
        return line

    def peek(self) -> Optional[str]:
        if self._i >= len(self._lines):
            return None
        return self._lines[self._i]


def _parse_row(line: str) -> dict:
    # Right-aligned numeric columns (Betrag in particular) can be wider than
    # their header label, so this is deliberately token-based rather than
    # position/slice-based.
    tokens = line.split()
    if len(tokens) not in (9, 10):
        raise ValueError(f"unparseable row (unexpected token count): {line!r}")

    status_match = _ROW_STATUS_RE.match(tokens[0])
    if not status_match:
        raise ValueError(f"unparseable row (bad status token): {line!r}")
    code = status_match.group(1)
    if code not in _STATUS_MAP:
        raise ValueError(f"unknown status code {tokens[0]!r} in row: {line!r}")
    status = _STATUS_MAP[code]

    document_number = tokens[1]
    document_type = tokens[2]

    for tok in (tokens[3], tokens[4], tokens[5]):
        if not _DATE_RE.match(tok):
            raise ValueError(f"unparseable row (bad date {tok!r}): {line!r}")
    document_date = _parse_german_date(tokens[3])
    posting_date = _parse_german_date(tokens[4])
    due_date = _parse_german_date(tokens[5])

    debit_credit = tokens[6]
    if debit_credit not in ("S", "H"):
        raise ValueError(f"unparseable row (bad S/H value {debit_credit!r}): {line!r}")

    amount = _parse_german_amount(tokens[7])
    currency = tokens[8]
    clearing_document = tokens[9] if len(tokens) == 10 else None

    return {
        "status": status,
        "document_number": document_number,
        "document_type": document_type,
        "document_date": document_date,
        "posting_date": posting_date,
        "due_date": due_date,
        "debit_credit": debit_credit,
        "amount": amount,
        "currency": currency,
        "clearing_document": clearing_document,
    }


def _parse_totals(totals_lines: list[str]) -> list[dict]:
    if not totals_lines:
        raise ValueError("vendor page has no totals lines")

    order: list[str] = []
    data: dict[str, dict] = {}
    for line in totals_lines:
        m_offen = _SUMME_OFFEN_RE.match(line)
        m_ausgl = _SUMME_AUSGL_RE.match(line)
        if m_offen:
            currency, raw_amount, key = m_offen.group(1), m_offen.group(2), "open_total"
        elif m_ausgl:
            currency, raw_amount, key = m_ausgl.group(1), m_ausgl.group(2), "cleared_total"
        else:
            raise ValueError(f"totals line does not match induced pattern: {line!r}")

        amount = _parse_german_amount(raw_amount)
        entry = data.setdefault(currency, {})
        if key in entry:
            raise ValueError(f"duplicate {key} for currency {currency!r}")
        entry[key] = amount
        if currency not in order:
            order.append(currency)

    vendor_totals = []
    for currency in order:
        entry = data[currency]
        if "open_total" not in entry or "cleared_total" not in entry:
            raise ValueError(f"incomplete totals pair for currency {currency!r}")
        vendor_totals.append(
            {
                "currency": currency,
                "open_total": entry["open_total"],
                "cleared_total": entry["cleared_total"],
            }
        )
    return vendor_totals


def _parse_page(page: str) -> tuple[dict, dict]:
    lines = page.split("\n")
    cur = _LineCursor(lines)

    header_line = cur.next().rstrip()
    if not _PAGE_HEADER_RE.match(header_line):
        raise ValueError(f"unexpected page header: {header_line!r}")

    dash_line = cur.next().rstrip()
    if not _DASH_RE.match(dash_line):
        raise ValueError(f"expected dashed separator, got: {dash_line!r}")

    kreditor_line = cur.next().rstrip()
    m = _KREDITOR_RE.match(kreditor_line)
    if not m:
        raise ValueError(f"unparseable Kreditor line: {kreditor_line!r}")
    vendor_number, vendor_name = m.group(1), m.group(2).rstrip()

    buchungskreis_line = cur.next().rstrip()
    m = _BUCHUNGSKREIS_RE.match(buchungskreis_line)
    if not m:
        raise ValueError(f"unparseable Buchungskreis line: {buchungskreis_line!r}")
    company_code = m.group(1)

    stichtag_line = cur.next().rstrip()
    m = _STICHTAG_RE.match(stichtag_line)
    if not m:
        raise ValueError(f"unparseable Stichtag line: {stichtag_line!r}")
    key_date = _parse_german_date(m.group(1))
    user = m.group(2)

    blank_line = cur.next()
    if blank_line.strip() != "":
        raise ValueError(f"expected blank line after vendor meta block, got: {blank_line!r}")

    column_header_line = cur.next().rstrip()
    if column_header_line != _COLUMN_HEADER:
        raise ValueError(f"unknown column set: {column_header_line!r}")

    dash_line2 = cur.next().rstrip()
    if not _DASH_RE.match(dash_line2):
        raise ValueError(f"expected dashed separator, got: {dash_line2!r}")

    line_items: list[dict] = []
    totals_raw: list[str] = []
    seen_totals = False
    while True:
        line = cur.next()
        stripped = line.strip()
        if stripped == "":
            if cur.peek() is None:
                break
            continue
        if stripped.startswith("@"):
            if seen_totals:
                raise ValueError(f"data row found after totals lines: {stripped!r}")
            line_items.append(_parse_row(stripped))
        elif stripped.startswith("*"):
            seen_totals = True
            totals_raw.append(stripped)
        else:
            raise ValueError(f"unparseable row: {stripped!r}")

        if cur.peek() is None:
            break

    if not line_items:
        raise ValueError("vendor page has no line items")

    vendor_totals = _parse_totals(totals_raw)

    header = {
        "company_code": company_code,
        "key_date": key_date,
        "report_date": key_date,
        "user": user,
    }
    vendor = {
        "vendor_number": vendor_number,
        "vendor_name": vendor_name,
        "line_items": line_items,
        "vendor_totals": vendor_totals,
    }
    return header, vendor


# --------------------------------------------------------------------------
# Public entry point
# --------------------------------------------------------------------------


def parse(text: str) -> dict:
    """Parse an FBL1N vendor-line-item report into structured data.

    Returns {"header": {...}, "vendors": [...]}, matching the accepted
    LLM-parse schema for this document type. Raises ValueError on any
    structural surprise (unknown column set, unparseable row, malformed
    totals lines) rather than guessing.
    """
    if not isinstance(text, str) or not text.strip():
        raise ValueError("empty document")

    pages = _split_pages(text)

    doc_header: Optional[dict] = None
    vendors = []
    for page in pages:
        header, vendor = _parse_page(page)
        if doc_header is None:
            doc_header = header
        elif header != doc_header:
            raise ValueError(
                "inconsistent document header across vendor pages: "
                f"{doc_header!r} vs {header!r}"
            )
        vendors.append(vendor)

    return {"header": doc_header, "vendors": vendors}
